### ISSUE TITLE
[BUG] - facing issue formio/angular version deependencies with @angular/core 

### ISSUE THREAD

**Issue by Preethy1291** [formio/angular#1015]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. 
2. 
3. 

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by daneformio** [comment]
@Preethy1291 Can you please provide more information about your issues? What error messages are you seeing? When do you encounter these issues?
