### ISSUE TITLE
[Question] - [Custom Component] - Custom components are not maintain the state when dragging

### ISSUE THREAD

**Issue by dinbtechit** [formio/angular#1027]
Custom components are not maintaining the values/state when dragged.

1. I created a custom button component and have a property called buttonText to store the button text.

```ts
editform: () => {
return [{
 key: customOptions.buttonText,
 type: 'textfield'
 input: true,
 defaultValue: 'Complete Payment'
}]
```

2. Added to the form and modified the buttonText field to "Pay Now". Everything works fine up until this point.

But when we drag the custom button, it shows the default value of "Complete Payment" rather than the updated value "Pay Now".

![Kapture 2023-11-02 at 16 05 26](https://github.com/formio/angular/assets/17984781/c94b0fb6-1a4f-49cd-b5a0-f5cb9989b856)

Any idea how I can fix this?

**Comment by daneformio** [comment]
@dinbtechit Can you let us know what versions you are using?

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond, and we can resume the triage process.
