### ISSUE TITLE
class="form-control"

### ISSUE THREAD

**Issue by e404r** [formio/angular#1033]
class="form-control". how to change default

**Comment by travist** [comment]
You will need to add a new template to the renderer using the ```Formio.use(...)``` method like so.

```js
import { Formio } from '@angular/formio';
Formio.use({
  template: {...}
});
```

The contents of the template will be your custom template that overrides the classes of the rendered form. Please see https://help.form.io/developers/form-development/form-templates for examples on creating new templates.
