### ISSUE TITLE
Add custom  html 

### ISSUE THREAD

**Issue by e404r** [formio/angular#1034]
public static get InputTest(): SafeHtml {
      const inputHtml = `
        <input
          type="text"
          ngxTouchKeyboard
          ngxTouchKeyboardFullScreen
          #touchKeyboard="ngxTouchKeyboard"
          (focus)="touchKeyboard.openPanel()"
        />
      `;
    
      return inputHtml;
    }

after rendering   ngxTouchKeyboard nor woking

**Comment by travist** [comment]
This is not a question for Form.io renderer. This seems to be just a generic Angular input question. Please re-submit this question in the Angular issue queue.
