### ISSUE TITLE
[Question] Angular stable version 16 or higher

### ISSUE THREAD

**Issue by adhonay** [formio/angular#1037]
Do you have any predictions on how much a stable version of Formio will be for Angular 16 or higher?

I am currently using:

```
"@formio/js": "5.0.0-rc.27"
"@formio/angular": "6.0.0-rc.5"
```

And what would be the most stable and updated version today for Angular?

**Comment by travist** [comment]
We just released @formio/angular => 6.0.0 which is for Angular 16 and uses our "stable" version of our renderer which is formiojs@4.18.4.

We also released @formio/angular => 7.0.0 which is for Angular 17 which uses our "stable" version of our renderer which is formiojs.

We are also working on a new 5.x version of our renderer which is going to be published as @formio/js.  It has not yet been decided what versions we will use in Angular to pull in that version, but I suspect we will use 6.5.0 and 7.5.0 respectively.
