### ISSUE TITLE
Angular 17 and FormIO runtime error

### ISSUE THREAD

**Issue by pannirselvamm** [formio/angular#1054]
This error message is generated when I run my simple angular which has only the code below
-----------------------------------------------------------------------------------------------------------------
import { FormioModule } from '@formio/angular';

@Component({
  standalone: true,
  imports: [NxWelcomeComponent, RouterModule,FormioModule ],
  selector: 'web-latest-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
--------------------------------------------------------------------------------------------------
./node_modules/@formio/angular/fesm2022/formio-angular.mjs:3:0-60 - Error: Module not found: Error: Can't resolve 'formiojs'

\node_modules\@formio\angular\fesm2022'

I am using npx create-nx-workspace to create my angular project.  Tested with angular 17 and 16. Same error.

**Comment by Amir-MP** [comment]
i think you should install formiojs aswell , formiojs is dependency

**Comment by rohidaskakad** [comment]
I think , angular ivy doesn't support angular formio

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
