### ISSUE TITLE
[Custom Components] Custom Components View only mode.

### ISSUE THREAD

**Issue by yong980** [formio/angular#1058]
I have created a few custom component using formio in my current project. 

Right now I am trying to make my custom component view only like how the Form Renderer trigger it's view only mode. Question is there anyway I can customize viewOnly mode with custom component?

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
