### ISSUE TITLE
[Issue] Submit event is not firing in Form IO

### ISSUE THREAD

**Issue by MdFaisalSaeed** [formio/angular#1061]
I am using a Form IO submit button in one of my pages and on submit, I have added a popup, which has two buttons i.e. Proceed and Cancel. After clicking on Proceed button, I submit the form, but on cancel I close the popup and save the data but not submitting the form. 

Submit button is not firing for below conditions:
After clicking on submit button, popup opens. I click on cancel button and popup closes. Again, I click on Submit button, popup opens and again I click on cancel button and popup closed and if I try to click on submit button again, nothing happens.

**Comment by lane-formio** [comment]
Can you please provide any additional information such as what version of angular you are using and possibly a jsfiddle and/or video to demonstrate your issue?

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
