### ISSUE TITLE
[BUG]  Error installing dependencies for  8.0.0-rc.4 in angular 18

### ISSUE THREAD

**Issue by Nach0Git** [formio/angular#1083]
## Environment
Please provide as many details as you can:
running `npm I `should install dependencies without issues for angular 18
Per https://www.npmjs.com/package/ngx-bootstrap documentation
![image](https://github.com/formio/angular/assets/21264330/c04987ac-3c76-43d1-910e-a2f5430f41f9)

Currently the dependency is defined as:
![image](https://github.com/formio/angular/assets/21264330/5f9ccd3c-cc53-4954-a882-0163e1768a00)
- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 5.0.0
- Frontend framework: Angular 18
- Browser: All
- Browser version: All

## Observed behavior
 Additionally, if I install version 8.0.0-rc4 with angular 17 I see the following compiling error
 
![image](https://github.com/formio/angular/assets/21264330/99029a6a-6605-4940-b770-f340a7e372fb)

## Expected behavior
Need version 18 of 'ngx-bootstrap' dependency to support angular 18.

**Comment by KrakenTyio** [comment]
Temporary you can try in package.json

```
"overrides": {
    "@formio/angular": {
      "ngx-bootstrap": "latest"
    }
  }
```

**Comment by lane-formio** [comment]
Resolved with https://github.com/formio/angular/pull/1087
