### ISSUE TITLE
[Question] Angular 18 compatibility?

### ISSUE THREAD

**Issue by renan-f** [formio/angular#1100]
I would like to know what the forecast is for the release of the version compatible with Angular 18, as we are already close to version 19 as well.

**Comment by lane-formio** [comment]
8.0.0-rc.11 should be fairly stable, but we are coordinating its official release around the release of our 9.3.0 Enterprise Server and 5.0.0 renderer, which is expected in the next month or two.

**Comment by renan-f** [comment]
Thanks
