### ISSUE TITLE
[Question] Can I override modal edit option in all components?

### ISSUE THREAD

**Issue by ps91** [formio/angular#1101]
Hi,

I want to be able to change some aspects of modal edit option in components settings. I would like to be able to change, for example, the text on the button to open the modal and also the close button of the modal. Is it possivel to override those options? Or at least shouldn't we be able to set this options in the component settings when modal edit is selected?

Thanks.

**Comment by lane-formio** [comment]
<div>Agent Viktoryia Alennikava linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/50370">50370</a> for this issue.</div><br/>

**Comment by travist** [comment]
You can override the modal template using the following method.

https://help.form.io/developers/form-development/form-templates#overriding-templates

And here is the modal template.

https://github.com/formio/formio.js/blob/47de51a76c850f8f4a73b99e9866ba0c571c5661/src/components/_classes/componentModal/ComponentModal.js#L8C38-L8C52
