### ISSUE TITLE
Dynamically setting data set for select inputs

### ISSUE THREAD

**Issue by E2dwhy** [formio/angular#1112]
**Is your feature request related to a problem? Please describe.**
We are trying to dynamicaly set the data from the Select input

**Describe the solution you'd like**
We are trying to dynamicaly set the data from the Select input, that is, listening to key and key down events and update the data of the select dropdown so that we optimize the app to not load the entire dataset that is mainly about 8000 records.
Is there a way to make this work? and if yes can you guide us through?

**Describe alternatives you've considered**

**Additional context**

**Comment by lane-formio** [comment]
Duplicate issue.
@seeranjeeviramavel provided a solution here: https://github.com/formio/formio.js/issues/5928
