### ISSUE TITLE
reset button does not reset dropdown

### ISSUE THREAD

**Issue by gavieritei** [formio/angular#117]
Hi,

We have a form with multiple components, some (or many) of them are dropdowns (using the select component).
We have a Reset button with the reset action but there seems to be a difference for the reset event for dropdowns between ng2-formio and ng-formio.

If I select anything in a dropdown, in ng2-formio, the dropdown will not reset, but in ng-formio it seems to be working properly.

Is there a way to intercept the reset event in ng2-formio? Because there is only the (change) event, and I cannot differentiate between the reset or the form completion.

Thanks!

PS: using latest version of Chrome (on Windows) and latest ng2-formio+angular2.
PS2: Thanks for a great job!

**Comment by beniaminp** [comment]
Any fix?

Thank you!

**Comment by VladRM** [comment]
Hi guys,

Any news on this subject?

**Comment by VladRM** [comment]
I believe this bug does not reproduce in the latest version.
