### ISSUE TITLE
Plugin hooks are not being fired when using <formio> component

### ISSUE THREAD

**Issue by asalhani** [formio/angular#178]
@travist @Vercjames @YuryRybakSoftensity @randallknutson

I have a requirement were I have to modify the HTTP request which is being fired on loading resources/forms. I checked the documentation and I found that Formio.js has [Plugin hooks.](https://github.com/formio/formio.js/wiki/JavaScript-API#plugin-hooks) 

I configured a simple plugin as instructed.
```
 let simplePlugin = {
            priority: 0,
            init: function(formio) {
                debugger;
            },
            preRequest: function (requestArgs) {
                debugger;
            },
            request: function(requestArgs){
                debugger;
            },
            wrapRequestPromise: function(promise, requestArgs){
                debugger
                return promise;
            },
            preStaticRequest: function(requestArgs){
                debugger;
            },
            staticRequest: function(requestArgs){
                debugger;
            },
            wrapStaticRequestPromise: function(promise, requestArgs){
                debugger
                return promise;
            }
        };
        Formio.registerPlugin(simplePlugin, 'simplePlugin');
```

The case: the hooks is being fired when loading the new builder component. I designed a simple form which has a nested form component on it. When I open the form is submission mode, I’m expecting that one of the hooks should be fired too so I can modify the HTTP request headers before it’s being sent to the server. Unfortunately, nothing happened and the request bypassed all the hooks.

I loaded the same form but this time using pure formio.js library, the hooks there are working as expected. 

So either I’m doing something wrong or there is a bug in <formio> component which prevents hooks from being fired.

Appreciate your comment on this issue ASAP

**Comment by asalhani** [comment]
@jhen1422  @travist @Vercjames @YuryRybakSoftensity @randallknutson

Any update so far?

**Comment by wag110894** [comment]
Hello  Asalhani,
This is William with the Form.io support team. Thanks for reaching out. 

Form.io offers support packages as well as development services to help with your application. These services connect you directly with a Form.io developer and can be a huge help with your app. Please let me know if you’re interested, I’d be more than happy to send you additional information.

Please let me know if you have any further questions or concerns. 

Thanks,
William Gay
Form.io Support

**Comment by bandman0226** [comment]
I would also like to know. We are experiencing the same issues.

**Comment by wag110894** [comment]
Please contact support@form.io for more information in regards to our support packages.

**Comment by bandman0226** [comment]
We had downgraded versions and got by because it was working as intended with an older version but due to other bugs we are needed to upgrade. The upgrade in turn seems to be breaking this. Like we have before we used this documentation to set up a plugin https://github.com/formio/formio.js/wiki/Fetch-Plugin-API and tried using the plugin hooks but they are not working.

**Comment by travist** [comment]
Make sure that you are registering it on the ```Formio``` instance that is coming from the angular-formio library like so.

```js
import { Formio } from 'angular-formio';
...
...
Formio.registerPlugin(simplePlugin, 'simplePlugin');
```
