### ISSUE TITLE
getUrlParts() returns null.

### ISSUE THREAD

**Issue by Hamix** [formio/angular#194]
Hi
I'm using Angular 6.
I've configured formio by implementing `FormioAppConfig `, it seems correct because the path URL that I've traced is "https://api.form.io/form" but below line: 
`var hostparts = this.getUrlParts(path);`
returns null.
`var hostName = hostparts[1] + hostparts[2];`
> AppComponent.html:16 ERROR TypeError: Cannot read property '1' of null
>     at new Formio (Formio.js:139)
>     at FormBuilder.setForm (Form.js:74)
>     at FormBuilder.render (Form.js:109)
>     at Function.push../node_modules/formiojs/FormBuilder.js._Formio2.default.builder (FormBuilder.js:102)
>     at FormBuilderComponent.push../node_modules/angular-formio/components/formbuilder/formbuilder.component.js.FormBuilderComponent.ngAfterViewInit (formbuilder.component.js:32)
>     at callProviderLifecycles (core.js:9567)
>     at callElementProvidersLifecycles (core.js:9541)
>     at callLifecycleHooksChildrenFirst (core.js:9531)
>     at checkAndUpdateView (core.js:10467)
>     at callViewAction (core.js:10699)

Thanks.

**Comment by Miskamyasa** [comment]
this.getUrlParts(path) || []
does the job

**Comment by spicter** [comment]
Any news on this?

I'm using my own backend - not using the formio backend.
It worked perfectly for some days - and suddenly I get the 'getUrlParts() returns null.' error

Any idea?

**Comment by travist** [comment]
We have not made a change to this code in over 2 years so I am not sure what could be causing the problem other than maybe the browsers behave differently now and do not return values expected by this function. What browsers are you using to reproduce this issue?

**Comment by spicter** [comment]
Hi Travis,

first of all great thx for your fantastic framework.

It’s one of the rare frameworks which just works!

it only fails if you do totally crazy things with it - I tried to include the Renderer as a custom component in the Builder :-)

This messed up everything :-)

Sorry the disturbance !

Thx again

Andreas

**Comment by flinden68** [comment]
Currently I have the same problem with Angular 11. But I don't think this is causing the issue. 
When I add a url to a form on form.io it renders correctly
When I change to a local url, like http://localhost:3100/formname it breaks with the error as shown above
