### ISSUE TITLE
Documentation on PDF example

### ISSUE THREAD

**Issue by mbagliojr** [formio/angular#213]
How would I go about doing something like the PDF example? Is there any documentation around this?

**Comment by wag110894** [comment]
Hello Mike,

This is William with the Form.io support team. Thank you for reaching out!
When you create a form in the form.io portal, you have the option of creating a web form or PDF form. If you choose pdf form you can upload a pdf and turn it into a form. In addition, if you need a pdf version of a form, you can use the download endpoint to get a PDF generated version of the form submission.
Here is the link to our PDF Help Docs: https://help.form.io/userguide/pdf/ 
Please let me know if you have any further questions or concerns.

Thanks, 
William Gay 
Form.io Developer Support

**Comment by jftsaraiva** [comment]
@wag110894 but how can we use PDF form in one Angular App without using form.io portal?

**Comment by travist** [comment]
LIke this https://formio.github.io/angular-demo/#/forms/pdf.

This works by just making your pdf display mode "pdf" and our renderer will just render it correctly.

**Comment by jftsaraiva** [comment]
@travist this link (https://formio.github.io/angular-demo/#/forms/pdf) uses form.io portal:

```
https://files.form.io/pdf/58b78b87f5609a0070f3f456/file/849bb08d-a880-5bb9-bbe6-7d7aac115123.html?id=e72lo9v
```
without using form.io portal to store pdf I can't find any working example.


In that angular demo on Form Manager (Form Builder) we can select 'Pdf' as Form Type:

![image](https://user-images.githubusercontent.com/2278476/59800553-cfe81800-92de-11e9-91b6-b14ed79d8b04.png)

Toolbox changes to:
![image](https://user-images.githubusercontent.com/2278476/59800812-6e747900-92df-11e9-81c9-cc77575f98c4.png)

but nothing else works. We can't upload or select a pdf file and src is:

 ![image](https://user-images.githubusercontent.com/2278476/59800739-4dac2380-92df-11e9-8644-9da6404361c9.png)

if we drag and drop a component does nothing. It's always a blank area:

![image](https://user-images.githubusercontent.com/2278476/59800998-dfb42c00-92df-11e9-80e2-85f045b0444c.png)

Do you have any working example of PDF Form (with builder and with render) without using form.io portal? 
We would like to use PDF Form on-premise. Is this possible?

**Comment by travist** [comment]
You can deploy our PDF Server into your own environment (with a license) and this will support your own domain names. We do not have an Open Source version of our PDF solution, so this is currently the only way to get this working in your own environment.

**Comment by Sansem2** [comment]
Hi, 
I am using Forms.io and I am interested in getting a paid account but I have few questions regarding pdf download, 
I have a requirement of downloading filled form as pdf and saving it on azure, can we achieve this from formbuilder in forms.io interface without writing a piece of code for it.
Please help me with the same.

Thanks,
Seema Sharma

**Comment by travist** [comment]
The only thing that we do not provide is the auto-upload to azure, but we should cover the generation of the PDF with the following API endpoint https://apidocs.form.io/#634ac0f8-0584-4edb-889f-79ee25404cc1

**Comment by wag110894** [comment]
Hello @barwalgayatri,

Thanks for reaching out. Our PDF functionality is only available on our Commerical Application. Please contact sale@form.io if you are interested in getting our PDF functionality.

**Comment by prateekjsingh** [comment]
Hi FormIO team,
I am using FormIO library's minified version to embed the FormBuilder into my application.
The ask is to generate and save a PDF version of the Form at the time of submit.

From the documentation it seems like we can use the PDF basic server for free and I need to get a license for PDF server plus. 

Can you please confirm which API method can be used to generate the FORM pdf at the time of submission?

Thanks
Prateek Jeet Singh
