### ISSUE TITLE
Options have not affect

### ISSUE THREAD

**Issue by dolphinsd** [formio/angular#215]
Here is config of render and options have no effect on messages.

<formio #formView [form]="template" [submission]="submission" options="options" (submit)="formSubmit($event)" [refresh]="refreshForm"></formio>

component defines
 options: any = {
        errors: {},
        alerts: {}
    };
with 
_.merge(this.options.errors, { message: this.l('FormErrors') });
        _.merge(this.options.alerts, { submitMessage: this.l('SavedSuccessfully') });

result is default messages are used.

**Comment by edwinanciani** [comment]
Hi,

There was a problem with conditionals when the alerts are sent to the form.  
This PR #218 could fix this issue.

**Comment by ZenMasterJacob20011** [comment]
The PR has fixed the issue. Closing this thread.
