### ISSUE TITLE
"Uncaught (in promise): [object Object]" when submit content with errors

### ISSUE THREAD

**Issue by JoeyLi-1** [formio/angular#217]
Hi There,

I had encountered a wired issue.
I want to allow my client to submit unfinished forms as draft. But if some required field is missing, it will pop this error in the console panel.
![image](https://user-images.githubusercontent.com/20162464/47634570-efce9e00-db8c-11e8-987d-0d177b44aa53.png)

To reproduce this issue just change the property of submit button "disableOnInvalid" to false of the demo project. And then go to the simple form (http://localhost:4200/forms/simple) 
![image](https://user-images.githubusercontent.com/20162464/47634673-4f2cae00-db8d-11e8-9459-32db912f3b2e.png)

I just hacked in the source code line935 of "node_module/formiojs/formio.js" and add this "result.components[4].disableOnInvalid = false;"

I had tried lots of ways to catch the exception, but all failed. Could some body help me on this issue? Thank you!

Version: latest;
Angular version: 6.0.0;

**Comment by JoeyLi-1** [comment]
@travist Seems it needs a catch at line 1194 (Webform.js)
if (!before) {
        return this.beforeSubmit(options).then(function () {
          return _this15.executeSubmit(options);
        }).catch((err) => {
          console.log(err);
        });
If I added this catch, then the console error disappeared. Please confirm if this is the right fix. Thank you!

**Comment by travist** [comment]
Thanks for debugging @JoeyLi-1 

This code is here in the core renderer @ https://github.com/formio/formio.js/blob/master/src/Webform.js#L1138

Pull requests welcome.

**Comment by JoeyLi-1** [comment]
@travist Done, please review https://github.com/formio/formio.js/pull/760.

**Comment by daspilker** [comment]
This has not been fixed.

 formio/formio.js#760 has been reverted: https://github.com/formio/formio.js/commit/211bbcf3dd1068f56113596a390fd0ae21bd8e93

**Comment by travist** [comment]
Yeah, this probably needs to be done within this library instead of the core renderer. We will add it to our list, but it would go much faster if the community jumped in and tool a look at a resolution. We are backed up with more critical items.

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
