### ISSUE TITLE
Validation not getting triggered On blur 

### ISSUE THREAD

**Issue by GangulyPriti** [formio/angular#238]
We are using angular-formio version 3.9.0.

We have set the ValidateOn property of a component to trigger validation on " blur" . 
Validations are getting triggered for the first time on blur of component , onward its getting triggered on Change.

However we need to trigger validations on blur only.

**Comment by travist** [comment]
We will add this to our backlog to investigate. Thanks.

**Comment by DevPriti** [comment]
Any Updates...
