### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by aakarshbaiju** [formio/angular#240]
I am trying to integrate angular formio on an existing angular 4 project in which I particularly require the formbuilder feature. I have tried the latest (3.9.5) release of the plugin as well as the first release in which formbuilder feature was initially added (2.0.0-alpha.3) but the same error pops up. The issue however does not seem to be there for the 1.10 release which however doesn't have formbuilder.

These are the dependencies currently used in the project:
"dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/material": "2.0.0-beta.12",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "@angular/router": "4.4.6",
    "@compodoc/compodoc": "1.0.4",
    "@covalent/core": "1.0.0-beta.8-1",
    "@covalent/http": "1.0.0-beta.8-1",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-beta.5",
    "@swimlane/dragula": "3.7.3",
    "@swimlane/ngx-dnd": "3.1.0",
    "@types/algoliasearch": "3.24.5",
    "@types/file-saver": "1.3.0",
    "@types/hammerjs": "2.0.35",
    "algoliasearch": "3.24.7",
    "algoliasearch-helper": "2.23.0",
    "angular-cropperjs": "0.1.5",
    "angular-formio": "2.0.0-alpha.3 ",
    "angular-froala-wysiwyg": "2.7.2",
    "angular2-uuid": "1.1.1",
    "angularfire2": "4.0.0-rc0",
    "bootstrap": "4.0.0-beta.2",
    "core-js": "2.5.1",
    "file-saver": "1.3.3",
    "firebase": "4.3.0",
    "font-awesome": "4.7.0",
    "hammerjs": "2.0.8",
    "lodash": "4.17.4",
    "ng2-breadcrumb": "0.5.14",
    "ng2-dnd": "4.2.0",
    "ng2-nouislider": "1.7.4",
    "ng2-select": "1.2.0",
    "ng2-validation": "4.2.0",
    "ngx-color-picker": "4.5.0",
    "ngx-gallery": "4.3.0",
    "ngx-uploader": "4.2.1",
    "nouislider": "9.2.0",
    "raven-js": "3.20.1",
    "rxjs": "5.5.2",
    "ts-helpers": "1.1.2",
    "zone.js": "0.8.18"
  }

Error: Metadata version mismatch for module /node_modules/angular-formio/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /src/app/app.module.ts, resolving symbol AppModule in /src/app/app.module.ts

**Comment by travist** [comment]
This package.json looks to be from a very old version. We are only supporting the latest version, which I have not tested with Angular 4 in a while. Are you saying that our latest no longer works with Angular 4.x?

**Comment by LegacyCoder** [comment]
As far as the package.json is concerned it indeed is quite old, but I have tried integrating the module on a freshly scaffolded angular 4 app with the latest stable release (version 4.4.7) and same issue persists, so yeah I believe the latest version or atleast the versions since the formbuilder inclusion doesn't work for Angular 4.x

**Comment by LegacyCoder** [comment]
We have been trying to maintain Angular 4 at present since upgrading right now is not a feasible option, although I might consider upgrading if there is no other way.
