### ISSUE TITLE
immutable fields

### ISSUE THREAD

**Issue by dolphinsd** [formio/angular#243]
We would like to have immutable fields on our form. Which means once the form is submitted those fields cannot be edited. How do we accomplish such a thing when form is loaded for editing and we want to mark some fields readonly? Thanks.

**Comment by randallknutson** [comment]
You can do this by adding "hideComponents" attribute to the formio component. For example <formio [hideComponents]="['one', 'two']"></formio>

**Comment by dolphinsd** [comment]
@randallknutson thanks. We still want to display them, but in readonly mode

**Comment by randallknutson** [comment]
We currently only have a hideComponents list. It makes sense to have a "disableComponents" list as well. Another way to do this is to set the disabled flag in the builder if they are always disabled. If they need to be dynamic, you can also iterate over the form components and set the disabled flag on any fields.

**Comment by dolphinsd** [comment]
@randallknutson , I tried [hideComponents]="['submit']" to hide submit button. It does not hide the button. Any idea why, should open another issue? 
`<formio #formView [form]="template" [hideComponents]="['submit']" [readOnly]="true"></formio>
`

![19b03fab6f39e40ee84b45cc6f383312](https://user-images.githubusercontent.com/3460517/55527026-33ea3100-564c-11e9-8a8a-1035d832730a.png)

**Comment by dmenne** [comment]
Same for me:

```
<formio 
  src="https://examples.form.io/example" 
  [hideComponents]="['firstName', 'phoneNumber']">
</formio>
```
Everything in the example form is visible

**Comment by dmenne** [comment]
Looks like @randallknutson 's comment about hideComponents refers to the AngularJs version. There is no hideComponents in the Angular 2 version. (https://github.com/formio/angular-formio/wiki/Data-Table)

**Comment by travist** [comment]
This may be a bug. We will investigate.

**Comment by jhen1422** [comment]
@dmenne Thank you for the report. We have a created a ticket for the issue and will review during our planning meeting next week. Please note, we welcome pull requests in this library. If you need this item expedited, please feel free to contact support@form.io for pricing.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
