### ISSUE TITLE
Question for custom formbuilder

### ISSUE THREAD

**Issue by eren186** [formio/angular#259]
HI 
 I need to   custom formbuilder‘s   components title
 then I looked  #241 and url(http://formio.github.io/formio.js/app/examples/custombuilder.html) 
but after  i custom   the formbuilder i got two component list  like this, and  when the component drag to the form it doesn't work.
![image](https://user-images.githubusercontent.com/48199905/53718279-b1782100-3e95-11e9-9ea9-c6fbafbf1fd1.png)
can u tell me where i'm doing wrong? or is there a easy way to  custom formbuilder‘s   components title?
<form-builder #fb [form]="form" (change)="onChange($event)"></form-builder>
`let builder=this.element.nativeElement.children[0].children[0];
    const Formio = require('formiojs').Formio;
 
    Formio.builder(this.builder, {}, {
      builder: {
        basic: false,
        advanced: false,
        data: false,
        customBasic: {
          title: '常用控件',
          default: true,
          weight: 0,
          components: {
            textfield: true,
            textarea: true,
            email: true,
            phoneNumber: true
          }
        },
        custom: {
          title: 'User Fields',
          weight: 10,
          components: {
            firstName: {
              title: 'First Name',
              key: 'firstName',
              icon: 'fa fa-terminal',
              schema: {
                label: 'First Name',
                type: 'textfield',
                key: 'firstName',
                input: true
              }
            },
            lastName: {
              title: 'Last Name',
              key: 'lastName',
              icon: 'fa fa-terminal',
              schema: {
                label: 'Last Name',
                type: 'textfield',
                key: 'lastName',
                input: true
              }
            },
            email: {
              title: 'Email',
              key: 'email',
              icon: 'fa fa-at',
              schema: {
                label: 'Email',
                type: 'email',
                key: 'email',
                input: true
              }
            },
            phoneNumber: {
              title: 'Mobile Phone',
              key: 'mobilePhone',
              icon: 'fa fa-phone-square',
              schema: {
                label: 'Mobile Phone',
                type: 'phoneNumber',
                key: 'mobilePhone',
                input: true
              }
            }
          }
        },
        layout: {
          components: {
            table: false
          }
        }
      },
      editForm: {
        textfield: [
          {
            key: 'api',
            ignore: true
          }        
        ]
      }
    }).then(function(builder) {
      builder.on('saveComponent', function() {
        console.log(builder.schema);
      });
    });`

**Comment by randallknutson** [comment]
We've seen this issue recently where the sidebar ends up duplicated on the form. We are opening a ticket to get this fixed. We believe it has something to do with when the form gets refreshed, the sidebar doesn't get cleared correctly.

**Comment by eren186** [comment]
thank you @randallknutson   i will wait this issue fixed.
is there have other way to localized component's title  ?

**Comment by randallknutson** [comment]
You can also import Components from formiojs and do

Component.addCompoonent('textfield', TextField);

This is more of a programmatic override of components.
