### ISSUE TITLE
Instantiate the FormioWizard class

### ISSUE THREAD

**Issue by irsmart** [formio/angular#280]
I get this warning in the browser "You need to instantiate the FormioWizard class to use this form as a wizard" when I load a wizard form. However, I cannot find any information in the documentation on what to do apart from the old AngularJS documentation that says to use <formio-wizard .....> which doesn't work.

Can anyone help?

**Comment by y16i** [comment]
I'm not sure exact your situation without your code. I'm assuming you are trying to use wizard mode. This is what I did.

html: <formio [form]="json"></formio>

Use a panal type for a page of wizard and add "display":"wizard".
e.g.)
ts: this.json = {
 "components": [
  {
     "type": "panel",
     "title": "wiz1"
  },
  {
     "type": "panel",
     "title": "wiz2"
  }
 ],
 "display": "wizard"
}

**Comment by irsmart** [comment]
The JSON has the panel type and display:wizard as I'm using the formio code to produce the JSON. 

So for example the following very simple two pager produces the warning mentioned in the original post:

{"_id":"5cab40cfec9dd94d4f71f04b","type":"form","tags":["common"],"owner":"5cab3f5aec9dd94d4f71f04a","components":[{"type":"panel","title":"Page 1","components":[{"key":"page1Content","label":"Content","input":false,"tag":"h1","attrs":[{"value":"","attr":""}],"className":"","content":"Form X","type":"htmlelement","hideLabel":true,"tags":[],"conditional":{"show":"","when":null,"eq":""},"properties":{}}],"input":false,"key":"page1","clearOnHide":false,"theme":"default","tableView":false,"hideLabel":false},{"type":"panel","title":"Page 2","components":[{"key":"page2Content","label":"Content","input":false,"tag":"h1","attrs":[{"value":"","attr":""}],"className":"","content":"Form X - page 2","type":"htmlelement","hideLabel":true,"tags":[],"conditional":{"show":"","when":null,"eq":""},"properties":{}}],"input":false,"key":"page2","clearOnHide":false,"theme":"default","tableView":false,"hideLabel":false}],"display":"wizard","submissionAccess":[{"roles":["5cab3f42ec9dd94d4f71f03d"],"type":"create_own"},{"roles":["5cab3f42ec9dd94d4f71f03d"],"type":"read_own"},{"roles":["5cab3f42ec9dd94d4f71f03d"],"type":"update_own"},{"roles":["5cab3f42ec9dd94d4f71f03d"],"type":"delete_own"}],"path":"eligibility-x","title":"Eligibility check X","name":"eligibilityCheckX","access":[{"roles":["5cab3f42ec9dd94d4f71f03c","5cab3f42ec9dd94d4f71f03d","5cab3f42ec9dd94d4f71f03e"],"type":"read_all"}],"created":"2019-04-08T12:38:39.162Z","modified":"2019-04-12T13:35:09.865Z","machineName":"eligibilityCheckX"}

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
