### ISSUE TITLE
Problem with prepopulated data via submission

### ISSUE THREAD

**Issue by kacperdev** [formio/angular#287]
Hi,

I'd like to pre-populate rendered form with some values. So I've added EventEmitter and binded it to [refresh] output. Then I've emitted some values as submission. It's working well. But when I want to edit any pre-populated data in form, old values are kept in (change) and (submit) event (change event is detected correctly but it doesn't have any affect on event.data). What's really strange is that when I edit data inside datagrid update is working fine. But adding new row to datagrid or updating textfields which are inside containers is not working at all.
Is there any solution to this problem?

I'm using angular-formio 3.11.6 and formiojs 3.20.0 with Angular 7.

Thanks for your help!

**Comment by travist** [comment]
It would be helpful to have a jsfiddle of this issue that you are experiencing so that we can take a look.

**Comment by kacperdev** [comment]
Sorry for bothering you. There was problem with additional dependencies and I accidentialy rendered form before emitting submission values which cause that strange behaviour.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
