### ISSUE TITLE
How can I use angular-formio with formio.js 4.x branch?

### ISSUE THREAD

**Issue by cristi-paraschiv** [formio/angular#293]
I'm trying to test the new rendering mechanism (https://github.com/formio/formio.js/tree/4.x/src/templates).
Is there an example on how to use angular-formio with formio.js 4.x?

**Comment by travist** [comment]
Not currently. We will need to create a 4.x branch of this angular-formio library which includes that new template system. This is on our list, but we are working to solidify that release before we bring it into the other frameworks.
