### ISSUE TITLE
angular version

### ISSUE THREAD

**Issue by charbelkh** [formio/angular#295]
hello , does this work with 
Angular CLI: 1.6.1
Node: 8.16.0
Angular: 4.3.6
?
i am trying to use i but keep getting a 'NativePromise.resolve is not a function' error from it

**Comment by wag110894** [comment]
Here is our list of package.json
https://github.com/formio/angular-formio/blob/master/package.json

Hope this helps.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
