### ISSUE TITLE
On form submission does not collect filled fields values from form`s subforms

### ISSUE THREAD

**Issue by ttomytiss** [formio/angular#299]
On latest several formio versions on form submission does not collect filled fields values from any form`s subforms at all.

P.S. Maybe same kind of problem: https://github.com/formio/formio.js/issues/504

**Comment by ttomytiss** [comment]
Found out that this functionality was changed in changelog:
3.19.3 Fixed Problem where the nested sub form was not sending the correct submission to load in subforms.

How to fix: Use correctly "Save as reference" parameter. As mentioned (https://help.form.io/userguide/form-components/):
Save as reference Check if you’d like to save only _id of child form submission instead of storing all child submission object inside of parent submission. This will also help all changes you’ve made in child submission be reflected in parent submission. If not checked, whole child submission object will be saved, and no any child submission changes would be reflected in parent submission.

Currently we are testing. If submission data will be not empty, we will close this task.

**Comment by randallknutson** [comment]
Okay. Let us know.

**Comment by franke-mc** [comment]
See also https://github.com/formio/angular-formio/issues/296#issuecomment-496939729

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
