### ISSUE TITLE
Formio renderer and builder style mess on Microsoft Edge browser

### ISSUE THREAD

**Issue by ttomytiss** [formio/angular#300]
Formio renderer and builder style mess on Microsoft Edge browser. This results that formio practically unusable on this browser.

**Comment by travist** [comment]
We just use Bootstrap so I am curious if you are including the styles correctly in your application.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
