### ISSUE TITLE
Select component when remove selected value with remove button (cross) shows text 'undefined'

### ISSUE THREAD

**Issue by ttomytiss** [formio/angular#301]
Select component when remove selected value with remove button (cross) shows text 'undefined'. Same problem exist on live demo: http://formio.github.io/formio.js/app/examples/select.html

P.S. This problem does not exist when add select component to panel, well, or other component. In this case it works correctly.

**Comment by jhen1422** [comment]
Hello,

Thank you for the report. This item is currently on our development backlog. We do offer services to expedite issues or enhancements. Please contact support@form.io if you are interested. Additionally, we would welcome community pull requests to fix this issue .

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
