### ISSUE TITLE
General Query : Integrating Stripe in angular-formio

### ISSUE THREAD

**Issue by A-Pradeep** [formio/angular#309]
Hi , i was checking out the payment method i.e. Stripe . So was checking any documents which help integrating the Stripe Checkout inside the formIO .  I found only [FormIO JS](http://formio.github.io/formio.js/app/examples/stripeCheckout.html). But  for that we have to manually give the JSON . 
I wanted to know how can i create a button for the payment and link with the stripe.

**Comment by travist** [comment]
You will need to use the same method as described @ https://formio.github.io/formio.js/app/examples/stripe.html

To get this to work with Angular formio, you will just need to pass in your "custom" renderer (formio.js) into the <formio> directive using the [renderer] property.

```
import { Form } from 'formiojs';
import { StripeComponent } from 'formiojs/build/contrib/stripe/stripe/stripe';
Formio.registerComponent('stripe', StripeComponent);

@Component({
  template: 'form.html'
})
export default class CustomTemplate {
   public renderer: any = Form;
}
```

```html
<formio [renderer]="renderer"></formio>
```

**Comment by A-Pradeep** [comment]
@travist  Hi , in the rendering side ( as shown in the [docs](http://formio.github.io/formio.js/app/examples/stripeCheckout.html)  , stripe checkout ) . I've created account in `stripe` and when i hit submit from the formio , in the stripe logs , there is no  amount property in the JSON ,  i don't know whether to configure the FormIO or in the Stripe side.

I'm using custom component for rendering the stripe component. 
The JSON is 
```
{
  "type": "stripeCheckout",
  "key": "card",
  "label": "Authorize payment",
  "stripe": {
    "apiKey": "pk_test_Aprek1cboUExxK6dHoBaOphh",
    "handlerConfiguration": {
      "image": "https://stripe.com/img/documentation/checkout/marketplace.png",
      "locale": "auto"
    },
    "popupConfiguration": {
      "name": "T-SHIRT",
      "description": "MEN IN BLACK",
      "currency": "USD",
      "amount": "{{data.calculatedValue}}"
    }
  },
  "protected": false,
  "persistent": true,
  "id": "egusb9t"
}
```

**As a side note , the `stripe_element`  is not working the the [FormIO link](http://formio.github.io/formio.js/app/examples/stripe.html)   , even i tried to render the stripe_element code  , but no use.

**Comment by travist** [comment]
Our stripe contrib plugin was developed by a third party. We may need some help maintaining it if you would like to make a pull request.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
