### ISSUE TITLE
Zoom in and out not working when viewing pdf in firefox

### ISSUE THREAD

**Issue by rubandangol** [formio/angular#313]
When displaying pdf, the zoom in and zoom out buttons don't do anything in firefox. It is however working fine in chrome and edge.

**Comment by wag110894** [comment]
Hello,
 
This item is an item in our backlog. We have tagged you on the ticket (FOR-972). We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.

**Comment by rubandangol** [comment]
I will wait for you guys to fix it. Thank you.

**Comment by rubandangol** [comment]
Just in case you guys aren't aware, this bug still exists.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
