### ISSUE TITLE
Loading button not stop when i call success or error

### ISSUE THREAD

**Issue by KP-story** [formio/angular#318]
i notify to formio submit success or error but loading button not stop.
my code bellow
```

export class FormioViewComponent implements OnInit {

  @Input() formDescription;
  @Input() submission:any;
   private fireSubmitSuccess: EventEmitter<String > = new EventEmitter();
   private fireSubmitFailed: EventEmitter<String > = new EventEmitter();

   @Output() submit :EventEmitter<any> = new EventEmitter();
  constructor() { }

  submitDone()
  {
 
     this.fireSubmitFailed.next("Thanh cong");
console.log("submit done");
  }
  ngOnInit() {

  }

}
```
`      <formio [success]="fireSubmitSuccess" [error]="fireSubmitFailed"[form]="formDescription" (submit)="submit.emit($event) ; submitDone();" [submission]="submission"></formio>
`

**Comment by travist** [comment]
This is a known issue that we are looking into.

**Comment by sabinayakc** [comment]
I am having the same issue but Im just using the default submit event. It says submission complete but the submit loading icon doesn't go away. In the component.ts file, i just have a `console.log` for `(submit)=onSubmit($event}`. 

![image](https://user-images.githubusercontent.com/13154166/65899922-63b78e80-e37a-11e9-846a-89674a3d332f.png)

**Comment by nprla3s** [comment]
@travist - Facing same issue. Any solution on this issue would be helpful!!

**Comment by VitorCoS** [comment]
Hi guys, we're facing this same issue almost 4 years later, do you have any update about this topic??????

**Comment by dinbtechit** [comment]
You should use `submitDone` directive to notify the formIO that the submission is done.

```html
<formio [form]="formIoObj"
                [submitDone]="submissionDone"      <<<-----<<<<
                [options]="formioOptions"
                (submit)="submit($event)" ></formio>
```

```ts
@Component(...)
export class PreviewComponent {

 @Output()
  submissionDone = new EventEmitter<Boolean>();

  async submit(formSubmission?: FormioSubmission) {
    console.log(object);
    // Submit to your backend
    this.submissionDone.emit(true). // Set to true to notify submission is complete.
  }
```


https://github.com/formio/angular/assets/17984781/768a0532-93ff-4931-bd95-22da85627430






P.S you should use the `error` directive when there are errors.

**Comment by lane-formio** [comment]
Thanks for the contribution @dinbtechit 
I'm going to go ahead and close this as resolved.

**Comment by avmesquita** [comment]
For me, at Angular 17, EventEmitter needs to be **any** as type. Boolean has crashed.

    @Output() submissionDone = new EventEmitter<any>();

**Comment by avmesquita** [comment]
> Thanks for the contribution @dinbtechit I'm going to go ahead and close this as resolved.

Please, update wiki at https://github.com/formio/angular/wiki/Form-Renderer with this parameter.

**Comment by Sidiro23** [comment]
A Ticket has been created for this feature request. FID-220
