### ISSUE TITLE
instance.off is not a function 

### ISSUE THREAD

**Issue by kingstarwu** [formio/angular#322]
When the angular6 project integrates angular-form@4.X, the front-end browser prompts an error message. How should this be solved? I looked at the underlying code of form.js@4.X and found that the method return information is different from 3.X. How should this solve the problem of version backward compatibility?

**Comment by kingstarwu** [comment]
<img width="1439" alt="2122" src="https://user-images.githubusercontent.com/18042649/60787347-187f4c80-a18c-11e9-9098-0cf736571f11.png">

**Comment by travist** [comment]
I will be upgrading this to use our latest 4.x version. We have made some fixes that I believe will resolve some of these problems.

**Comment by yjagspi** [comment]
Facing the same issue as @kingstarwu. Any hints on how to avoid this error? Thanks in advance..!

**Comment by travist** [comment]
Please try latest 4.x version that was pushed out this morning.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
