### ISSUE TITLE
Custom Action URL not sending forms payload in request

### ISSUE THREAD

**Issue by padhumailin** [formio/angular#323]
I need to handle form data submitted in my API. But when i test in preview with custom action url, forms payloads are net been sent in request. 

I just added Custom Action URL in setting.

do i missed  something to configure. pls help

**Comment by travist** [comment]
Please provide a JSFiddle showing the problem. That would help us determine the problem.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
