### ISSUE TITLE
Initial validation of form

### ISSUE THREAD

**Issue by julhen93** [formio/angular#324]
Hi,

i have a form in an angular app that contains requried fields and i need to see if the form is valid. When pre-populating some of the fields of the form, the isValid attribute from the change event is initialised with true, even though the required field is not set. Is there a way to update the validity or see whether the form is currently valid without submitting the form?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
