### ISSUE TITLE
hide a component in a registration form base on logged in user role pragmatically.

### ISSUE THREAD

**Issue by padhumailin** [formio/angular#326]
I have created multiple roles and registered some users with different roles like employee / manager etc..

I need to hide a component in a registration form base on logged in user role pragmatically.

trying to hide the empcode field in registration form, but not working.
any idea?

{provide: FormioResourceConfig, useValue: {
name: 'registration',
form: 'registration',

  parents: [
    'event',
    {
      field: 'user',
      resource: 'currentUser',
      filter: false
    },
    {
      **field: 'empcode',
      show: false,**
    }
  ]
}}

how i can achieve it.

**Comment by randallknutson** [comment]
In custom conditional you can access the user object and look up the roles with Formio.access. You should then be able to look up which role id you want to check and have access to user.roles to see if they have it. 
```
user.roles
Formio.access
```

We would like to come up with a better way be able to check this like adding a function where you could pass the role name and be able to check against a user.

**Comment by padhumailin** [comment]
Can we write Custom condition in angular 6 or using JavaScript sdk

**Comment by travist** [comment]
You would write this custom conditional using that section in the Conditonals tab of the builder

**Comment by padhumailin** [comment]
i tried below condition in Advanced condition (javascript) in builder, but not works. 
show = user.roles.indexOf('5d2db6bc8437b443b806a527') == -1

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
