### ISSUE TITLE
504 GATEWAY_TIMEOUT after authentication

### ISSUE THREAD

**Issue by padhumailin** [formio/angular#328]
504 GATEWAY_TIMEOUT occurs once authenticated from github. is this due to not using the commercial version of formio?

Also in another application getting "GitHub account has not yet been linked" in login page after authentication. i have added oAuth action to link current user.

After this i'm getting unauthorized error while submitting in https://ufcokdihgmydfrg.form.io/user/login/submission

**Comment by travist** [comment]
Yes, this is most likely that these actions are not enabled if you are not on commercial plan. It should work if your project is on Trial so please verify that you have at least a trial plan.

**Comment by padhumailin** [comment]
After successful authorize from github, still FormioAuthService authenticated value shows as false.
how to get the logged in user information and set authenticated as true?

https://github.com/login/oauth/authorize?response_type=code&client_id=b77a93a71dc718ea6ab9&redirect_uri=http%3A%2F%2Flocalhost%3A4210&state=ef25dae5ed6b9fbdf2f29d154ce81424d6d785e6e5fa9bf5cc7a086482819ee26bf758d9aaed35b1966b88b9bcee671df2d238128e216b66e5e522ee2535441d&scope=user%3Aemail

**Comment by padhumailin** [comment]
After successful authorize from github, still FormioAuthService authenticated value has false.
and shown unauthorized error for the call https://ufcokdihgmydfrg.form.io/user/login/submission.

https://github.com/login/oauth/authorize?response_type=code&client_id=b77a93a71dc718ea6ab9&redirect_uri=http%3A%2F%2Flocalhost%3A4210&state=ef25dae5ed6b9fbdf2f29d154ce81424d6d785e6e5fa9bf5cc7a086482819ee26bf758d9aaed35b1966b88b9bcee671df2d238128e216b66e5e522ee2535441d&scope=user%3Aemail

**Comment by travist** [comment]
In the response from the server, are you receiving an x-jwt-token header as a response with your token? If so, then this means that the auth was successful. If not, then I would be curious how your login form is configured since this may be a misconfiguration.

**Comment by padhumailin** [comment]
In forum launch im getting "You must assign this button to an oauth action before it will work" , please let me know what configuration i missed...

**Comment by randallknutson** [comment]
When you get the form definition with OAuth you have to add ?live=1 to the form url. This is because the OAuth action modifies the OAuth button to add the appropriate information but we only want to do this when live. We are discussing changing this since it causes lots of issues.

**Comment by padhumailin** [comment]
..
  providers: [
    FormioResourceService,
    {provide: FormioResourceConfig, useValue: {
      name: 'participant',

Im accessing forms with above code.. how i can append ?live=1 in this case.

**Comment by padhumailin** [comment]
> In the response from the server, are you receiving an x-jwt-token header as a response with your token? If so, then this means that the auth was successful. If not, then I would be curious how your login form is configured since this may be a misconfiguration.

the following payload is sent along with logon submission:
{"data":{},"oauth":{"github":{"code":"7f901849a1c476b21147","state":"4723db324bf2b2426339050798c8c690e1e7aa30d99ea8691bed9471662235dd990c083f10966e85b6deb85bf164e7e67dff0487d460c54d0e5856da9a930a9a","redirectURI":"http://localhost:4210"}}}

**Comment by travist** [comment]
Angular 6 is just a wrapper around our formio.js renderer so they all should be the same with this functionality. Not sure what is going on here, but if you need resolution to this very soon you will probably need to expedite this so our dev team can be allocated to dig into your configuration. Please contact support if you want to go down that route.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
