### ISSUE TITLE
How-to render 2 index on same page

### ISSUE THREAD

**Issue by beltschatsar** [formio/angular#336]
Hi,

I'm struggling with this problem for a while: How to render 2 index on the same page.

For example, I want to render all events (regardless of the participant) and all participants (regardless of the event) on the same page like this:

````html
<!-- event-participant/event-participant.component.html -->
<app-event-index></app-event-index>
<app-participant-index></app-participant-index>
````

And given the following files:

````typescript
// event-participant/event-participant-component.ts
//..
@Component({
  templateUrl: './event-participant.component.html',
})
export class EventParticipantComponent {
//...
}
````

````typescript
// event-participant.module.ts
//...
const childResourceRoutes: Routes =  [
  {
    path: '',
    component: EventParticipantComponent,
  }
];
@NgModule({
  imports: [
    CommonModule,
    FormioModule,
    RouterModule.forChild(childResourceRoutes),
    ParticipantModule,
    EventModule
  ],
  declarations: [
    EventParticipantComponent
  ],
  providers: [
  ]
})

export class EventParticipantModule { }
````

And given that:
- ParticipantModule is exporting a selector named `app-participant-index` (FormioResourceIndexComponent)
- EventModule is exporting a selector named `app-event-index` (FormioResourceIndexComponent)

event-participant.component.html seems to be ignored since it is the first imported module that show up. In the example provided, ParticipantModule's index is showed. If I place ParticipantModule in last position in import list, EventModule's index will show up instead.

Thanks for any help.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
