### ISSUE TITLE
validation error event

### ISSUE THREAD

**Issue by sureshece9999** [formio/angular#337]
Hi, I am using formio angular plugin for rendering form in my app. I want to handle or need to display popup when I get validation error. I referred formio angular document I found all event except error event.. Could  you please help me to solve / handle validation error event..

**Comment by aiwebb** [comment]
There's a `customValidation` hook you can set up when specifying form options. This will hook your function into the submission flow after normal validation, where you can perform any additional checks, raise an error, or in your case display a popup - just call `next()` when you're done, with an optional error argument if you'd like submission to fail with that error.

```js
hooks: {
  customValidation: function(submission, next) {
    // pass optional error message to next()
    next('Custom validation failure reason here');
  }
}
```

**Comment by sureshece9999** [comment]
Hi, I tried with hooks but I am not able to get any callback when I get validation error.. Is there any output event to catch any errors.. I added that snippet in options object.

![image](https://user-images.githubusercontent.com/48546522/61961008-4c5bce00-afe4-11e9-84ad-ba6589e5ecc3.png)

**Comment by aiwebb** [comment]
@sureshece9999 - you may want to add a `debugger` statement into your hook to confirm whether it's actually executing. It looks like part of the first image is cut off, so it's hard to tell.

**Comment by sureshece9999** [comment]
![image](https://user-images.githubusercontent.com/48546522/62102314-2ff6b480-b2b6-11e9-8077-c4accb90a77e.png)

I am using like this but even call not going inside hook and not printing anything in console...

**Comment by travist** [comment]
It should be ```[formioOptions]``` instead of ```[options]```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
