### ISSUE TITLE
[BUG] Radio button default value in survey component is not selected

### ISSUE THREAD

**Issue by xellafe** [formio/angular#338]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 1.48.2
- Formio.js version:
- Frontend framework: 4.0.0-beta.7
- Browser: Chrome
- Browser version: 75.0.3770.142 (x64)

## Steps to Reproduce
1. Create a survery form
2. Add some choices
3. Set default value
4. Render the form

## Expected behavior

Radio with default value should be selected

## Observed behavior

All radio buttons are empty

### Screenshot from Form.IO
![image](https://user-images.githubusercontent.com/33595243/62134562-fa1af580-b2e0-11e9-8d1b-d90dff270ed4.png)

### Screenshot from front-end app
![image](https://user-images.githubusercontent.com/33595243/62134484-de175400-b2e0-11e9-8c3d-92f8599db196.png)

**Comment by travist** [comment]
We will take a look.

**Comment by gopikrishna123** [comment]
@xellafe @travist  Is it Resolved?

**Comment by wag110894** [comment]
@gopikrishna123 @xellafe , can you try upgrading to version 4.9.5 of angular-formio and see if the issue still occurs?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
