### ISSUE TITLE
EditForm Dialog without style

### ISSUE THREAD

**Issue by felipebelluco** [formio/angular#348]
I don't use bootstrap in my application, because if I do it brokes many things. To manage that, I used the following to make the FormBuilder style works:

```
:host ::ng-deep {
  @import "~bootstrap/scss/bootstrap";
  @import "~formiojs/dist/formio.builder";
}
```

And it does work! But the EditForm dialog is appended to the body, so it doesn't get the bootstrap styles. Is there any way I can append the edit form inside my component instead of the body?

Thanks in advance for your help!

**Comment by aiwebb** [comment]
@felipebelluco, the WebformBuilder is calling Base.createModal() from here:

https://github.com/formio/formio.js/blob/3983c3b33c625a4cdad97848354a5ec36027f95c/src/WebformBuilder.js#L320

Base.createModal() is attaching the modal to the body here:

https://github.com/formio/formio.js/blob/3983c3b33c625a4cdad97848354a5ec36027f95c/src/components/base/Base.js#L698

You may want to override Base.createModal() to fire an event the modal is created - that way you can hook into the creation of that dialog and immediately move it as needed. Something like this:

```js
Base.prototype.createModal_original = Base.prototype.createModal;
Base.prototype.createModal = function(name) {
  let dialog = Base.prototype.createModal_original();

  document.dispatchEvent(new CustomEvent('modal-created', {name, dialog}));

  return dialog;
}
```

**Comment by felipebelluco** [comment]
@aiwebb I know I'm asking too much, but I'm new to this whole thing, where exactly should I add this code? I've tried inside OnInit method but it keeps show the following error:

```
ERROR TypeError: Cannot read property 'push' of undefined
    at Component.addEventListener (Component.js:205)
    at Component.createModal [as createModal_original] (Base.js:781)
    at WebformBuilder.Base.createModal (formio.component.ts:87)
    at WebformBuilder.editComponent (WebformBuilder.js:419)
    at WebformBuilder.onDrop (WebformBuilder.js:1070)
    at Object.<anonymous> (WebformBuilder.js:1140)
    at emitter (emitter.js:47)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (emitter.js:46)
    at Object.thing.emit (emitter.js:38)
defaultErrorLogger @ core.js:15724
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15772
next @ core.js:17771
schedulerFn @ core.js:13515
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:192
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:130
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:13499
(anonymous) @ core.js:17321
./node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
./node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:17258
onHandleError @ core.js:17321
./node_modules/zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:395
./node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:198
./node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
core.js:15724 ERROR TypeError: Failed to execute 'elementFromPoint' on 'Document': The provided double value is non-finite.
    at getElementBehindPoint (dragula.js:554)
    at release (dragula.js:242)
    at Object.destroy (dragula.js:85)
    at WebformBuilder.refreshDraggable (WebformBuilder.js:1126)
    at invokeFunc (lodash.js:10335)
    at trailingEdge (lodash.js:10384)
    at timerExpired (lodash.js:10372)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
```

**Comment by aiwebb** [comment]
@felipebelluco, here's an example JSFiddle:

https://jsfiddle.net/zqr9Ljsv/3/

**Comment by felipebelluco** [comment]
@aiwebb worked perfectly! Thank you very much! I have one more question; when using the `form-builder` component, is it possible to update the form programmatically? What is happening is that when I add a checkbox component programmatically, it seems to render fine, but when I add another component via builder, the edit form dialog shows but none of the dialog buttons work.

**Comment by travist** [comment]
@felipebelluco you need to call this method from the WebformBuilder instance to get it to stick.

https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L870

**Comment by MosabAbuzaid** [comment]
Hi all 
I have the same issue and want to salve it on your way but I can't understand where exactly you told the code where to append the dialog?

**Comment by MosabAbuzaid** [comment]
Hi @felipebelluco  how did you moved the dialog after catching the event because I used that same way but when I moved the dialog it's stopped working

**Comment by MosabAbuzaid** [comment]
Hi 
can anyone tell me what is the correct way to move the dialog because all of its event listeners are based on dialog appended  directly at the root of the body and when I moved it all events stop working like close and navigate between tabes

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
