### ISSUE TITLE
[BUG]  Google Maps API Key not loaded first time when using FormioResourceCreateComponent

### ISSUE THREAD

**Issue by bh-adrienne** [formio/angular#353]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 6.4.7
- Formio.js version:
- Frontend framework: Angular
- Browser: Issue reproduced in Chrome AND Firefox
- Browser version: n/a

## Steps to Reproduce
1.  Create an Angular component following wiki for CRUD options. Use FormioResourceCreateComponent as the route for create (when configuring FormioResourceRoutes setup in module) and the FormioResourceIndexComponent as the index. 
2.  Use a form.io form with the Google Maps API configured and the <formio> tag on the html for the custom FormioResourceCreateComponent. 
3. Navigate in browser to the index route. (example: /mycomponent). FormioResourceIndexComponent displays expected grid of options and link to create a new form. 
4. Click on "add" link. Browser navigates to /mycomponent/new and displays form.
## Expected behavior
Form should load and form elements configured to use Google Maps API key work on the first form load.

## Observed behavior
 On FIRST load, the form component with a Google maps API configured does NOT work or use the API key. HOWEVER, if you RELOAD the route using the browser refresh, OR paste the route DIRECTLY into a new browser tab (example: http://localhost:4200/mycomponent/new), then the API keys are loaded correctly. 

This leads me to believe there is possibly something wrong with the Angular route or link generated by  FormioResourceIndexComponent or some state somewhere that does not want to allow the Google Maps API to load within the application that is corrected by completely reloading the page.

**Comment by bh-adrienne** [comment]
Additional notes: I get this error while on the Index component: 
<img width="504" alt="image" src="https://user-images.githubusercontent.com/44947170/63975048-12b33280-ca7c-11e9-9146-80efc41e63f4.png">

which leads me to believe that the FormioResourceIndexComponent is trying to pre-load the form definition somehow and it isn't working?

**Comment by travist** [comment]
This is strange. So does this work outside of Angular? Like if you use a render with formio/formio.js renderer.

**Comment by bh-adrienne** [comment]
I have narrowed down this issue further and it looks like it's a sort of caching issue in the following scenarios in Formio.js + Angular-formio together (as it doesn't happen with just formio.js when I use that from the portal): 
1. Create a form with TWO Google maps address fields on it.  Add the API Key to JUST ONE OF THEM. 
2. Load this form as part of the angular-formio resource list page. 
3. You will see from the console that only 1 call out to Google Maps API key gets made, even though there are multiple Address Component items on the Form. 
4. If that call gets made for the component WITHOUT an api key, then BOTH component items will be broken, not just the (obviously broken) one without the key. 

This was VERY difficult to find, can the logic or an error message somewhere be changed to make this more obvious as a problem?

**Comment by bh-adrienne** [comment]
On the flip side, since I have now found the source of my team's issue, consider the above the suggested workaround- this is no longer blocking me and my team.

**Comment by travist** [comment]
We will add this as a bug in our backlog.

**Comment by wag110894** [comment]
Hello,

We welcome a pull request for this item to be resolved or we have a process to expedite this issue if you are interested. Please send an email to support@form.io if you would like the price to expedite this for you.
 
Thanks.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
