### ISSUE TITLE
Customize form builder in angular app

### ISSUE THREAD

**Issue by kkhanhluu** [formio/angular#355]
When user adding a new field, i want to show labels as a drop-down list, user can choose one of the items as the label. And i want to pre set the default value for description and tooltip box. How can i do that? Many thanks.
<img width="1080" alt="Screen Shot 2019-09-02 at 16 00 33" src="https://user-images.githubusercontent.com/38130967/64119876-2079f800-cd9b-11e9-8db6-d161557e4224.png">

**Comment by travist** [comment]
This can be done by modifying the ```[formioOptions]``` property with configs similar to what you see here https://formio.github.io/formio.js/app/examples/custombuilder.html

**Comment by kkhanhluu** [comment]
@travist thanks for you reply but i have not figured out what you recommended. Which components does [formioOptions] property belong to? Where and how can i configure it?

**Comment by buseodaci** [comment]
@kkhanhluu did you solve this ?

**Comment by msrmsr621** [comment]
@kkhanhluu did you solve it, please help me?

**Comment by msrmsr621** [comment]
> @travist thanks for you reply but i need to set label as a dropdown list and the values of description and toolbox corresponds to item, which user choose in the dropdown list.

did you solve it, please help me?

**Comment by lane-formio** [comment]
@msrmsr621  Since @kkhanhluu I'm going to encourage you to open a new issue.
