### ISSUE TITLE
 [BUG] Text area not loading ; quilljs are getting blocked

### ISSUE THREAD

**Issue by sreejithswamidas** [formio/angular#363]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 3.x
- Formio.js version:3.x
- Frontend framework: Angular
- Browser: Chrome
- Browser version: 60+

## Steps to Reproduce
1. If the text area is WYSIWYG Editor formio is calling quilljs api s to get the js and css files
2. In some of the networks those calls are getting blocked.
3. 

## Example
1. If the text area is WYSIWYG Editor formio is calling quilljs api s to get the js and css files
2. In some of the networks those calls are getting blocked.

**Comment by aiwebb** [comment]
@sreejithswamidas, can you confirm the full URLs of those requested files? e.g. `https://cdn.form.io/quill/1.3.6/quill.min.js`

**Comment by sreejithswamidas** [comment]
https://cdn.form.io/quill/1.3.6/quill.min.js
https://cdn.form.io/quill/1.3.6/quill.min.css

**Comment by randallknutson** [comment]
Are you using CSP or anything that could be blocking those urls? You can also include quill source code manually on the page and it will skip loading from those urls.

**Comment by sreejithswamidas** [comment]
@randallknuston
Where should I add these source files because these apis are getting called from angular-formio node module

**Comment by travist** [comment]
You can just import the Quill library into your application, and then use the following in your main module file.

```
import 'quill';
```

This should force your application to include the Global quill object which will skip the dynamic loading via URL.

**Comment by shahzadiiui2015** [comment]
How i can get access to the Quill editor from angular component?

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
