### ISSUE TITLE
formEditor javascript error after upgrading to 4.0.2 version

### ISSUE THREAD

**Issue by dolphinsd** [formio/angular#365]
FYI going back to 3.6.12 and issues disappear.

we see this error on Angular 8.
zone-evergreen.js:2828 GET http://localhost:4200/form?type=resource&limit=4294967295&select=_id%2Ctitle%2Cname%2Ccomponents 404 (Not Found)
scheduleTask @ zone-evergreen.js:2828
scheduleTask @ zone-evergreen.js:386
onScheduleTask @ zone-evergreen.js:273
scheduleTask @ zone-evergreen.js:379
scheduleTask @ zone-evergreen.js:211
scheduleMacroTask @ zone-evergreen.js:234
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1118
(anonymous) @ zone-evergreen.js:2861
proto.<computed> @ zone-evergreen.js:1433
(anonymous) @ fetch-browser.js:478
ZoneAwarePromise @ zone-evergreen.js:872
self.fetch @ fetch-browser.js:439
request @ Formio.js:932
(anonymous) @ Formio.js:863
invoke @ zone-evergreen.js:365
onInvoke @ core.js:39698
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:851
invokeTask @ zone-evergreen.js:400
onInvokeTask @ core.js:39679
invokeTask @ zone-evergreen.js:399
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:570
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:553
scheduleTask @ zone-evergreen.js:389
onScheduleTask @ zone-evergreen.js:273
scheduleTask @ zone-evergreen.js:379
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:841
then @ zone-evergreen.js:967
_updateValue @ forms.js:6774
ngOnChanges @ forms.js:6647
checkAndUpdateDirectiveInline @ core.js:31905
checkAndUpdateNodeInline @ core.js:44366
checkAndUpdateNode @ core.js:44305
debugCheckAndUpdateNode @ core.js:45327
debugCheckDirectivesFn @ core.js:45270
eval @ CreateOrEditFormComponent.html:32
debugUpdateDirectives @ core.js:45258
checkAndUpdateView @ core.js:44270
callViewAction @ core.js:44636
execComponentViewsAction @ core.js:44564
checkAndUpdateView @ core.js:44277
callViewAction @ core.js:44636
execEmbeddedViewsAction @ core.js:44593
checkAndUpdateView @ core.js:44271
callViewAction @ core.js:44636
execComponentViewsAction @ core.js:44564
checkAndUpdateView @ core.js:44277
callViewAction @ core.js:44636
execEmbeddedViewsAction @ core.js:44593
checkAndUpdateView @ core.js:44271
callViewAction @ core.js:44636
execComponentViewsAction @ core.js:44564
checkAndUpdateView @ core.js:44277
callViewAction @ core.js:44636
execEmbeddedViewsAction @ core.js:44593
checkAndUpdateView @ core.js:44271
callViewAction @ core.js:44636
execComponentViewsAction @ core.js:44564
checkAndUpdateView @ core.js:44277
callWithDebugContext @ core.js:45631
debugCheckAndUpdateView @ core.js:45193
detectChanges @ core.js:31125
tick @ core.js:41044
(anonymous) @ core.js:40892
invoke @ zone-evergreen.js:365
onInvoke @ core.js:39698
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:124
run @ core.js:39510
next @ core.js:40889
schedulerFn @ core.js:35335
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:35297
checkStable @ core.js:39641
onLeave @ core.js:39759
onInvoke @ core.js:39701
invoke @ zone-evergreen.js:364
runGuarded @ zone-evergreen.js:134
(anonymous) @ zone-evergreen.js:118
load (async)
set @ zone-evergreen.js:1372
(anonymous) @ service-proxies.ts:98007
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:21
subscribe @ Observable.js:23
subscribeToResult @ subscribeToResult.js:9
_innerSub @ mergeMap.js:59
_tryNext @ mergeMap.js:53
_next @ mergeMap.js:36
next @ Subscriber.js:49
_next @ filter.js:33
next @ Subscriber.js:49
notifyNext @ mergeMap.js:69
_next @ InnerSubscriber.js:11
next @ Subscriber.js:49
next @ Subject.js:39
(anonymous) @ abpHttpInterceptor.js:245
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
reader.onload @ abpHttpInterceptor.js:147
invoke @ zone-evergreen.js:365
onInvoke @ core.js:39698
invoke @ zone-evergreen.js:364
runGuarded @ zone-evergreen.js:134
(anonymous) @ zone-evergreen.js:118
load (async)
set @ zone-evergreen.js:1372
(anonymous) @ abpHttpInterceptor.js:146
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
push../node_modules/abp-ng2-module/dist/src/abpHttpInterceptor.js.AbpHttpInterceptor.handleSuccessResponse @ abpHttpInterceptor.js:240
(anonymous) @ abpHttpInterceptor.js:175
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
onLoad @ http.js:2453
invokeTask @ zone-evergreen.js:400
onInvokeTask @ core.js:39679
invokeTask @ zone-evergreen.js:399
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:481
invokeTask @ zone-evergreen.js:1596
globalZoneAwareCallback @ zone-evergreen.js:1633
load (async)
customScheduleGlobal @ zone-evergreen.js:1735
scheduleTask @ zone-evergreen.js:386
onScheduleTask @ zone-evergreen.js:273
scheduleTask @ zone-evergreen.js:379
scheduleTask @ zone-evergreen.js:211
scheduleEventTask @ zone-evergreen.js:237
(anonymous) @ zone-evergreen.js:1907
(anonymous) @ http.js:2558
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
push../node_modules/abp-ng2-module/dist/src/abpHttpInterceptor.js.AbpHttpInterceptor.intercept @ abpHttpInterceptor.js:174
handle @ http.js:1910
intercept @ angular-oauth2-oidc.js:3030
handle @ http.js:1910
intercept @ http.js:2207
handle @ http.js:1910
intercept @ http.js:2738
handle @ http.js:1910
handle @ http.js:2808
(anonymous) @ http.js:1637
_tryNext @ mergeMap.js:46
_next @ mergeMap.js:36
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:21
subscribe @ Observable.js:23
call @ filter.js:13
subscribe @ Observable.js:23
call @ mergeMap.js:21
subscribe @ Observable.js:23
call @ catchError.js:16
subscribe @ Observable.js:23
call @ finalize.js:11
subscribe @ Observable.js:23
show @ create-or-edit-form.component.ts:171
(anonymous) @ create-or-edit-form.component.ts:91
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
_subscribe @ BehaviorSubject.js:14
_trySubscribe @ Observable.js:42
_trySubscribe @ Subject.js:81
subscribe @ Observable.js:28
ngOnInit @ create-or-edit-form.component.ts:90
checkAndUpdateDirectiveInline @ core.js:31909
checkAndUpdateNodeInline @ core.js:44366
checkAndUpdateNode @ core.js:44305
debugCheckAndUpdateNode @ core.js:45327
debugCheckDirectivesFn @ core.js:45270
eval @ CreateOrEditFormComponent_Host.ngfactory.js? [sm]:1
debugUpdateDirectives @ core.js:45258
checkAndUpdateView @ core.js:44270
callViewAction @ core.js:44636
execEmbeddedViewsAction @ core.js:44593
checkAndUpdateView @ core.js:44271
callViewAction @ core.js:44636
execComponentViewsAction @ core.js:44564
checkAndUpdateView @ core.js:44277
callViewAction @ core.js:44636
execEmbeddedViewsAction @ core.js:44593
checkAndUpdateView @ core.js:44271
callViewAction @ core.js:44636
execComponentViewsAction @ core.js:44564
checkAndUpdateView @ core.js:44277
callViewAction @ core.js:44636
execEmbeddedViewsAction @ core.js:44593
checkAndUpdateView @ core.js:44271
callViewAction @ core.js:44636
execComponentViewsAction @ core.js:44564
checkAndUpdateView @ core.js:44277
callWithDebugContext @ core.js:45631
debugCheckAndUpdateView @ core.js:45193
detectChanges @ core.js:31125
tick @ core.js:41044
(anonymous) @ core.js:40892
invoke @ zone-evergreen.js:365
onInvoke @ core.js:39698
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:124
run @ core.js:39510
next @ core.js:40889
schedulerFn @ core.js:35335
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:35297
checkStable @ core.js:39641
onHasTask @ core.js:39718
hasTask @ zone-evergreen.js:420
_updateTaskCount @ zone-evergreen.js:441
_updateTaskCount @ zone-evergreen.js:264
runTask @ zone-evergreen.js:185
drainMicroTaskQueue @ zone-evergreen.js:570
invokeTask @ zone-evergreen.js:485
invokeTask @ zone-evergreen.js:1596
globalZoneAwareCallback @ zone-evergreen.js:1622
Show 158 more frames
core.js:6014 ERROR Error: Uncaught (in promise): <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /form</pre>
</body>
</html>

    at resolvePromise (zone-evergreen.js:793)
    at resolvePromise (zone-evergreen.js:752)
    at zone-evergreen.js:854
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:39679)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:570)

**Comment by dolphinsd** [comment]
@travist version 4.2.2 still has error, any idea why it tries to load form, from appurl even so we use template
![image](https://user-images.githubusercontent.com/3460517/65986969-cc197500-e439-11e9-92f2-22f64012db7e.png)

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
