### ISSUE TITLE
[BUG] Address field with Google Api Key doesn't work on modal

### ISSUE THREAD

**Issue by kamel-msaoubi** [formio/angular#378]
## Environment
Please provide as many details as you can:
I have a resource named 'A' with a component of type Address with a Google Api Key. It works well, I have the autocompletion.
But I have also an another form named 'B' with a Select component with Data Source Type as 'Resource' pluged to resource 'A' and the field 'Add resource' checked.
Adding a file for my form 'B', when I click on 'Add resource', I have a modal with the components of my resource 'A'. Everything works well but the component of type Address doesn't work.
- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.X.X
- Frontend framework: Ionic
- Browser: Chrome
- Browser version: latest

## Steps to Reproduce
1. Having two forms : 'A' with a component of type address and google api key and another form 'B' with a Select component, data source type 'Resource' plugged to the form 'A' and 'Add resource' checked.
2. Create a new file for my form 'B', click on 'Add resource', fill in the form 'A' displayed in the modal, the field Address doesn't work

## Expected behavior
Field Address working on modal, with autocompletion
## Observed behavior
Field Address doesn't autocomplete on modal

**Comment by wag110894** [comment]
Thanks for reaching out!

We are aware of this issue and have tagged you on the ticket (T4X-409).

We will let you know once this issue with the Address Field not working when the Google API is included.

Thanks,

**Comment by bh-adrienne** [comment]
Can I also get tagged on this ticket?

**Comment by wag110894** [comment]
You have been tagged.

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
