### ISSUE TITLE
Checkmatrix items can be checked in view mode

### ISSUE THREAD

**Issue by dmenne** [formio/angular#380]
Items in CheckMatrix can be edited (checked/unchecked) in view mode

**Comment by wag110894** [comment]
We are able to replicate this issue using our 3x Core Renderer. We will fix this inside our 4x Core Renderer. We will let you know once this resolved.

Thanks.

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
