### ISSUE TITLE
How to set permission update all to form definitions as default

### ISSUE THREAD

**Issue by Yobikap** [formio/angular#393]
Hi Travist,

In formmanager I have created a form definition, that I can update.
Now I also want someone that has the role authenticated, to update the form definition that I have initially created.

How can I fix the permission so that this authenticated person can also update all my form definitions on default, without me setting permission in the form.io devportal on each form?

I have used this document, but cannot find my answer.
https://help.form.io/userguide/roles-and-permissions/#submissionpermissions

This are our project settings
![Screenshot 2019-10-30 at 11 48 33](https://user-images.githubusercontent.com/2850919/67851852-997f9c80-fb0b-11e9-92fb-78f622720859.png)

I hope you can guide me how to set the permission on all the form definitions.

**Comment by travist** [comment]
Setting default permissions for all new forms is currently not supported. We will add this as a feature request to our backlog.

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
