### ISSUE TITLE
Form builder  bad rendering

### ISSUE THREAD

**Issue by fzucaro** [formio/angular#401]
I insert tag form/builder in angular application, but the presentation is not correct, I insert the css in style.scss file  **@import "~bootswatch/dist/cosmo/_variables.scss";
@import "~bootstrap/scss/bootstrap.scss";
@import "~bootswatch/dist/cosmo/_bootswatch.scss";
$fa-font-path: '../node_modules/font-awesome/fonts';
@import '~font-awesome/scss/font-awesome';**   

![form-builder](https://user-images.githubusercontent.com/10828465/68501857-6d78bf80-025f-11ea-868c-8d300a298ce9.png)

but the result dosn't change.

**Comment by travist** [comment]
This is probably because you have other styles that are conflicting with the standard Bootstrap styles provided by these libs. Does it look like this when you remove all other custom styles?

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
