### ISSUE TITLE
Feature request: Radio buttons for mobile/tablet

### ISSUE THREAD

**Issue by dmenne** [formio/angular#403]
Default radio buttons are not very useful in mobile/table apps, because they are too small and the selection is not clearly visible. I generally use a solution based on [bootstrap buttons](https://stackblitz.com/edit/angular-vnng3e?file=app%2Fbuttons-radio.html) .

I have tried to create a custom component following the CheckMatrix example, but was no very successful.

**Comment by wag110894** [comment]
Thanks for reaching out! Our developers have discussed this and estimate that this would take 8 hours of development time to add this feature. Please contact support@form.io if you are interested. 

Thanks.

**Comment by dmenne** [comment]
Partially: https://github.com/dmenne/custom-radio

Still has rough sides, but as long as the basic bug in all Custom Components has not been resolved I won't put more work into it.

**Comment by travist** [comment]
Here is how we create custom components (using vanilla js) which also works in Angular. It maybe the case that you could port your work into this method which should solve the onInit issue you described in your other issues.

https://github.com/formio/contrib

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
