### ISSUE TITLE
[Question] Is there any way to extend a component in an angular project?

### ISSUE THREAD

**Issue by jerocon** [formio/angular#416]
Hi, 

Is there any way to extend a component, for example DataGrid, in an angular project?

The idea is to be able to add a new button to import a csv file with which to load a DataGrid.

**Comment by travist** [comment]
You can take a look at the angular-material-formio project. It does this quite a bit...

https://github.com/formio/angular-material-formio

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
