### ISSUE TITLE
[BUG] unable to customize select component (searchResultLimit)

### ISSUE THREAD

**Issue by beltschatsar** [formio/angular#418]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: latest
- Frontend framework: angular-demo
- Browser:Google Chrome 
- Browser version: 62.0.3202.62 

## Steps to Reproduce
1. clone angular-demo
2. have resource with a component type 'select' based on a resource which has more than 4 results which begin with a given letter (example: 'a1', 'a2', 'a3', 'a4', 'a5', ...)
3. In \<resource\>-create.html, have a formio element using renderOptions like the following: 
```html
<formio
  [form]="service.form"
  [submission]="service.resource"
  [refresh]="service.refresh"
  (submit)="onSubmit($event)"
  [renderOptions]='{
  "components": {
    "select": {
      "customOptions": {
        "searchResultLimit": 10
      }
    }
  }
}'
></formio>
```

## Expected behavior
When typing a letter (example: 'a')  in select component, I expect to see more than 4 result (example: 'a1', 'a2', 'a3', 'a4', 'a5', ...)

## Observed behavior
Only the first 4th are showed, no scrollbar is available to see others matching result 

## Example
see above

**Comment by jhen1422** [comment]
@beltschatsar 
Is the search result limit working outside of Angular wrapper?

**Comment by beltschatsar** [comment]
If I provide a full json instead of service.form for form attribute, and not provide submission attribute, select component would work as expected. 

As a workaround, I did a class extending Select (inspired from the checkMatrix example) which has the correct setting in schema and did a setComponent to replace the builtin select component type and have the expected behaviour.

**Comment by travist** [comment]
If you make a pull request to the "formio/formio.js" with your change, I am sure we will accept it and you will no longer need to extend the select component.

**Comment by bandman0226** [comment]
I too am seeing the same thing.
formiojs: 4.8.1
angular-formio: 4.5.1

I would be interested in seeing more on this workaround that @beltschatsar has in place.

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
