### ISSUE TITLE
[BUG] SubmissionGridHeaderComponent bug means nested data is never displayed in formio-grid

### ISSUE THREAD

**Issue by bh-adrienne** [formio/angular#431]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: latest
- Frontend framework: Angular
- Browser: Firefox 
- Browser version:

## Steps to Reproduce
1. The SubmissionGridHeaderComponent does NOT produce valid key for nested data. Observe that the 'key' value created for the header is hard coded here on line 54 and does not take nested data values into account: 
https://github.com/formio/angular-formio/blob/483e114794a9e405806eea20d2e36729fda67724/src/grid/submission/SubmissionGridHeader.component.js

## Expected behavior
'key' value here ought to be key used to access data in a response, which means it should support nesting. This works in Form.io on the website in the non-Angular version, but not in the Angular code.  For example, it is completely valid with Form.io's postman API to retrieve a field located inside an edit grid. The following URL format will return nested data: 

`http://lvh.me/projectname/application/submission?limit=10&select=data.hcp_full_name%2Cdata.my_editgrid.my_editgrid_nested_field
`
Example data returned: 

```js
{ "_id": "5de6e95c7afc225e3c2a1fcc",
        "data": {
            "my_editgrid": [
                {
                    "my_editgrid_nested_field": "2021-09-30T00:00:00-04:00"
                }
           ]
       }
}
```
 In the Form.io default view of table data, data values like the one above will actually be displayed properly as well.  In the Angular version, the data is not, because the key is wrong. 
The key for the above example SHOULD be: 'data.my_editgrid.my_editgrid_nested_field'. 

## Observed behavior
Hard coded key means no nested data is ever displayable in component formio-grid.
Again, using the above example, what gets returned is just 'data.my_editgrid_nested_field', which doesn't exist.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
