### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by praveenmadishetty** [formio/angular#450]
## Environment
In my application, requirement is to connect the pages on button click action. I have created 2 to 3 pages, and i have to navigate from one page to another page on button click. How can we achieve that?

//this is the code i have tried
At first i created a class
import ButtonComponent from 'formiojs/components/button/Button.js';

export class FormioButtonComponent extends ButtonComponent {
constructor(component, options, data) {
        super(component, options, data);
 }
 build() {
        super.build();
        this.addEventListener(this.buttonElement, 'click', (event: any) => {
            console.log('event', event);
           //Here i am trying to extend click functionality with my custom logic
            router.navigatebyURL(page);
        }
 }
}
![querysnippet](https://user-images.githubusercontent.com/42296326/72778037-ad83f780-3c3d-11ea-97f6-e58a97d7b8f5.PNG)

so that i could be able to pass the page name for navigating.

Regards in Advance

**Comment by travist** [comment]
I believe what you are looking to do is described in this page...

https://formio.github.io/formio.js/app/examples/customwizard.html

**Comment by praveenmadishetty** [comment]
Hi @travist , Thanks for responding. but i am not looking for 
https://formio.github.io/formio.js/app/examples/customwizard.html

I am looking to add an option (ie., a TEXTBOX) in the existing formio default button configuration modal as shown in above screenshot.

i am resharing the screenshot please check it
![querysnippet](https://user-images.githubusercontent.com/42296326/72870525-70d40100-3d0e-11ea-940b-23ac09ada4cc.PNG)

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
