### ISSUE TITLE
[HELP] Override template in component using JS

### ISSUE THREAD

**Issue by samswbk** [formio/angular#462]
I'm using a custom form builder with JS example(no angular), how to override the template of a custom component(inputcamera).

`formBuilder = new Formio.FormBuilder(document.getElementById("builder"), form, {
        builder: {
basic: false,
customBasic: {
        title: 'Basic',
        default: true,
        weight: 0,
        components: {
            inputcamera: {
                title: 'Camera',
                schema: {
                    label: 'Camera',
                    type: 'file',
                    key: 'inputcamera',
                    image: true
                }
            }
        }
    },
        editForm: editForm
    });`

**Comment by samswbk** [comment]
any help?

**Comment by travist** [comment]
Does this documentation help? https://github.com/formio/formio.js/wiki/Templates-API

**Comment by samswbk** [comment]
@travist not much, im using JS API not angular.

i define the custom component:
`inputcamera: { title: 'Camera', schema: { label: 'Camera', type: 'file', key: 'inputcamera', image: true }`

and put the code below before builder instance (new Formio.FormBuilder(...))
`Formio.Templates.setTemplate('file-inputcamera', {
        form: '<i class="fa fa-camera"></i> Use Camera'
    });`

**Comment by samswbk** [comment]
@travist if i use this way:

`Formio.Templates.current = {
        file: {
            form: templateCamera
        }
    };`

the template apply on file component, but if i use this:
`Formio.Templates.setTemplate('file', { form: templateCamera });`

doesn't apply, another stuff is, i only want the template in my custom, in the case 'inputcamera', i check the TemplateAPI and try:
``${templateName}-${component.type}-${component.key}`,`

but unsuccessful since I can't apply using 'Formio,setTemplate':
`Formio.Templates.setTemplate('file-inputcamera', { form: templateCamera });`

**Comment by samswbk** [comment]
Any tips?

**Comment by travist** [comment]
This would require you to debug through the code to determine what is different from setTemplate vs current = ....  I do not know off the top of my head.
