### ISSUE TITLE
UX and UI design change

### ISSUE THREAD

**Issue by Dheeraj-Bharti** [formio/angular#467]
Hi, 
I wanted to customize displaying configuration of formio components popup to another way in my application. I don't want the pop up to come out after dragging the component, i want to show the configuration on the right side of the page. Can we do that? If yes, Please tell me how, if no is there any work around in the source code that we can do?

Please respond ASAP.

**Comment by travist** [comment]
The way I would do this is to override the ```createModal``` method for the WebformBuilder class. Something like this...

```js
builder.createModal = function(element, options) {
  // Do your logic here.
};
```

**Comment by Dheeraj-Bharti** [comment]
It's not working in the latest version of angular-formio. Can you give an example  how to do it in the typescript. I've imported the base and tried to override the createModal() function that is working in 3.27.x version but not in the 4.x version. Please provide the complete reference.

Thank you.!

**Comment by travist** [comment]
I would create a ```ViewChild``` reference in your template to point to the ```formio-buillder```, which will give you a reference to the FormBuilderComponent class. From here, you can get the builder instance like this.

```
@ViewChild(FormBuilderComponent) builder;

ngAfterViewInit() {
  this.builder.ready.then((builder) => {
    builder.createModal = function(element, options) {
      // Do your logic here.
    };
  });
}
```

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
