### ISSUE TITLE
[INFO]

### ISSUE THREAD

**Issue by fzucaro** [formio/angular#475]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version: 
- Formio.js version: 4.4.4
- Frontend framework: Angular
- Browser: Chrome
- Browser version: e 80.0.3987.122 (

## Steps to Reproduce
1. I don't submit to formio, i have (submit) event in wich i manage the submission. If i have an error in the procedure, the front-end shows the message "Submission complete". How can i modify this behavior
 This is my procedure
``
 onSubmit(submission: any) {

    let codiceStato: number;
    /*
    proprietà state contiene info su operazione
    draft: ho premiuto save
    submitted: ho premuto submitted
     */
    this.data = submission['data'];
    if (submission['state'] === StatiForm.codiceStatoDRAFTFormio) {
      codiceStato = StatiForm.codiceStatoBOZZA;
    }
    if (submission['state'] === StatiForm.codiceStatoSUBMITTEDFormio) {
      codiceStato = StatiForm.codiceStatoINVIATO;
    }

      try {
       
        if (Costanti.TIPO_STRUTTURA_WIZARD.localeCompare(this.tipoStruttura) === 0) {
          this.currentStep = this.formio.formio.page;
        }
          console.log('SUBMISSION ' + JSON.stringify(submission.data) + '**********');
         // this is the post data
          this.sottomettiForm({"data": submission.data}, this.idModulo, this.idIstanza, codiceStato, this.currentStep);

      } catch (e) {
       this.msgErr = "Errore preparazione dati, istanza non salvata";

     }
  }
``

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
