### ISSUE TITLE
Extending PDFBuilder 

### ISSUE THREAD

**Issue by sourav0491** [formio/angular#480]
What is the way of extending the PDFBuilder and customize it ? I was able to extend the formBuilder but not able to do the same with PDFBuilder. I am guessing it is not exposed as a module. Please let me know what should the appropriate way to do that when using it in an angular based front end project.

**Comment by merobal** [comment]
Have you checked https://github.com/formio/angular-formio/issues/473 ?

**Comment by sourav0491** [comment]
Yes. The thing I am looking for is to customize the default behavior of PDFbuilder when using it through angular-formio library. The #473 is about making custom components when using PDF builder. Thus, I think #473 is different than #480.

**Comment by merobal** [comment]
Then maybe @travist can help

**Comment by travist** [comment]
I am looking at the core code now, and it looks like we are not exporting the ```Builders``` construct @ https://github.com/formio/formio.js/blob/master/src/FormBuilder.js#L2.  We need to make a change to export this.  Then you would be able to do the following.

```
import { Formio } from 'angular-formio';
const PDFBuilder = Formio.Builders.getBuilder('pdf');

class MyPDFBuilder extends PDFBuilder {

}

Formio.Builders.addBuilder('pdf', MyPDFBuilder);
```

We will add a task for us to export this so this can be done, but right now, we cannot extend the PDF builder from an application.

**Comment by sourav0491** [comment]
When can I expect this change to be published?

**Comment by travist** [comment]
I just looked and it does seem like the Builders construct is exported. Give the above a try and let me know if it works for you.

**Comment by sbatabyal** [comment]
Hi @travist. We updated to the latest version (4.6.1) of angular-formio, and tried the snippet that you shared. But looks like "Builders" is still not exposed under Formio:

![image](https://user-images.githubusercontent.com/20504422/75996547-0248ac80-5f24-11ea-9aa9-d2b8d68ece87.png)

**Comment by travist** [comment]
This is probably that they are not exposed with the type definitions. What happens when you do the following?

```js
(Formio as any).Builders.addBuilder('pdf', MyPDFBuilder);
```

**Comment by sourav0491** [comment]
Tried the same as mentioned above. Still not able to access the builders.The screenshot of error stack is given below -
![image](https://user-images.githubusercontent.com/21309001/76410129-72887f80-63b5-11ea-9900-528740455a76.png)

The code snippet is also given below -
![image](https://user-images.githubusercontent.com/21309001/76410407-e034ab80-63b5-11ea-841f-215aaafc6524.png)

**Comment by travist** [comment]
We will add this to our backlog to to get added to the exports.

**Comment by max-in-to** [comment]
Has there been any updates on this recently?

**Comment by wag110894** [comment]
Hello @max-in-to can you try using the latest version of angular-formio and see if the issue has been resolved? The newest stable version of Angular-formio is 4.11.0.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
