### ISSUE TITLE
[BUG] Custom component made with vanilla js not being registered to angular application

### ISSUE THREAD

**Issue by arvyy** [formio/angular#482]
(I saw there is a separate report for custom components, but as far as I understand it's meant for issues regarding creating custom components with angular, not the old way with vanilla js)

## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 1.70.0
- Formio.js version: 4.8.0-rc.12
- Frontend framework: angular-formio ^4.4.3
- Browser: Chrome
- Browser version: 80.0.3987.122

## Steps to Reproduce
1. Clone & run https://github.com/formio/angular-app-starterkit
2. Click forms -> create form -> expand basic tab

## Expected behavior
basic tab contains "Check Matrix" custom component, defined in https://github.com/formio/angular-app-starterkit/blob/master/src/app/components/CheckMatrix.js

## Observed behavior
"Check Matrix" custom component is missing

Custom components were working fine with previous versions (server version 1.46; formio.js version ^3.20.9; angular-formio version ^3.16.0), however after upgrading to new major versions (and refactoring the class they extend), custom component registration doesn't work anymore.

**Comment by travist** [comment]
You need to import Formio from angular-formio and not formiojs to register the component.  i.e.

```js
import { Formio } from 'angular-formio';

.....

Formio.registerComponent();
```

**Comment by arvyy** [comment]
Thanks for fast response. Unfortunately this doesn't seem to help (testing this on the angular-app-starterkit project)

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
