### ISSUE TITLE
[Bug] Set language in render

### ISSUE THREAD

**Issue by fzucaro** [formio/angular#496]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [x ] Local deployment
    - Version:  
- Formio.js version: 4.4.4
- Frontend framework:  Angular  8.2.13
- Browser: Chrome
- Browser version:  80.0.3987.132 

## Steps to Reproduce
 I would set language for render form. I set language in renderOptions:
[renderOptions]="{....  language: 'it'}"
I set object translated in FormioOptions by code: 
this.options = {
        alerts: {'submitMessage': this.alertMessage},
        errors: {'message': Messaggi.msgErrForm},
        i18n: {language: 'it',
          it: {
            complete: 'Invio completato',
            error: 'Si prega di correggere gli errori prima di inviare.',
            required: '{{field}} è obbligatorio',
            unique: '{{field}} deve essere unico',
            array: '{{field}} deve essere un elenco',
            array_nonempty: '{{field}} deve ...
             .... field translated

## Expected behavior
I Expected  translated fileds
## Observed behavior
If the form is displayed as wizard i see translated fields, but if displayed as Form i see  default label     
## Example
Submit button with label  "Submit" instead of  translated label "Invia Form". In wizard label is showed correctly.

**Comment by travist** [comment]
Is it possible to provide a live example of this issue... Maybe using JSFiddle or something similar for Angular.

**Comment by fzucaro** [comment]
Sorry i don't know how use this tools, if could help i can get the code..however the problem is than the translation doesn't work for form that are displayed as FORM and not WIZARD

**Comment by travist** [comment]
If we don't have a live example showing this, then this issue will have a hard time making its way to the top of my developers list to investigate. Maybe someone from the community is also experiencing this problem?...

**Comment by fzucaro** [comment]
If could help i put in this  [jsFiddle](https://jsfiddle.net/fzucaro/90zf8ab7/8/ ) code in which i define options with ttranslate

**Comment by travist** [comment]
The fiddle isn't running, so it helps a little, but we will still not be able to assign this to a developer on our end without a reproducible case. Otherwise we are tasked with creating an application that reproduces the issue.

**Comment by fzucaro** [comment]
Thanks, but if you need my help to prepare application please contact me if do you deem it appropriate.
