### ISSUE TITLE
I have Upgraded the Project from Angular 7 to Angular 9, error TS2307: Cannot find module 'formiojs/components/base/Base'.

### ISSUE THREAD

**Issue by Abhilashtiwari0301** [formio/angular#508]
Hi Everyone,

I am facing the Problem after upgrading the Project from Angular 7 to Angular 9. the same thing is worked in Angular 7,
Please Help,

Below is the error
error TS2307: Cannot find module 'formiojs/components/base/Base'.
error TS2307: Cannot find module 'formiojs/components/Validator.js'.
error TS2339: Property 'registerComponent' does not exist on type 'typeof Formio'.

I am register the component in the constructor of the class and it's work in Angular 7, see code below,

Formio.registerComponent('accordion', AccordionComponent); -- this line giving me error

constructor(private formUtils: AbstractChartMeasureFormService,
		private authService: AuthService,
		private abstractChartService: AbstractChartService) {
		Formio.registerComponent('accordion', AccordionComponent);
		this.checkValidity();
		this.hideShowBlockDeleteBtns();
		this.addButton();

}

Package.json

"dependencies": {
    "@angular/animations": "~9.0.7",
    "@angular/cdk": "~9.1.3",
    "@angular/common": "~9.0.7",
    "@angular/compiler": "~9.0.7",
    "@angular/core": "~9.0.7",
    "@angular/elements": "^9.0.7",
    "@angular/forms": "~9.0.7",
    "@angular/localize": "^9.0.7",
    "@angular/platform-browser": "~9.0.7",
    "@angular/platform-browser-dynamic": "~9.0.7",
    "@angular/router": "~9.0.7",
    "@fullcalendar/core": "^4.4.0",
    "@ng-bootstrap/ng-bootstrap": "^6.0.0",
    "@ng-idle/core": "^8.0.0-beta.4",
    "@swimlane/ngx-charts": "^13.0.2",
    "@types/jquery": "^3.3.33",
    "angular-formio": "^3.12.0",
    "babel-polyfill": "^6.26.0",
    "bootstrap": "4.4.1",
    "chart.js": "^2.9.3",
    "core-js": "^2.5.4",
    "date.js": "^0.3.3",
    "flatpickr": "4.6.3",
    "font-awesome": "^4.7.0",
    "formiojs": "^4.8.0-rc.12",
    "jquery": "^3.2.1",
    "karma": "^4.4.1",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "oidc-client": "^1.6.1",
    "popper.js": "^1.16.1",
    "primeicons": "^2.0.0",
    "primeng": "^9.0.1",
    "quill": "^1.3.7",
    "rxjs": "^6.3.3",
    "rxjs-compat": "6.3.3",
    "tslib": "^1.9.0",
    "xml-js": "^1.6.11",
    "zone.js"

Please help

**Comment by travist** [comment]
This is because your previous version was based on 3.x, and the new versions are now based on 4.x which is a big change. You will need to migrate any custom components, etc to 4.x renderer to get everything working the way you need them to work.

**Comment by merobal** [comment]
Instead of `Formio.registerComponent` try
```
import { Components } from 'angular-formio';

Components.setComponent('separator', SeparatorComponent);
```

**Comment by Abhilashtiwari0301** [comment]
hi @merobal , @travist 

import { Components } from 'angular-formio'; is working fine,

but how to resolve the below Error.

error TS2307: Cannot find module 'formiojs/components/base/Base'.
error TS2307: Cannot find module 'formiojs/components/Validator.js'.

Updated Package.json



 "dependencies": {
    "@angular/animations": "~9.0.7",
    "@angular/cdk": "~9.1.3",
    "@angular/common": "~9.0.7",
    "@angular/compiler": "~9.0.7",
    "@angular/core": "~9.0.7",
    "@angular/elements": "^9.0.7",
    "@angular/forms": "~9.0.7",
    "@angular/localize": "^9.0.7",
    "@angular/platform-browser": "~9.0.7",
    "@angular/platform-browser-dynamic": "~9.0.7",
    "@angular/router": "~9.0.7",
    "@fullcalendar/core": "^4.4.0",
    "@ng-bootstrap/ng-bootstrap": "^6.0.0",
    "@ng-idle/core": "^8.0.0-beta.4",
    "@swimlane/ngx-charts": "^13.0.2",
    "@types/jquery": "^3.3.33",
    "angular-formio": "^4.6.1",
    "babel-polyfill": "^6.26.0",
    "bootstrap": "4.4.1",
    "chart.js": "^2.9.3",
    "core-js": "^2.5.4",
    "date.js": "^0.3.3",
    "flatpickr": "4.6.3",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "karma": "^4.4.1",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "oidc-client": "^1.6.1",
    "popper.js": "^1.16.1",
    "primeicons": "^2.0.0",
    "primeng": "^9.0.1",
    "quill": "^1.3.7",
    "rxjs": "^6.3.3",
    "rxjs-compat": "6.3.3",
    "tslib": "^1.9.0",
    "xml-js": "^1.6.11",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.7",
    "@angular/cli": "~9.0.7",
    "@angular/compiler-cli": "~9.0.7",
    "@angular/language-service": "~9.0.7",
    "@types/jasmine": "^3.0.0",
    "@types/jasminewd2": "^2.0.0",
    "@types/node": "^8.10.59",
    "codelyzer": "^5.1.2",
    "jasmine-core": "^3.0.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.0.0",
    "karma-chrome-launcher": "^3.0.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-html-reporter": "^0.2.7",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-junit-reporter": "^1.2.0",
    "node-sass": "^4.13.1",
    "protractor": "^5.4.3",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.0",
    "typescript": "^3.7.2"
  }

**Comment by Abhilashtiwari0301** [comment]
Thanks @merobal, Thanks @travist

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
