### ISSUE TITLE
[Question] how i can allow unsafe HTML in the html component

### ISSUE THREAD

**Issue by HenriqueVilela** [formio/angular#510]
I need to let the html component execute scripts. but i notice that the formio removes my script tags and other unsafe tags like iframe dont work.

**Comment by travist** [comment]
Obviously this is on purpose, but it can be overridden with options that get passed to the sanitize methods.  Here is the code that shows them.

https://github.com/formio/formio.js/blob/master/src/utils/utils.js#L1046

These options are passed to the DOMPurify library found @ https://github.com/cure53/DOMPurify#can-i-configure-dompurify.  They can be passed to the Form.io renderer within Angular like this.

```
<formio [rendererOptions]="{
  sanitizeConfig: {
    addTags: ['iframe']
  }
}"></formio>
```

**Comment by OleksandrPoshtaruk1533** [comment]
after check on source code 
[here](https://github.com/formio/angular/blob/master/projects/angular-formio/src/custom-component/register-custom-component.ts#L8C17-L8C34) and [here](https://github.com/formio/angular/blob/master/projects/angular-formio/src/FormioBaseComponent.ts#L102)
I could make renderer to display custom component tags
Just in ngOnInit of parent component 

registerCustomTag('custom-tag', this.injector);

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
