### ISSUE TITLE
[Custom Components] Add new property to formbuilder display

### ISSUE THREAD

**Issue by naonvl** [formio/angular#516]
I want to create some thing like this

```
<div style="width: 100%;margin-top: 20px;">
          <nb-card>
            <nb-card-body class="myIframe">
              <iframe src="https://www.youtube.com/embed/gSfc4GhlZ44" frameborder="0" webkitallowfullscreen
                mozallowfullscreen allowfullscreen></iframe>
            </nb-card-body>
          </nb-card>
        </div>
```

I already create custom component for this, but i want to pass a value to iframe src, so users can add this component and insert a src value in form builder display section. how can i achieve that?

**Comment by wag110894** [comment]
Hello @naonvl,

Thanks for reaching out! We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. 

Please contact support@form.io for more information.

Thank you.

**Comment by naonvl** [comment]
@travist Thanks for replying,

i already sent you an email, we're waiting your reply there, thanks again
