### ISSUE TITLE
Custom Component is not render in form.io tag

### ISSUE THREAD

**Issue by ThakkarHardik** [formio/angular#530]
hello @travist 

I made 2-3 custom component 
now i m rendering one by one on click of menu 
at first time my custom component is rendering proper , second time come to that component it is not rendering the proper , can you please help me out here.
![Untitled1111](https://user-images.githubusercontent.com/16595615/80273336-f2ad3f00-86ee-11ea-94f0-b19c4c7658b2.png) (first time click result )

![Untitled111](https://user-images.githubusercontent.com/16595615/80273351-00fb5b00-86ef-11ea-8451-49766e39068e.png) (second time result it means click on other menu and again click on the same menu)

**Comment by wag110894** [comment]
Hello @ThakkarHardik,  Can you confirm that you have read through the documentation and ensure that you are doing things correctly?
https://github.com/formio/formio.js/wiki/Custom-Components-API
https://github.com/formio/contrib

**Comment by benjamindamm** [comment]
I have the same issue. I am using my custom components in the FormBuilder as well, but when it comes to render them i get just an empty tag.

```
<div ref="component"
  class="form-group has-feedback formio-component formio-component-list-viewer formio-component-listViewer formio-component-label-hidden"
  id="edpuv0o">
  <div ref="element">
    <!-- This is where my component should be -->
  </div>
  <div class="formio-errors invalid-feedback" ref="messageContainer"></div>
</div>
```

**Comment by mubinahmed** [comment]
Did anyone figure out the solution for this? I have the same issue as well.

**Comment by dev-thinks** [comment]
> I've been struggling with this as well. It looks to me like my angular control `<app-whatever></app-whatever>` is being removed by the Sanitizer. I can get the control to render by adding an exception to the SanitizeConfig for the form renderer as follows:
> 
> ```
> const form = await Formio.createForm(
>       this.getRootElem(),
>       {
>         components,
>       },
>       {
>         // noAlerts: true,
>         formio: formIO,
>         readOnly: this.readonly,
>         formConfig: {
>           hide: !this.appSettings.show,
>         },
>         sanitizeConfig: {
>           allowedTags: ['app-whatever'],
>           addTags: ['app-whatever']
>         }
>       }
>     );
> ```
> 
> I still haven't found how to configure the Sanitizer for the form Builder however. Also I would have thought this would be handled by angular-formio registerCustomFormioComponent method as it's annoying to have to set these all in advance.

After struggling for an hour with this situation, this renderoptions object fixes in the form renderer part. Thanks for the clue, @TrevSAU

**Comment by OleksandrPoshtaruk1533** [comment]
<form-builder [form]="form" [options]="formOptions"></form-builder>

  formOptions = {
    sanitizeConfig: {
      allowedTags: ['some-wrapper'],
      addTags: ['some-wrapper']
    }
  };
  
  Made it work for builder
  Now need to do same for renderer
