### ISSUE TITLE
[BUG] Select Component rendering

### ISSUE THREAD

**Issue by pissardl** [formio/angular#535]
## Environment
- Hosting type
  - [ ] Form.io
  - [x] Local deployment
- Formio.js version:
- Frontend framework: "angular-formio": "^4.4.4",
- Browser: Chrome
- Browser version: 81.0.4044.129 (Build ufficiale) (a 64 bit)

    "@angular/animations": "~8.2.13",
    "@angular/common": "~8.2.13",
    "@angular/compiler": "~8.2.13",
    "@angular/core": "~8.2.13",
    "@angular/elements": "^8.2.13",
    "@angular/forms": "~8.2.13",
    "@angular/localize": "^9.0.7",
    "@angular/platform-browser": "~8.2.13",
    "@angular/platform-browser-dynamic": "~8.2.13",
    "@angular/router": "~8.2.13",
    "@ng-bootstrap/ng-bootstrap": "^5.2.0",
    "@webcomponents/custom-elements": "^1.3.2",
    "angular-font-awesome": "^3.1.2",
    "angular-formio": "^4.4.4",
	...
	
We have several small problems to use Select Component (all are using Data Source Type : URL) which are perhaps related to each other:
2 problems with HTML5 widget type
1 problem with ChoicesJS widget type

## A/ Using Select Component widget type HTML5
1. With Lazy Load Data, you need to click two you want to see the list of values.
2. if the value has already been saved (in draft), the data will not be displayed upon reopening. 
It is necessary to click on the Select Component to display the selected element.

## B/ Using Select Component widget type ChoicesJS
If ChoicesJS Select Component is positioned inside a Panel, as one of the last components contained in the Panel: 
The list of values is not displayed in its entirety, it is truncated from the end of the Panel.
The list of select values is not above the Panel (with the HML5 widget type Select Component there is no such problem).

**Comment by wag110894** [comment]
@pissardl,
 can you try upgrading to the latest version of angular and see if these issues still occur? If so, could you provide a JSFiddle with the issues so it is easy for us to reproduce on our side?

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
