### ISSUE TITLE
[BUG] while using encapsulation: ViewEncapsulation.ShadowDom property, form-builder drag and drop is not working

### ISSUE THREAD

**Issue by pooja-waikar** [formio/angular#537]
I trying to use encapsulation: ViewEncapsulation.ShadowDom property for my component to access only component css files, But when I use ShadowDom, form-builder drag and drop is not working.
I am not able to drag and drop components.

**Comment by travist** [comment]
Please provide a live example. Maybe a fiddle?

**Comment by JRiggenbach** [comment]
Strangely enough, I ran into this problem today also. I have an angular app that is primarily using material design so I only want to load up bootstrap for the components that are using the formio components.  I haven't tracked down why the bootstrap styles are not applied with the default Emulation view encapsulation, but they are when using ShadowDom encapsulation. Unfortunately the drag and drop does not work, as the original author has stated. I believe I tracked this down to an open but on the dragula library, which appears to have a pull request to fix but the repo appears dead.  I'll update my comment with an example when I get back in front of my computer.  In the meantime, any idea why the boostrap styling is not being applied if they are not on the global space?

**Comment by JRiggenbach** [comment]
After playing around a bit more, I've had moderate success by using ::ng-deep, I also had a few other styles to reset as well, so in my component .scss file.

```javascript
:host ::ng-deep {
  @import "../../node_modules/bootstrap/scss/bootstrap";
}

.formcomponents .formcomponent {
  margin-top: .2em;
}

.card-header {
  padding: 0;
}

.builder-group-button {
  background-color: transparent;
  text-align: left;
}
```
However, once the ::ng-deep got the styling working for the builder layout, once you drag a component into the drop area, the edit form modal pops up and this is no longer encapsulated within my angular component.  So in one of my global scss files, i added this

```javascript
.formio-dialog {
  @import "../../node_modules/bootstrap/scss/bootstrap";
}
```
I think I'd rather just have the shadow DOM option work, but at least I'm starting to make a little headway with this.  Perhaps I'll see what it takes to just create a material form builder also :)

**Comment by pooja-waikar** [comment]
> Please provide a live example. Maybe a fiddle?

layout-formbuilder.component.ts

@Component({
  selector: 'layout-formbuilder',
  templateUrl: './layout-formbuilder.component.html',
  styleUrls: ['./layout-formbuilder.component.css'],
  encapsulation: ViewEncapsulation.ShadowDom
})

@ViewChild("json") jsonElement?: ElementRef;

  public form: Object = {
    components: []
  };

  onChange(event) {
    this.jsonElement.nativeElement.innerHTML = "";
    this.jsonElement.nativeElement.appendChild(
      document.createTextNode(JSON.stringify(event.form, null, 4))
    );
  }

-----------------------------------------------------------
layout-formbuilder.component.html

<form-builder [form]="form" (change)="onChange($event)"></form-builder>


-------------------------------------------------------
layout-formbuilder.component.css

@import "~bootstrap/dist/css/bootstrap.css";
@import "font-awesome/css/font-awesome.min.css";


this is my component code

**Comment by dev-thinks** [comment]
Approach mentioned by @JRiggenbach works well. fortunately i made it worked before seeing this thread.

Our app is not having bootstrap for all other components, only importing  bootstrap 4 for form.io pieces.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.

**Comment by simionato-ennovaresearch** [comment]
IMHO this is still relevant in 2026. Right now is **extremely** hard to scope the `<form-builder>` styles.
I guess having the Shadow DOM to work would solve the issue (except for the opened modal, though...)

**Comment by heather-formio** [comment]
@simionato-ennovaresearch Thanks for linking. @brendanbond is there anything with the new styling that might help with this for the builder context?

**Comment by lane-formio** [comment]
This should be resolved with the introduction of our standard template which includes the builder chrome, so the shadow DOM will no longer be necessary to "silo" the builder's bootstrap-based components from the wider application. However, if the goal is to use shadow DOM for some other purpose, we still don't have explicit support.

https://help.form.io/developers/form-development/form-templates/the-form.io-standard-template

I'll flag this internally so I can follow up when we have our initial release of the standard template (expected Q2 of 2026).

For internal reference: FIO-10918
