### ISSUE TITLE
[Question] Can we display wizard pages in a single page for preview

### ISSUE THREAD

**Issue by satheeshpandian** [formio/angular#548]
I have implemented a multiple page option using wizard. In preview page change display:wizard to display:form to display all tabs in a single page. Its coming correctly. But select box items load with URL is not working.

**Comment by wag110894** [comment]
@satheeshpandian, can you please provide a jsfiddle of this issue taking place?

**Comment by dev-thinks** [comment]
@satheeshpandian, May be readonly mode of the form with form type as "form" instead of wizard will take of your request?

**Comment by travist** [comment]
Just change the display of the form to "form" and it will show a wizard as a flat form.

```js
(new Formio('https://examples.form.io/wizard')).loadForm().then(function(form) {
  form.display = 'form';
  Formio.createForm(document.getElementById('formio'), form);
});
```
