### ISSUE TITLE
What to refresh in EventEmitter

### ISSUE THREAD

**Issue by dmenne** [formio/angular#555]
I have read  `https://github.com/formio/angular-formio/wiki/Form-Renderer#updating-forms-and-submission` dozens of times. The refresh event show there is for a static submission. 

In the example below I have to refresh the browser manually when `:id` changes, otherwise the browser shows the correct url, but does not load the content.  As I understand, I should emit a refresh, but I have no idea how the parameters of refresh should look like in this case.

HTML:

```
<formio [src]="activeViewUrl" [refresh] = "refreshForm"></formio>
```

.ts
```
  activeViewUrl: string
  refreshForm: EventEmitter
...
  ngOnInit(): void {
    this.refreshForm = new EventEmitter();
    this.activeViewUrl =  this.config.appUrl + '/' + this.route.snapshot.params[`id`]
    this.route.params.subscribe(
        (params: Params) =>  {
          this.activeViewUrl =   this.config.appUrl + '/' + params[`id`]
         // **** What to write here *******
          // this.refreshForm.emit('the src')
        }
      )}
```

**Comment by travist** [comment]
It should be of type FormioRefreshValue seen @ https://github.com/formio/angular-formio/blob/master/src/formio.common.ts#L9 which means you cannot pass in the "string" to the form, but it needs to be the form JSON. You will need to load the form first like so.

```
import { Formio } from 'angular-formio';

(new Formio(formSrc)).loadForm().then((form) => this.refreshForm.emit({ form }));
```

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
