### ISSUE TITLE
[Question] How SaveDraft in wizard form

### ISSUE THREAD

**Issue by osvaldo-santos** [formio/angular#558]
Hi, Ihave been working with formio but i haven't found a way to save wizard draft using <formio> directive. Save draft is only allowed to FormManager???

**Comment by wag110894** [comment]
You will need to create a button and set the Action as 'Save in State' and set the 'Save in state' setting to 'draft'. You will then need to create a new submission action and add 'Submission State = "draft";'. You need to ensure that the same name that you have in the 'Save in state' setting is the same as what the submission state is equal to.
Here is a screenshot for the save as draft button: https://share.getcloudapp.com/YEuAY1bk
Here is a screenshot of the Submission Actions: https://share.getcloudapp.com/JruWYb5w

Here is some additional information: https://formio.github.io/formio.js/app/examples/savedraft.html

**Comment by wag110894** [comment]
@osantos1910 

Thank you for your patience while we got an example of this working for you. 

Here it is: 

<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://unpkg.com/formiojs@latest/dist/formio.full.min.css">
    <script src="https://unpkg.com/formiojs@latest/dist/formio.full.min.js"></script>
    <script type="text/javascript">
        window.onload = function() {
            Formio.icons = 'fontawesome';
            Formio.createForm(document.getElementById('formio'), 'https://examples.form.io/customwizard', {
                buttonSettings: {
                    showCancel: false,
                    showPrevious: false,
                    showNext: false,
                    showSubmit: false
                }
            }).then(function(wizard) {
                wizard.on('gotoNextPage', function(event) {
                    wizard.emit('submitButton', {
                        state: 'draft',
                        instance: wizard,
                    });
                    wizard.nextPage();
                });
            });
            wizard.on('gotoPreviousPage', function() {
                wizard.prevPage();
            });
            wizard.on('wizardSave', function() {
                wizard.submit().then(function() {
                    wizard.onChange();
                    wizard.nextPage();
                });
            });
        };
    </script>
</head>

<body>
    <div id="formio"></div>
</body></html>

I hope that this helps.

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
