### ISSUE TITLE
[Custom Components] HTML for Custom Component using Angular Elements

### ISSUE THREAD

**Issue by bandman0226** [formio/angular#572]
I have followed the directions on how to add custom components using angular elements from this page:

https://github.com/formio/angular-formio/wiki/Custom-Components-with-Angular-Elements

The new component shows up in the toolbox of the builder and gets added to the form just fine.

![2020-07-01 11_26_13-Rhooster](https://user-images.githubusercontent.com/26914029/86268343-ab7b7880-bb8d-11ea-8116-c687b441812c.png)

I am wanting to see if I can get the component to render like the file upload control that is already available.
 
![2020-07-01 11_23_32-Rhooster](https://user-images.githubusercontent.com/26914029/86268127-563f6700-bb8d-11ea-8a7b-981345f3ec5b.png)

Any insight would be greatly appreciated!

**Comment by merobal** [comment]
For custom components like this, you may build the component's logic and template with Angular. Also, you can use any of the angular-based third-party libs from npm, wrap that in a custom Angular component and register as formio field.

**Comment by bandman0226** [comment]
Is there a way to add a single property to the already existing component?

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
