### ISSUE TITLE
[BUG] - Updating to 4.9.0 leads to Zonejs promise polyfill error being thrown 

### ISSUE THREAD

**Issue by pkarakal** [formio/angular#575]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 4.9.0 
- Formio.js version: 4.10.5
- Frontend framework: Angular 6
- Browser: Firefox
- Browser version: 78.0.1

## Steps to Reproduce
1. Install angular-formio@4.10.0
2. Run the application
3. Open it on Firefox

## Expected behavior
I would expect it to run with its new features

## Observed behavior
It opens on Chrome/Chromium-based browser but throws the following error on Firefox

```
Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
```

In my package.json, I already have the necessary peer dependencies that `angular-formio` requires.

**Comment by pkarakal** [comment]
Note: this seems to work fine when using Angular 9

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
