### ISSUE TITLE
how to show or hide input fields based on radio buttion in angular-formio?[Question] 

### ISSUE THREAD

**Issue by Gayudhaya** [formio/angular#577]
{
            label: "Gender",
            labelPosition: "left-left",
            optionsLabelPosition: "right",
            inline: false,
            tableView: false,
            values: [
                {
                   label: "male",
                   value: "male",
                    shortcut: "M"
                },
                {
                    label: "female",
                    value: "female",
                    shortcut: "F"
                }
            ],
            key: "gender",
            type: "radio",
            input: true,
            labelWidth: 20,
            //labelMargin: 1
        },
       // this is radio button field

**Comment by rajakdr** [comment]
Hi @Gayudhaya , can you try on  Advanced Logic or conditional options. i think it will solve your problem. or try this .

{
      "components": [
        {
          "label": "Gender",
          "labelPosition": "left-left",
          "optionsLabelPosition": "right",
          "inline": false,
          "tableView": false,
          "values": [
            {
              "label": "Male",
              "value": "male",
              "shortcut": "M"
            },
            {
              "label": "Female",
              "value": "female",
              "shortcut": "F"
            },
            {
              "label": "Others",
              "value": "others",
              "shortcut": "O"
            }
          ],
          "validate": {
            "required": true
          },
          "key": "gender",
          "type": "radio",
          "input": true
        },
        {
          "label": "Gender Others",
          "tableView": true,
          "key": "genderOthers",
          "conditional": {
            "show": true,
            "when": "gender",
            "eq": "others"
          },
          "logic": [
            {
              "name": "Required",
              "trigger": {
                "type": "simple",
                "simple": {
                  "show": true,
                  "when": "gender",
                  "eq": "others"
                }
              },
              "actions": [
                {
                  "name": "Requireds",
                  "type": "property",
                  "property": {
                    "label": "Required",
                    "value": "validate.required",
                    "type": "boolean"
                  },
                  "state": true
                }
              ]
            }
          ],
          "type": "textfield",
          "input": true
        }
      ]
    }

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
