### ISSUE TITLE
[Custom Components] JSON Schema and Form Data on Custom Component

### ISSUE THREAD

**Issue by rajakdr** [formio/angular#578]
Hi,
I am using angular formio 4.8.4 and i created one custom component button (MnabrButton). Here i need to get the all parameters what assigned to this custom component button in form JSON (Ex : attributes, properties, label, DefaultValue and custom parameters....). and FORM Data what i filled on this form. i tried all blogs for this issue. i could not find the issue. If any one can please share your ideas. Thanks.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
