### ISSUE TITLE
Is CORS supported?[Question] 

### ISSUE THREAD

**Issue by qingliaowu** [formio/angular#586]
Is CORS supported for PDF uploading function?
![Screen Shot 2020-07-17 at 20 52 34](https://user-images.githubusercontent.com/41318040/87854699-9739c880-c94e-11ea-9dc6-443ae331ab4b.png)

**Comment by travist** [comment]
Yes it should be, although it seems you are trying from localhost. This may require a special case to enable that to work correctly. We will investigate on our end.

**Comment by qingliaowu** [comment]
Cool, thanks

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
