### ISSUE TITLE
[Question]  How to remove help 

### ISSUE THREAD

**Issue by william-levi** [formio/angular#587]
Is there a way to remove this "help" ?
![Capture](https://user-images.githubusercontent.com/25534399/87890218-140c9580-ca68-11ea-9f82-9cc79fccdfd3.PNG)

**Comment by travist** [comment]
You could hide it with CSS.

**Comment by dev-thinks** [comment]
something like this -

```
body a[href*='help.form.io'] {
  display: none !important;
}

```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
