### ISSUE TITLE
[Question] Set Default Value

### ISSUE THREAD

**Issue by william-levi** [formio/angular#588]
How to set default value in editForm ? 
![Capture2](https://user-images.githubusercontent.com/25534399/87891466-9a2adb00-ca6c-11ea-9c22-f0569e7330df.PNG)
![day](https://user-images.githubusercontent.com/25534399/87891467-9b5c0800-ca6c-11ea-858f-0fcafed6f0ab.PNG)

Like in the image.. setting default value for dayFirst. 

Thanks !

**Comment by wag110894** [comment]
@william-levi 
Thanks for reaching out!

The default value setting is located inside of the Data Tab.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
