### ISSUE TITLE
Unable to edit content properly in Custom Validation, Custom Values, Item Template sections for all Components

### ISSUE THREAD

**Issue by gopikrishna123** [formio/angular#593]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
In the text editors of Custom Validation, Custom Values, Item Template , there are additional spacing getting appended while typing which is making it difficult to edit the content. There are issues when typing the backspace also. Requesting help to resolve this issue.

Below are the series of screenshots which automatically adds spaces before the cursor as we type,
1.One space seen before the cursor
![image](https://user-images.githubusercontent.com/24910318/88316367-bbe2c700-cce5-11ea-98de-a81d94df4441.png)

2.Two spaces is seen before the cursor.

![image](https://user-images.githubusercontent.com/24910318/88316395-c69d5c00-cce5-11ea-80e2-0464ce136ad3.png)

3.Three spaces is seen before the cursor.

![image](https://user-images.githubusercontent.com/24910318/88316415-d0bf5a80-cce5-11ea-9468-6891b5424590.png)

**Comment by cmcortez** [comment]
This issue was submitted via support. Please reference your support ticket and provide the form embed URL we requested.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
