### ISSUE TITLE
[Custom Components] How to add validations to Custom Component

### ISSUE THREAD

**Issue by ullas1989** [formio/angular#594]
Hi @travist 
I have a custom component that can display some rows.

I want to implement the validation inside custom component such that if row count is 0, it triggers a required validation. So custom component need to pass its status as Invalid and error back to formio instance.

Any idea how to do this?

I have read all the custom component documentation but not able to find any solution.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
