### ISSUE TITLE
Signature with disable property [Question] 

### ISSUE THREAD

**Issue by bandman0226** [formio/angular#595]
I had a quick question. I am noticing that if I have a signature filled in the component and the readOnly property is set to true on the form then the signature shows just fine. If I turn off readOnly for the form and disable the signature (in case a user has to fill out other properties without changing the signature) then the signature does not render. Is this working by design or a bug? Is there a work around with this?

**Comment by travist** [comment]
We have had some issues with the signature component, but we have recently resolved these issues with the latest RC builds of the renderer. Have you tried using the RC versions of this library and see if this issue goes away with them?

**Comment by bandman0226** [comment]
Thank you so much @travist! I updated from 4.79 to 4.9.2. Seems like somewhere in there the issue was resolved.

**Comment by dev-thinks** [comment]
waiting for this bug to be resolved. please let us know when this will be available as general release.

**Comment by wag110894** [comment]
@dev-thinks, As Travis mentioned above, can you try using one of the RC versions and see if the issue goes away?

**Comment by bandman0226** [comment]
@travist We did not upgrade to any RC version but we did upgrade angular formio to 4.9.2 and it seemed to work with a css change we implemented as well. 

The signature pad did not render still unless we changed the css of that component to have "display: unset". In the previous version if we changed this property then it would display the signature but it could be modified (even with disabled).

**Comment by travist** [comment]
Just released new versions today with some fixes to signature component. Please try the latest and let us know if the issue still persists.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
