### ISSUE TITLE
[BUG] - Form Builder Fails To Customize  the Display Properties When Placing Other Component Inside Column Components

### ISSUE THREAD

**Issue by GAK-MPRO** [formio/angular#599]
## Environment
https://formio.github.io/angular-demo/#/forms/builder
- Could be reproduced by cloning and localhost
- Hosting type

  - [X] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework: Angular 8
- Browser: Chrome
- Browser version:84.0.4147.89 (Official Build) (64-bit)

## Steps to Reproduce
1. Go to https://formio.github.io/angular-demo/#/forms/builder
2.  Drag column component, and then inside one of the columns, try placing a textbox, and then edit the label
3. Click Save
4. Json Viewer should have been updated with customized value, instead it does not reflect any customization that was added to  the textbox. 
5. The same happens on local system

## Expected behavior
Json Viewer should have been updated with customized value. For e.g, for a textbox with a custom label "test label", it should have been
```js
components": [
        {
            "label": "Columns",
            "columns": [
                {
                    "components": [
                        {
                            "input": true,
                            "key": "textField",
                            "tableView": true,
                            **_"label": "test label",_**
                            "type": "textfield",
                            "hideOnChildrenHidden": false
                        }
                    ],
                    "width": 6,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "size": "md"
                },
```
## Observed behavior
```js
{
    "components": [
        {
            "label": "Columns",
            "columns": [
                {
                    "components": [
                        {
                            "input": true,
                            "key": "textField",
                            "tableView": true,
                            "label": "Text Field",
                            "type": "textfield",
                            "hideOnChildrenHidden": false
                        }
                    ],
                    "width": 6,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "size": "md"
                },
                {
                    "components": [],
                    "width": 6,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "size": "md"
                }
            ],
            "tableView": false,
            "key": "columns",
            "type": "columns",
            "input": false
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}
```
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.
<img width="1189" alt="Error" src="https://user-images.githubusercontent.com/35886913/88747597-bd145980-d114-11ea-997a-27607f1d1aa3.png">

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
