### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by praveenmadishetty** [formio/angular#603]
## Environment
I Have created a custom input text component using angular-formio,
and it is not detecting default value entered from settings to display in custom input text, Please help me regarding this.

Thanks in Advance
Praveen Madishetty

**Comment by iknityanand** [comment]
Even i am facing the same issue. Can't get default value in data tab. Also not getting default value data in the JSON output as well.

**Comment by wag110894** [comment]
@praveenmadishetty @iknityanand 

Thank you for reaching out! Form.io has support packages that will connect you with a developer to help you with your custom components. Please let me know if you are interested and I will ensure that you are connected to our Team with information regarding our Support Packages.

**Comment by praveenmadishetty** [comment]
Thanks for your Reply @wag110894 , But it would be helpful if i get help without going to support package Team Presently, the reason for this, is nothing but i just want to give a try with Formio, and know to what extent it can be compatible for my upcoming projects.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
