### ISSUE TITLE
[BUG] JSON undefined: When data entered into a field in form builder.

### ISSUE THREAD

**Issue by PranapSivadasan** [formio/angular#610]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: **Latest**
- Frontend framework: **Angular**
- Browser: **Firefox**
- Browser version: **79.0**

## Steps to Reproduce

1.  Add any field into the form.
       **For Example:** Add a text field into the form.
2.  Check the JSON. JSON is created properly. 
3.  Now Enter any value into the field and click anywhere outside the field, such that the submit button is highlighted.
       **For Example:** Add text "Hi" to the field and click outside.
4.  Check the JSON. JSON is undefined. 

## Expected behavior
JSON should always be defined.

## Observed behavior
JSON becomes undefined in the above conditions.

## Example
![Formio_JSON_undefined_error](https://user-images.githubusercontent.com/44242289/90893308-6250e380-e3dc-11ea-8184-83f95b826b3c.gif)

**Comment by PranapSivadasan** [comment]
@wag110894 Ya that's true. In that case either the **feature of adding data into the fields of builder must be disabled** or irrespective of what we enter into the field must be ignored and JSON data must be stable.

The Formio.js is proper
http://formio.github.io/formio.js/app/sandbox

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
