### ISSUE TITLE
[Question] File Storage without Portal

### ISSUE THREAD

**Issue by StefanRupertsberger** [formio/angular#617]
Hello Everyone!

I want to host my own minio (S3) instance for file storage.
As far as I know you have to configure your file storage on the form.io portal.
My problem is that I want my project to be available offline in my local network (no connection to form.io).

Is it possible to provide the necessary configuration directly to the builder/viewer?

**Comment by StefanRupertsberger** [comment]
And is it possible to get rid of this warning message "You must provide an AppConfig within your application!"?
It breaks the builder when I provide an empty AppConfig as a few people here suggested.
In the wiki it says I need to provide an appUrl to the form.io project. (<-- Don't want to depend on that)

**Comment by drosophila-melanogaster** [comment]
Hello, @StefanRupertsberger. Did you manage to find a solution for using MinIO as your File component storage provider? Thanks in advance.

**Comment by StefanRupertsberger** [comment]
Hi @drosophila-melanogaster, no sorry I didn't...

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
