### ISSUE TITLE
[Question] How to reset form validations on click on formIO button component

### ISSUE THREAD

**Issue by ullas1989** [formio/angular#618]
Is there a way to reset form validations when user clicks on a formIo button?

Right now, once validations are triggered, they keep on there until all the validation errors have been fixed.

**Comment by randallknutson** [comment]
You need to reset the pristine setting on the form. You should be able to do this in a custom script in the button with instance.root.setPristine(true);

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
