### ISSUE TITLE
change and invalid  events not working properly

### ISSUE THREAD

**Issue by dennitorf** [formio/angular#622]
Hi team! Any solution about this? I am in the same situation. I used a workaround, and I am forcing the user to make any change in the form in order to know if the form is valid or not. And, another issue is that when the event is fired the first time, the form is not valid, but is coming valid on the event.

_Originally posted by @dennitorf in https://github.com/formio/angular-formio/issues/560#issuecomment-692270370_

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
