### ISSUE TITLE
[BUG] The back camera is not enabled in file component

### ISSUE THREAD

**Issue by analorios93** [formio/angular#641]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.11.0
- Frontend framework: Ionic 5.4.16, angular 9.1.11 with cordova 9.0.0 
- Browser:
- Browser version:

## Steps to Reproduce
I have 4.11.0 angular-formio version and I have configured the settings of my component as: 
```
{
	"label": "Foto Equipo",
	"dataGridLabel": false,
	"tableView": false,
	"storage": "base64",
	"dir": "/",
	"fileNameTemplate": "Eb-",
	"image": true,
	"uploadOnly": true,
	"webcam": true,
	"fileTypes": [
		{
			"label": "png",
			"value": ".png"
		},
		{
			"label": "jpg",
			"value": ".jpg"
		},
		{
			"label": "pdf",
			"value": ".pdf"
		}
	],
	"fileMaxSize": "10MB",
	"persistent": false,
	"clearOnHide": false,
	"key": "fotoEquipo",
	"type": "file",
	"input": true
} 
```
I am testing my ionic application in Android Platform with Android 10 and when clicking on "Use Camera" button, it shows "Take picture" button but when clicking on it, it only enables the front camera of my phone and it doesn't allow to change to the other camera.  

Which is the right configuration of the component in order to get a picture with the back camera?

## Expected behavior
Being able to take pictures with the back camera
## Observed behavior
It only enables the front camera

**Comment by wag110894** [comment]
Hello @analorios93, can you provide a video of the issue occurring?

**Comment by analorios93** [comment]
In the video I'm attaching, you will see how is the front camera enable when clicking on "Take Picture" Button.
[Video with issue.zip](https://github.com/formio/angular-formio/files/5473917/Video.with.issue.zip)

**Comment by wag110894** [comment]
Can you try and click the browse button instead and select "Take Photo" and see if you are able to switch to the back camera from there?

**Comment by analorios93** [comment]
[Video 2.zip](https://github.com/formio/angular-formio/files/5476539/Video.2.zip)
Thank you for your answer Will, 
As you can see in the video I attached, the browse button just takes me to my phone gallery and there is no "Take Photo" button there.

**Comment by wag110894** [comment]
@analorios93, Can you provide an example so that we can replicate?

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
