### ISSUE TITLE
[Question] Using Data table on custom stored submissions and form template

### ISSUE THREAD

**Issue by vaishnavm217** [formio/angular#650]
similar to this https://github.com/formio/angular-formio/issues/185,
Is their anyway to show responses using `<formio-grid>` tag similar to the `form` and `submission` parameter passed

**Comment by travist** [comment]
Not sure what you mean by "show responses"...

**Comment by vaishnavm217** [comment]
The responses from the form is being stored in firestore rather than using the service. The formio grid only has `src` facility rather than like `form` or `submission` etc

**Comment by travist** [comment]
We currently do not support this. It would need to be introduced via community contribution.
