### ISSUE TITLE
[Custom Components] Custom component is re-rendering on every form change

### ISSUE THREAD

**Issue by michealharrington** [formio/angular#675]
After upgrading Angular to 10, my custom formio component is now refreshing on every form change which is resulting in the component losing it's state and flashing while it loads the previous state from the outer form.

The component is being destroyed and re-inited on every keystroke.

I'll gladly provide any other information needed.

**Comment by michealharrington** [comment]
Investigating this more, it seems to work as long as I don't install a newer version of formiojs 4.11.3.

**Comment by wag110894** [comment]
Hello @michealharrington, what version of angular-formio are you using?

**Comment by michealharrington** [comment]
The latest I could get to work was
angluar-formio = 4.9.6
formiojs = 4.11.3

**Comment by wag110894** [comment]
Hello @michealharrington, Thanks for providing your version. Form.io offers Support Packages that are for training, support, or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. I would be happy to provide you with our Support Packages Documentation if you are interested. 

If you are interested in hearing more about our commercial offerings we would be happy to set up a short call to hear more about your project and see how we can help.

**Comment by tvaidyan** [comment]
@wag110894 - I sent you a message (on LinkedIn) with my contact info.  I wanted to get more information on your training services.  Would you please get back to me with details when you get a chance?  Thanks!

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
