### ISSUE TITLE
[Question] [object DocumentFragment] as required message

### ISSUE THREAD

**Issue by penrodlol** [formio/angular#689]
For the formio builder, when Im in context of 'Select Boxes' and I navigate to my 'Data' tab and click 'Save' without filling out required fields, Im presented with the error message as shown on the image. Not sure if this is a bug or something that's gone wrong in our builder configuration json. Without diving in to the finer details of the configuration, is there any quick resolution that can solve/prevent this? Thanks

---

```
Versions:

- @angular/cli - 9.0.2
- angular-formio - 4.7.2
```

---

![Capture](https://user-images.githubusercontent.com/53282218/102261242-651d9a00-3edf-11eb-9bba-f9f0990652b7.PNG)

**Comment by wag110894** [comment]
@penrodlol, 

Thanks for reaching out! 
It looks like you are running on an older version of angular-formio. Can you try upgrading and see if the issue still occurs?

**Comment by penrodlol** [comment]
@wag110894 I upgrade to v4.11.2 the issue still remains... Here's a snippet of our config:

![config](https://user-images.githubusercontent.com/53282218/102263882-e32f7000-3ee2-11eb-9c9b-21b54dfda263.png)

**Comment by wag110894** [comment]
Hello @penrodlol, we are still not able to replicate on our side. Can you provide a JSFiddle of this issue taking place?

**Comment by penrodlol** [comment]
@wag110894 Ended up being a mistake on our side. Apologies.
