### ISSUE TITLE
cdn.form.io/flatpickr/flatpickr.min.js and min.css not found

### ISSUE THREAD

**Issue by learner291** [formio/angular#691]
One of our projects is hosted internally and does not have access to internet. When we run the project, calls to flatpickr.mins.js and min.css fail because internet access is not allowed. I have searched the entire project but unable to find the reference to this file. Do I need to install any component so that these two files are available locally and cdn call is not performed?

Thanks

**Comment by travist** [comment]
If you want this to work offline, then you will need to include Flatpickr as part of your application like so..

```js
import { Flatpickr } from 'flatpickr';
window.Flatpickr = Flatpickr;
```

Our renderer will first check to see if there is a globally available Flatpickr and will not lazy load the CSS or JS if it is available.

**Comment by learner291** [comment]
Thanks @travist for your suggestions.

I added the suggested code but I get Module has no exported member 'flatpickr' error.

![image](https://user-images.githubusercontent.com/40409548/103350310-74801400-4a97-11eb-9edb-a2cfeb07882c.png)

So after searching web a lot, I used the below statements, and now `flatpickr.mins.js` error does not appear however it is still unable to find min.css file, which means that clicking on Date Picker button does not display calendar. Do you know what is still missing?

```
import * as _flatpickr from 'flatpickr';
import { FlatpickrFn } from 'flatpickr/dist/types/instance';
const flatpickr: FlatpickrFn = _flatpickr as any;
```

**Comment by travist** [comment]
You just need to import the flatpickr.css file into your SASS file of your application.

**Comment by dev-thinks** [comment]
looks like implicit npm dependency on "flatpickr" has been removed. we need to install "flatpickr" npm package explicity to make it work with latest versions.
