### ISSUE TITLE
Formio slows down after validation error

### ISSUE THREAD

**Issue by animeshk874** [formio/angular#693]
We have a pretty complex form with conditional fields and custom validation. These forms lag a bit initially, but it works. However, the moment I get some error due to validation, the form slows down a lot. It takes almost 2-3 seconds (or even more) to register key presses and hide/show conditional fields. And since everything is synchronous, it blocks the main thread, leaving the entire page unusable for that 2-3 seconds. Also, the WYSIWYG editor takes some time to initialize and intercept key strokes irrespective of validation errors.

Here's a screenshot of Safari 13.1.2.

![Screen Shot 2020-12-30 at 16 15 55](https://user-images.githubusercontent.com/26036974/103346814-2f6dd900-4abb-11eb-9df1-f89de74924c7.png)

Angular version: 8.2.14
angular-formio version:  4.11.0

@chirayu14 @codekidX

**Comment by jhen1422** [comment]
@animeshk874 Could you please try upgrading to angular-formio version: 5.0.0 to see if that resolves the issue?

If the issue persists after upgrading, please include a jsfiddle of the form showing the slowdown.

Thanks!

**Comment by animeshk874** [comment]
Thanks @jhen1422

**Comment by animeshk874** [comment]
Thanks @jhen1422. Will try upgrading the version

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
