### ISSUE TITLE
[Question]  Disable or hide action button of field-set 

### ISSUE THREAD

**Issue by mohammadaaqib** [formio/angular#697]
i want to disable or remove these action buttons  for some user . Can i achive this ? if yes than How ?

![remove button](https://user-images.githubusercontent.com/14867369/103566643-28443200-4ee4-11eb-9cdc-14518d8f6b6b.png)

**Comment by wag110894** [comment]
Hello @mohammadaaqib, you can accomplish this by editing the form builder.

**Comment by mohammadaaqib** [comment]
hi, @wag110894 thank you for your reply.
any example or anything which helps me in this regard

**Comment by travist** [comment]
You need to override the template https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/builderComponent/form.ejs using the documentation found @ https://github.com/formio/formio.js/wiki/Templates-API#overriding-templates

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
