### ISSUE TITLE
How to populate a dropdown control from own backend data store at runtime?

### ISSUE THREAD

**Issue by tvaidyan** [formio/angular#699]
I'm embedding a form.io form in my Angular application.  Within this form, there is a dropdown control.  I want to programmatically add items into this dropdown control when the form is rendered from within my angular component.  How can I achieve this?  To be clear, I can't determine the values that will be in this dropdown, ahead of time (during form design time).  It can only be fetched from an external database in ngOnInit at the time when the component is loaded.  I just need a way to inject that data as select list items that the end-user can then pick from. Also, I don't need to worry about saving these dynamically added values back into the form.io backend.  I have a custom event wired up for this form and I'll collect the data back and do my own separate processing with it, outside of the form.io enviroment.

**Comment by travist** [comment]
This can be done by creating an API endpoint for your own backend data, and then configure the Select dropdown to use the URL based data source, and then point that to the API endpoint connected to your own dataset.

**Comment by tvaidyan** [comment]
Thank you @travist !  But, can you please weigh-in on a couple of the details of my use-case?

1. The values that I need to pull from my own database backend is depended on something else on the loaded form.  For example, say I have a dropdown value of "Car Makes".  If the user picks "Toyota" from this list.  I want to call my backend API with a parameter of "Toyota" and have it return all the "Car Models" for just Toyota.   As such, I can't login to the form.io portal and set the API URL ahead of time but I'll need to pass this customized URL to the form, within my Angular component. How can I do so?
2. Since I posted this question, I figured out on my own, how to get access to the formio object within angular, and wrote a very ugly function to traverse all it's node to look for a particular element.  For example, the dropdown that I'm interested in is several levels deep - in a panel, in a column, in a well.  By using this brute-force approach, I can finally get my element and then push items to its data property and I can get this to work.  But, is there a better way to do this?  Someone an ability to simply pass the "key" for a particular form element and then add/remove items from its data property?

Thanks,
Tom

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
