### ISSUE TITLE
How to Call Formio Validation Function on  Custom COmponent 

### ISSUE THREAD

**Issue by mehdi47** [formio/angular#700]
Hi,

I'm currently using angular-formio in a project, i created a custom phone component using ngx-intl-tel-input, when i click on the submit button, the custom component phone validation doesn't work, so my question is this : how can i call the formio validation on my custom component so i can cancel submission if there are any errors ?

Thank you.

**Comment by wag110894** [comment]
Hello @mehdi47,

Thanks for reaching out!

We do offer Support Packages that are for training, support, or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions.  Please contact support@form.io if you are interested.

Thank you!

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
