### ISSUE TITLE
[BUG] Validation on blur not working on day component.

### ISSUE THREAD

**Issue by pathompongthapuech** [formio/angular#701]
## Environment
- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: 4.11.1
- Frontend framework: Angular 9
- Browser: Chrome
- Browser version: 87

## Steps to Reproduce
1. Add a day field into the form builder.
2. Set validation on blur.
3. Make sure to check Require Day or Month or Year.

## Expected behavior
Validation error message must be displayed when the day field is empty.
## Observed behavior
Validation error message not display when the day field is empty.

**Comment by wag110894** [comment]
Hello @pathompongthapuech, 

In order for the validation blur to fire, you need to insert data into the Day component. You will also need to add a min year and max year (ex. Need to have the year in-between 2000 and 2021). You will fill out the component and trigger the min or max validation. You will then tab into a new component and begin typing, then the validation will trigger saying that the Day should not contain year less/more than 2000. Here is a video: https://share.getcloudapp.com/qGul2y7W
