### ISSUE TITLE
[BUG] Columns component preview is not correct

### ISSUE THREAD

**Issue by sanjaypraja** [formio/angular#702]
On demo https://formio.github.io/angular-demo/#/forms/builder
I have used columns component preview modal **Column Properties** section design is not perfect. Can we  fix it to change left div class properties col-6 to col-12? or if you have any other suggestion.
![Screenshot from 2021-01-20 20-41-20](https://user-images.githubusercontent.com/2256488/105198332-9125de00-5b63-11eb-9211-9253eeb43ecb.png)

**Comment by travist** [comment]
I believe this is just an issue where the table is overflowing the columns. The values of the columns seem correct "col-6". So this is probably a minor styling issue with the custom properties. We would need a community contributed fix if you want to see resolution to this one.

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
