### ISSUE TITLE
Compatibility to latest Angular version

### ISSUE THREAD

**Issue by nilsleistner** [formio/angular#704]
Hi,
trying to install formio/angular throws several warnings in the console, because of missing required dependencies. I am using the latest versions of Angular and Ionic (Angular 10 and Ionic 5) which are at least one version newer than your requirements.

Required versions:
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/38067181/105703432-82497d80-5f0d-11eb-9092-7a36b865c1b4.png">
Installed versions:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/38067181/105703472-93928a00-5f0d-11eb-88ea-b33c133f588b.png">

The formio component works with my installed angular versions, but unfortunately the form fields were not rendered as expected. Does this depend on the incorrect requirements used?

How it looks in my test-app:
![image](https://user-images.githubusercontent.com/38067181/105705058-f08f3f80-5f0f-11eb-9957-5dad4e2b923b.png)
How it looks on form.io page:
![image](https://user-images.githubusercontent.com/38067181/105704768-955d4d00-5f0f-11eb-8839-982f72d51287.png)

I have another question belonging to this:
When I change the source of the component, the component is not reloading. Is this also depending on my dependency problems?

Im am using the formio component in my testapp like this:
```
<ion-button color="primary" (click)="userRegisterForm()">First Form</ion-button>
<ion-button color="secondary" (click)="adminLoginForm()">Second Form</ion-button>
<div class="ion-padding" *ngIf="formIoLink">
    <formio [src]="formIoLink"></formio>
  </div>
```
TS class:
```
export class Tab1Page {

    public formIoLink = '';

    constructor() {}

    userRegisterForm() {
        this.formIoLink = 'https://bisqjanyjxbujeo.form.io/user/register';
        console.log(this.formIoLink);
    }

    adminLoginForm() {
        this.formIoLink = 'https://bisqjanyjxbujeo.form.io/admin/login';
        console.log(this.formIoLink);
    }

}
```

Regards,
Nils

**Comment by travist** [comment]
Please use ```@formio/angular``` instead of ```angular-formio``` package.

**Comment by nilsleistner** [comment]
Thanks a lot. But that doesn't solve my issues. It is still not getting rendered as expected (tested in an ionic and an angular app). But because this was just for testing stuff the angular integration is no longer needed (for now).
