### ISSUE TITLE
[Question] Select Component - Disable specific dataSrc

### ISSUE THREAD

**Issue by StefanRupertsberger** [formio/angular#705]
Is it possible to disable a specific `dataSrc` for the select component using the builder options?

For example I want to disable the Option `IndexedDB`. How could I achieve that?

**Comment by travist** [comment]
Yes, you can override the "editForm" for the select and then modify that select dropdown to not include it. Something like this maybe?...

```js
var selectEditForm = Formio.Components.components.select.editForm;
Formio.Components.components.select.editForm = function() {
  var editForm = selectEditForm();
  var dataSrc = Formio.getComponent(editForm, 'dataSrc');
  dataSrc.data.values = [
        { label: 'Values', value: 'values' },
        { label: 'URL', value: 'url' },
        { label: 'Resource', value: 'resource' },
        { label: 'Custom', value: 'custom' },
        { label: 'Raw JSON', value: 'json' }
      ];
  return editForm; 
};

```

**Comment by StefanRupertsberger** [comment]
That looks to be the thing I wanted.

I have two problems with it...
`error TS2339: Property 'Components' does not exist on type 'typeof Formio'.`

 It seems to work because 
`var dataSrc = Formio.getComponent(editForm, 'dataSrc');`
 throws an error that `Formio.getComponent is not a function`.

**Comment by travist** [comment]
This means that Formio is not defined. How are you embedding the renderer in your application?

**Comment by StefanRupertsberger** [comment]
I am just using the tags (`<form-builder></form-builder>`) in my HTML and providing the options through binding.

**Comment by travist** [comment]
You need to import it in your src like so.

```
import { Formio } from '@formio/angular';
```

**Comment by StefanRupertsberger** [comment]
Hm ok. I used `import { Formio } from 'angular-formio'` as I installed that package.
Now I see there is that package `@formio/angular`.
Can I just install that one as well without breaking anything? / What is the purpose of that package?

Thanks for the help btw!

**Comment by travist** [comment]
```angular-formio``` - Is for Angular < 10
```@formio/angular``` - Is for Angular >= 10.

They have the same functionality and directory structures and should be interoperable.

**Comment by StefanRupertsberger** [comment]
I am now importing it like this:
`import { Formio } from "angular-formio";`

I am still getting an Error:
`Property 'getComponent' does not exist on type 'typeof Formio'.`
at this line:
`const dataSrc = Formio.getComponent(editForm, "dataSrc");`

Using Angular 7.2.4 with angular-formio 4.11.2

**Comment by travist** [comment]
This may be a typescript configuration that is complaining about importing a library that does not have 100% type definition coverage. There may be a configuration where you can make it more lenient, but I am not sure what that it.

**Comment by StefanRupertsberger** [comment]
I tried to use `Formio` like this to avoid the compilation error:
```javascript
const dataSrc = (Formio as any).getComponent(editForm, "dataSrc");
```

Now I get the same error during runtime. so that function does not exist?.
I have now written a workaround that searches the editForm recursively for a key.

**Comment by drosophila-melanogaster** [comment]
I'm trying to do a similar thing for the `Edit Form > Button > Display > Action` dropdown. I've tried @travist's [suggestion](https://github.com/formio/angular/issues/705#issuecomment-767609815) but had the same problem with `getComponent()` as @StefanRupertsberger; ended up writing a workaround as well.

Now I have an updated `Action` dropdown, but none of the initial configuration provided via `[options]` to the `<form-builder>` Angular component (e.g. all the Edit Form tabs and inner components I've set to be ignored). Any ideas why?

**Comment by travist** [comment]
Any time you see that your changes are ignored by angular, the most common use case is that you are making the change on a different instance of ```Formio``` than what angular uses. For example, if you are doing this..

```js
import { Formio } from 'formiojs';
```

instead of this.

```js
import { Formio } from '@formio/angular';
```

**Comment by drosophila-melanogaster** [comment]
I see; thanks for the response.

In your example, you use `Formio` to access `Components` and `getComponent()`. However, `{ Formio } from '@formio/angular'` does not seem to contain these aforementioned objects here. Instead, I have to do this:

```javascript
import { FormioUtils, Components } from '@formio/angular';

const buttonEditForm = Components.components.button.editForm;
Components.components.button.editForm = () => {
    let editForm = buttonEditForm();
    let action = FormioUtils.getComponent(editForm.components, 'action', false);
    action.data.values = [
        { label: 'Submit', value: 'submit' },
        { label: 'Reset', value: 'reset' }
    ];
    return editForm;
};
```

And that's what makes the previously made configurations go default. Would there be any other way to do this?

**Comment by travist** [comment]
Components and "FormioUtils" should be part of the "Formio" class.

```js
import { Formio } from '@formio/angular';
console.log(Formio.Components); // Same as importing Components
console.log(Formio.Utils); // Same as importing FormioUtils.
```

Can you please confirm if this gives you anything?

**Comment by drosophila-melanogaster** [comment]
That gives me the same error @StefanRupertsberger got [here](https://github.com/formio/angular/issues/705#issuecomment-771450966); looks like TypeScript just putting me off. But if I declare a `Formio as any` I can then replace `Components` and `FormioUtils` for `Formio.Components` and `Formio.Utils`, but I still get the same results.

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
