### ISSUE TITLE
There is any way to implement Highchart.js inside the formio

### ISSUE THREAD

**Issue by ujjwal8055** [formio/angular#708]
We have MCQ type Question Answer in that we are giving a graph to analyze and answer the Question.

**Comment by travist** [comment]
Using our API's you can feed data into Highchart.js

**Comment by ujjwal8055** [comment]
Basically what I want, is to integrate any package at run time.
We generating form through `Formio.createForm` way
For Example: In ngx-webcam
`  <webcam (initError)="handleInitError($event)"></webcam>`

I want this <webcam></webcam> at run time.

I have done this

   Formio.createForm(params, {
      components: this.personalDetailsForm
    }).then((form: any) => {
      this.formData = form;
      const list = document.getElementsByClassName('class-266');
      **this.addGraph(list)**;
      form.submission = {
        data: this.stepData
      };
      form.on('submit', (submission: any) => {
        this.submitStep(submission);
      });
    });

  **addGraph**(data: any) {
    if (data.length) {
      const d1 = data[0].firstElementChild;
      d1.insertAdjacentHTML('afterend', '<div class="class-with-101" id="101"></div>');
      const component = this.resolver.resolveComponentFactory(HighChartsComponent);
      const componentRef = this.viewContainerRef.createComponent(component);
      const node = document.getElementById('101');
      node.appendChild(componentRef['location'].nativeElement);
    }
  }

https://stackblitz.com/edit/angularngxwebcam

**Comment by ujjwal8055** [comment]
Thank You @travist
