### ISSUE TITLE
[BUG] formComponent Draggable side bar gets hidden

### ISSUE THREAD

**Issue by ajaykumarsana** [formio/angular#709]
Hi @travist 
Hope you're doing good.
As part of micro front end development i'm using formio builder ( which suits our need) through [Single Spa](https://single-spa.js.org/docs/ecosystem-angular/#angular-cli).
**Steps**
1. By using form builder i just drag and dropped **Date/Time** field with default configuration
2. I saved the **JSON schema** from above steps in local storage .
3. Reload form builder with **formComponents** input saved in local storage.
4. Found issues like below, PFA.

issue 1:  left side **formComponent** gets hidden.
issue 2: Getting loader icon continuously in Rendered form.

Please help, 
Thanks a lot.
![image](https://user-images.githubusercontent.com/1854019/106268129-ab8d4500-6250-11eb-9fcf-03c7868f735b.png)

**Comment by travist** [comment]
I am seeing something different when I go to this demo.

https://formio.github.io/angular-demo/#/forms/builder

So, maybe you are doing something custom that is crashing? You may see a javascript crash in your console.

**Comment by ajaykumarsana** [comment]
@travist ,

Thank you for your reponse.
I took clone and had customised code from https://formio.github.io/angular-demo/#/forms/builder.

**Comment by ajaykumarsana** [comment]
If any one looking for solution, see below

Date/Time field uses flatpickr which doesn't gets load initially, so download flatpickr.js and load it initially in **script** tag
