### ISSUE TITLE
[Question] Form Builder: disable specific properties on Edit Form for all input types

### ISSUE THREAD

**Issue by drosophila-melanogaster** [formio/angular#710]
Hello,

One year ago a user asked the same thing in a [comment here](https://github.com/formio/angular-demo/issues/11#issuecomment-579718316), but he didn't get a proper response. When using Form Builder, is it possible to disable specific properties on Edit Form for all input types at once?

We have this to disable the API tab:
```javascript
{
  editForm: {
    textfield: [
      {
        key: 'api',
        ignore: true
      }        
    ]
  }
}
```

Do we have anything like this?
```javascript
{
  editForm: {
    __default__: [
      {
        key: 'api',
        ignore: true
      }        
    ]
  }
}
```

**Comment by travist** [comment]
We do not, but it could be added by changing this line 

https://github.com/formio/formio.js/blob/master/src/WebformBuilder.js#L1264

Should be a pretty simple fix and submit a pull request and we will review it on our end.

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
