### ISSUE TITLE
[Question] Form Builder: override default schema values for an input type on Edit Form

### ISSUE THREAD

**Issue by drosophila-melanogaster** [formio/angular#711]
Hello,

When using Form Builder, is it possible to override default schema values for an input type on Edit Form? For example, the `'Text Field'` value for `label` when initializing a `textfield` input on Edit Form?

From `src/components/textfield/TextField.js`:
```javascript
export default class TextFieldComponent extends Input {
  static schema(...extend) {
    return Input.schema({
      label: 'Text Field', // <----
      key: 'textField',
      type: 'textfield',
      mask: false,
      inputType: 'text',
      inputFormat: 'plain',
      inputMask: '',
      tableView: true,
      spellcheck: true,
      validate: {
        minLength: '',
        maxLength: '',
        pattern: ''
      }
    }, ...extend);
  }
  (...)
}
```

**Comment by travist** [comment]
You can override this by doing the following.

```js
const textFieldSchema = Formio.Components.components.textfield.schema
Formio.Components.components.textfield.schema = (...extend) => {
  var schema = textFieldSchema(extend);
  schema.label = 'Something custom here';
  return schema;  
};
```

**Comment by drosophila-melanogaster** [comment]
Thanks for the response; however, now I'm left with another problem.

If I have the following sequence:

```javascript
const textfieldSchema = Components.components.textfield.schema;
Components.components.textfield.schema = (...extend) => {
    let schema = textfieldSchema(extend);
    schema.label = '_textfield';
    return schema;
};

const textareaSchema = Components.components.textarea.schema;
Components.components.textarea.schema = (...extend) => {
    let schema = textareaSchema(extend);
    schema.label = '_textarea';
    return schema;
};

const passwordSchema = Components.components.password.schema;
Components.components.password.schema = (...extend) => {
    let schema = passwordSchema(extend);
    schema.label = '_password';
    return schema;
};
```

The labels get properly overriden, but then the fields that extend the `TextFieldComponent` all default to the `textfield` type:

![image](https://user-images.githubusercontent.com/78229449/106912481-d14b9b80-66e1-11eb-9812-34e5b6cd10b1.png)

Also, the `form.components` object outputs the following:

![image](https://user-images.githubusercontent.com/78229449/106912967-4e771080-66e2-11eb-8103-4deaca5ec18a.png)

...which I believe is not correct. Any ideas on what might be the issue?

**Comment by DmitryNistratov** [comment]
Hello @drosophila-melanogaster
Try the following way:
`const textfieldSchema = Components.components.textfield.schema;
Components.components.textfield.schema = (...extend) => {
  return textfieldSchema({label: '_textfield'}, ...extend);
};

const textareaSchema = Components.components.textarea.schema;
Components.components.textarea.schema = (...extend) => {
  return textareaSchema({label: '_textarea'}, ...extend);
};
...`

**Comment by drosophila-melanogaster** [comment]
Hello, @DmitryNistratov. Thanks for the response; this seems to address the issue, despite my IDE complaining about the rest parameter.
