### ISSUE TITLE
[Question] How to register a library of custom components. 

### ISSUE THREAD

**Issue by Squiff-cmd** [formio/angular#712]
Hi, 
I am currently developing a project with form.io that spreads across two applications.

(Angular app) : Where forms can be built / saved, using the @formio/angular package, specifically its builder. 
(MVC app) : Where forms are rendered and completed using the vanilla formio.js package.

After reading the useful documentation/code provided on [how to build a custom component library](https://github.com/formio/contrib) I've come to the point where I need to register the module of components with form.io. It is documents clearly how to do so in the vanilla package, but is it possible to register the same module and its components within the angular application. 

If not, at the moment I am assuming I have to create a duplication of components across both apps. Creating the same custom components I've made in the vanilla package in they angular version [using this method](https://gist.github.com/travist/59fa77086ec899e24992fc1508e61075)

Thanks,
Ben

**Comment by travist** [comment]
You can do it in angular as follows.

```js
import { Formio } from '@formio/angular';
import FormioContrib from 'your-clone-of-contrib-library';
Formio.use(FormioContrib);
```
