### ISSUE TITLE
How data can be changed when the data schema changes 

### ISSUE THREAD

**Issue by Anatoliy-Kas** [formio/angular#713]
How can I change the data when the data schema changes. For example, in the schema, the XXX field is moved to the container. I want the old data to remain valid when changing the schema.
Can I do it ?

**Comment by DmitryNistratov** [comment]
As a solution, you can use Advanced Logic:
```js
result = !row[instance.key] && instance && instance.pristine && instance.root && instance.root.submission && instance.root.submission._id;

value = data[instance.key] || instance.defaultValue;
```
![image](https://user-images.githubusercontent.com/68227834/107227255-3bd74100-6a2c-11eb-96d5-f3b2de170f45.png)

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
