### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by praveen5959** [formio/angular#716]
I want to change the look and feel of the forms-builder. I know Templating is available to use Bootstrap, semantic or bulma CSS. But I want to use my own custom theme to change the look and feel of forms-builder.

Is it possible?

**Comment by wag110894** [comment]
Hello @praveen5959,

Thank you for your interest in Form.io!

In the future, please submit your questions to Gitter( located here: https://gitter.im/formio/formio) for our community support.  We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. If you are interested in learning more about our Support Packages, then please contact support@form.io.

Thank you have a great day!
