### ISSUE TITLE
validate formio json

### ISSUE THREAD

**Issue by AA299** [formio/angular#717]
how to validate json in formio is there anything to  check form json is valid or not

**Comment by wag110894** [comment]
Hello @AA299,

Thank you for your interest in Form.io!

In the future, please submit your questions to Gitter( located here: https://gitter.im/formio/formio) for our community support.  We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. If you are interested in learning more about our Support Packages, then please contact support@form.io.

Thank you have a great day!
