### ISSUE TITLE
[How to have a custom submit button in form - renderer ?] 

### ISSUE THREAD

**Issue by abhishek0196** [formio/angular#721]
I'm looking for having a custom submit button in the form render, with the ability to disable it if the form is invalid. 
I have used the change event but it emits twice, on the initial load.
`<formio #f [form]="formIOJSON" (change)="onChange($event)" [submission]="formSubmittedData"
        style="width:80%; align-items:center;">
    </formio>`
In the attached screenshot, two console are logged, with **isValid** property true in both the logs, where as the form was not valid.
![Screenshot from 2021-02-16 15-08-13](https://user-images.githubusercontent.com/13505029/108044919-db1db900-7068-11eb-8025-2673cc793eb3.png)

**Comment by wag110894** [comment]
Hello @abhishek0196,


Thank you for your interest in Form.io!

In the future, please submit your questions to Gitter( located here: https://gitter.im/formio/formio) for our community support.  We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. If you are interested in learning more about our Support Packages, then please contact support@form.io.

Thank you and have a great day!

**Comment by weilies** [comment]
u mind share with us the rate? i am looking for a custom submit button too :) instead of submit the data to form.io, my use case need me only submit to my own cloud. we probably can share the cost with the community to get the custom submit function 👍

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
