### ISSUE TITLE
[Question] Customizing or translating "EditGrid header template

### ISSUE THREAD

**Issue by dev-thinks** [formio/angular#723]
Hello,

Is there a way to translating the header template content (component.label) in edit grid.

`<div class="row">
      {% util.eachComponent(components, function(component) { %}
        {% if (!component.hasOwnProperty('tableView') || component.tableView) { %}
          <div class="col-sm-2">{{ component.label }}</div>
        {% } %}
      {% }) %}
    </div>`

This is the default header template am seeing. but label text is not passed through translate function. 

1. is there a way to call translate from here?
2. or is there an option to access array of components from this template "src/templates/bootstrap3/editgrid/html.ejs"; so that i can customize the editgrid template

@travist Any insights into this really helpful, Thank you.

**Comment by aleksf0** [comment]
This has probably been already fixed... Looking at [header.ejs](https://github.com/formio/formio.js/blob/master/src/components/editgrid/templates/header.ejs) I can see the following default header template, which translates the header properly for me:
`
<div class="row">
  {% ctx.util.eachComponent(ctx.components, function(component) { %}
    {% if (!component.hasOwnProperty('tableView') || component.tableView) { %}
      <div class="col-sm-2">{{ ctx.t(component.label) }}</div>
    {% } %}
  {% }) %}
</div>
`

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
