### ISSUE TITLE
[Custom Components] Custom Accordion Component Drop Zone

### ISSUE THREAD

**Issue by mehdi47** [formio/angular#725]
Hi,

In my angular application, i added an accordion component, to which i'm trying to make it behave like a table component, where you can drag and drop other components inside, and as a result have a nested component.

i've tried working with ngx-dnd and make the accordion dropable but i can't drag & drop formio components inside.

So my issue, is this : how can i make a custom component ( whether it is an accordion or others in the future ) act as a droppable container for other components?

Thank you.

**Comment by wag110894** [comment]
Hello  @mehdi47 
Thank you for your interest in Form.io!
In the future, please submit your questions to Gitter( located here: https://gitter.im/formio/formio) for our community support.  We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions. If you are interested in learning more about our Support Packages, then please contact support@form.io.

Thank you and have a great day!

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
