### ISSUE TITLE
[Custom Components] - Render custom editor in formio form

### ISSUE THREAD

**Issue by pkarakal** [formio/angular#726]
I have created a custom editor based on CKEditor 5, and I am trying to use it as a custom element in a form. 
I have created the class that implements the FormioCustomComponent interface and have added the logic in my component. The problem is that the component isn't rendered in the form. The component is in a library packaged with ng-packagr and then imported in an angular project. I am registering the custom component in the angular client project inside the app.module so that it is accessible by any module and component in the application. I noticed that neither the constructor nor the ngOnInit lifecycle hooks are being invoked so it is like formio completely ignores it.

```typescript
export const COMPONENT_OPTIONS: FormioCustomComponentInfo = {
  type: 'editor',
  selector: 'editor',
  title: 'Editor',
  group: 'basic',
  icon: 'font',
  weight: 500
}

@Component({
  selector: 'editor',
  templateUrl: './editor.component.html',
  encapsulation: ViewEncapsulation.None
})
export class Editor implements FormioCustomComponent<string>{
  public ckeditor;
  private _value: string;
  @Output() valueChange = new EventEmitter<string>();
  @Input() disabled: boolean = false;
  @ViewChild( 'editor' ) editorComponent: EditorComponent;
  @Input()
  public set value(v: string) {
    this._value = v;
  }
  public get value(): string {
    return this._value;
  }

  constructor() {
    this.ckeditor = Editor;
  }
  updateValue(payload: string) {
    this.value = payload;
    this.valueChange.emit(payload); 
  }
}
```

Note: When using the component outside of Form.io, the component is rendered correctly.

### Framework/Library Versions
*  Angular: 6.2.9
*  formio/angular: 4.11.2 
*  formio.js: 4.12.7

**Comment by wag110894** [comment]
Hello @pkarakal 

Thank you for your interest in Form.io!

In the future, please submit your questions to Gitter( located here: https://gitter.im/formio/formio) for our community support. We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period. We will assign one of our senior developers to work directly with you in online sessions. If you are interested in learning more about our Support Packages, then please contact support@form.io.

Thank you and have a great day!

**Comment by Sidiro23** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
