### ISSUE TITLE
[Question] changing input value programmatically 

### ISSUE THREAD

**Issue by mohamedmahmoudf97** [formio/angular#731]
formComponents[0] = {
      "label": "Agent Name ",
      "tableView": true,
      "key": "agentName",
      "type": "textfield",
      "input": true,
      "defaultValue":"moahmed mahdmoj"
  };

      this.triggerRefresh.emit({
        form:{components:formComponents} 
      });

**Comment by travist** [comment]
You should use the Form SDK to do this.

```js
form.getComponent('firstName').setValue('Travis');
```

**Comment by mohamedmahmoudf97** [comment]
> You should use the Form SDK to do this.
> 
> ```js
> form.getComponent('firstName').setValue('Travis');
> ```

thank you but how can i use getComponent method in angular 8

**Comment by MaxPrimeAERY** [comment]
Same question @travist

**Comment by ZenMasterJacob20011** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
