### ISSUE TITLE
[Question] How to display youtube video 

### ISSUE THREAD

**Issue by upfounders** [formio/angular#733]
How to display youtube in the form as instruction, I tried to add iframe code block through Html Element,
<img width="642" alt="Screen Shot 2021-03-04 at 10 50 05 AM" src="https://user-images.githubusercontent.com/59995322/110014263-6f2d8880-7cd7-11eb-8e1e-77374efb0085.png">

but it doesn't display anything

**Comment by travist** [comment]
iframes are not supported. You will need to add an exception to the "domsanitize" to allow irames to be rendered.

This thread talks about how to do that. https://github.com/formio/formio.js/issues/2273

**Comment by upfounders** [comment]
this is very helpful @travist travist! I am not able to add youtube video from the Rich text editor in the Content?  is it a known issue?

**Comment by ccontour** [comment]
I am able to insert videos into Content components, what is happening when you try? It's possible CORS is blocking the player for you

**Comment by upfounders** [comment]
Possible, when I insert the youtube video, it is showing up in the editor, but when I save it, it shows blank in the form.

<img width="871" alt="Screen Shot 2021-03-09 at 7 11 08 AM" src="https://user-images.githubusercontent.com/59995322/110492227-d87e1480-80a6-11eb-8415-44429d6aee3d.png">

**Comment by ccontour** [comment]
Can you reload that page, and include a screenshot of the `Network` tab with it open from the start of the page load? Red lines are the ones that are failing

**Comment by upfounders** [comment]
you are right, I got the CORS issue, how should I fix it? thanks! 
<img width="1433" alt="Screen Shot 2021-03-09 at 2 54 20 PM" src="https://user-images.githubusercontent.com/59995322/110549798-7265b180-80e7-11eb-84d0-b9c9e1a7e092.png">

**Comment by travist** [comment]
CORS is a common thing that needs to be enabled within your server. Try this.

https://expressjs.com/en/resources/middleware/cors.html
