### ISSUE TITLE
Concat is not working in Angular Form | JavaScript/JSON Logic [Question] 

### ISSUE THREAD

**Issue by Kadhiresan-K** [formio/angular#739]
Hi All,

I want to Concat two different user inputs text/number fields and display them in the third text box which is in read-only format. please check the attached image below,

![Screenshot 2021-03-15 at 7 01 52 PM](https://user-images.githubusercontent.com/70190306/111162059-c7129c00-85c1-11eb-9b69-1f851c6b41d7.png)
![Screenshot 2021-03-15 at 7 09 00 PM](https://user-images.githubusercontent.com/70190306/111162197-f2958680-85c1-11eb-9d47-fa45d08631c4.png)

But value is not displaying in the UI, but when submitting the form I am able to get it.
**What's the way to make it visible in the UI?**
Thanks in advance.

**Comment by travist** [comment]
This may be a problem with "refresh" not updating. Try setting the "Refresh On" configuration so that this calculated value will refresh when the value of number changes.

**Comment by Kadhiresan-K** [comment]
Hi @travist 

thanks for the input,

I am not able to find the "Refresh On" configuration But I have set the "Redraw On" as _Any changes_ still no luck.

![Screenshot 2021-03-15 at 7 55 08 PM](https://user-images.githubusercontent.com/70190306/111169129-b285d200-85c8-11eb-83b1-bae4fc5cb4e5.png)

please let me know, is there is any other config that can help us.

**Comment by Kadhiresan-K** [comment]
Hi @travist 

It's working.

We are able to get the result using **Calculated Value** option.a
