### ISSUE TITLE
Using Angular 11 to create a formio-wizard

### ISSUE THREAD

**Issue by cbc872** [formio/angular#740]
Hi there, I am using Angular 11 and new to Formio.  I would like to create a "formio-wizard". I have only found one example using AngularJS (https://formio.github.io/formio-wizard) . Are there any other examples or documentation to show you how to do this? Thanks!

If I set the form type to wizard, it displays the wizard tabs - how do I change them into steps (with bubbles) like the example?

**Comment by travist** [comment]
We have a ticket to convert our latest renderer (which this library includes) to have several wizard headers types and we will bring back this "bubble" wizard header. This is still on our to-do list, though so it will come soon.
