### ISSUE TITLE
How to extend basic edit form for my custom component?

### ISSUE THREAD

**Issue by TimurAztec** [formio/angular#749]
I want to have my own custom edit form for my component as it show in example here
https://github.com/formio/angular/wiki/Custom-Components-with-Angular-Elements
with minimalEditForm(), but I want to change only few fields different from basic edit form.

**Comment by mikekotikov** [comment]
@TimurAztec the default edit form for custom components is the Text Field component one.
There are two ways for you to change it: 
1) Go to [formio.js repo](https://github.com/formio/formio.js) and navigate to src/components/textfield.
You'll see `editForm` folder with files that have sets of components used in edit form and `TextField.form.js` file that combines them. You may take them, modify for your needs and use in your application.
2) In your application you may direct import textfield (or any other component) edit form and change it in `static editForm()` method of your component. Here is an [example](https://gist.github.com/mikekotikov/6aaeb875a16e63e4ea17b68d532288e6) on how you may do this.
