### ISSUE TITLE
[Question] Where can I find all options of FormioOptions interface?

### ISSUE THREAD

**Issue by ponich** [formio/angular#751]
Now we have the interface `FormioOptions`

```typescript
export interface FormioOptions {
    errors?: ErrorsOptions;
    alerts?: AlertsOptions;
    alertsPosition?: AlertsPosition;
    disableAlerts?: boolean;
    i18n?: object;
    fileService?: object;
    hooks?: FormioHookOptions;
    sanitizeConfig?: any;
}
```

But on [Custom Form Builder documentation](https://formio.github.io/formio.js/app/examples/custombuilder.html) we can see extra options for form. As result `FormioOptions` doesn't have all properties.

**Comment by ccontour** [comment]
There isn't a formal definition beyond that. However, this may help you find an answer

https://github.com/formio/formio.js/blob/master/src/Form.js#L10
https://github.com/formio/formio.js/blob/master/src/Element.js#L19
