### ISSUE TITLE
[BUG] Can't see youtube videos that get added via the Ckeditor content embed functionality

### ISSUE THREAD

**Issue by moda20** [formio/angular#752]
## Environment
I am trying to add youtube videos to my form using the custom component and via the embed functionality of the ckEditor it is using. 
The issue is that the video, when I the editor, show up correctly with the preview picture but when saving it, the video doesn't show up on the rendered version of the form. 
I am doing this on the  demo page of formio for angular : https://formio.github.io/angular-demo/#/forms/builder
in the network tab of the dev tools I can see that a youtube request : `https://www.youtube.com/embed/......` is being sent but canceled while a second one (GET request to the same link) is sent and returns with 200 status but no response data is shown.

after this my video doesn't show up in the rendered version and a blank space taken by the video dimensions is what shows. 

here is my JSON form code : 

```
{
    "components": [
        {
            "html": "<figure class=\"media\"><div data-oembed-url=\"https://www.youtube.com/watch?v=l3daDnnz-2o\"><div style=\"position: relative; padding-bottom: 100%; height: 0; padding-bottom: 56.2493%;\"><iframe src=\"https://www.youtube.com/embed/l3daDnnz-2o\" style=\"position: absolute; width: 100%; height: 100%; top: 0; left: 0;\" frameborder=\"0\" allow=\"autoplay; encrypted-media\" allowfullscreen=\"\"></iframe></div></div></figure>",
            "label": "Content",
            "refreshOnChange": false,
            "key": "content",
            "type": "content",
            "input": false,
            "tableView": false
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}
```

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
