### ISSUE TITLE
[BUG] wron CSS in when trying to add form elements 

### ISSUE THREAD

**Issue by moda20** [formio/angular#753]
I am having a problem with the text on some panels not having the correct color ( white on white )
here is a screenshot of the issue, I can't override the CSS directly from my component `.scss` file as that is not taken into consideration by the `formBuilder` component.

![Screenshot 2021-03-31 at 14 37 46](https://user-images.githubusercontent.com/23613485/113154318-d20b3480-922f-11eb-88fa-e7f1e64bf859.png)

**Comment by AlexeyDavyd** [comment]
@moda20 Could you please provide consistent steps to reproduce?
