### ISSUE TITLE
[Question] replace ng-show in Item Template with *ngIf not working

### ISSUE THREAD

**Issue by blackbaud-RickSchnitzler** [formio/angular#755]
We have gone from "ng-formio": "2.19.6" and "ng-formio-builder": "2.19.4" to "angular-formio": "4.9.6"and "formiojs": "4.11.3" for our Angular9 SPA.
The Item Template for ChoicesJS looks like this.
```
<div>
  <div style="font-weight: bold">
    {{ item.Name }}
  </div>
</div>

<div class="search-recipient">
  <div ng-show="item.CanadianCharityNumber">Canadian Charity Number:  {{ item.CanadianCharityNumber }}</div>
  <div>{{ item.Address }}</div>
</div>
```
We've tried replacing ng-show with *ngIf and with [hidden] with no success. We have also tried changing Widget Type to HTML 5 and other properties. Tried scss solutions also to no avail.
Inspecting the ng-form version, I've noticed that class=".ng-hide" was added to the div by ng-formio I believe when there should not show.

We want the rows to be hidden if there is no data. Anyone have a solution?

**Comment by wag110894** [comment]
Hello @blackbaud-RickSchnitzler, are you still able to replicate this issue on your side? If so, can you try testing against the latest version of Angular (5.2.2)?

Thank you.

**Comment by blackbaud-RickSchnitzler** [comment]
Yes. I just updated from angular-formio:4.12.0 to @formio/angular 5.2.2 and formiojs:4.14.0 to formiojs:4.14.3.
I now see 
  Canadian Charity Number: null
I haven't tried anything but the ng-show and haven't tried other.
Inspecting shows.
<div>Canadian Charity Number:  null</div>
