### ISSUE TITLE
[Question] What's the difference between the @formio/angular and angular-formio packages

### ISSUE THREAD

**Issue by david-bulte** [formio/angular#757]
Here it says that I have to install @formio/angular: https://github.com/formio/angular

But here it says to install angular-formio: https://github.com/formio/angular/wiki

(note: I need to use custom components with angular elements)

**Comment by AlexeyDavyd** [comment]
That's basically the same library. We have just changed namespace. But haven't changed wiki info yet. Fell free to go with @formio/angular.
