### ISSUE TITLE
[BUG] : unable to resolve dependency tree

### ISSUE THREAD

**Issue by sharmav007** [formio/angular#758]
The npm install of formio angular failing for new app with dependency errors.

1. Create a new angular app and tried npm install --save @formio/angular formiojs

Observed behavior - npm install failing with below error.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: Formio-demo-app@0.0.0
npm ERR! Found: @angular/core@11.0.9
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~11.0.5" from the root project
npm ERR!   peer @angular/core@"^9.0.0 || ^10.0.0 || ^11.0.0" from @formio/angular@5.1.0
npm ERR!   node_modules/@formio/angular
npm ERR!     @formio/angular@"*" from the root project
npm ERR!   1 more (@angular/common)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"11.2.9" from @angular/elements@11.2.9
npm ERR! node_modules/@angular/elements
npm ERR!   peer @angular/elements@"^9.0.0 || ^10.0.0 || ^11.0.0" from @formio/angular@5.1.0
npm ERR!   node_modules/@formio/angular
npm ERR!     @formio/angular@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Even tried install --save --legacy-peer-deps  @formio/angular formiojs, it fails with below error
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/formio/Choices.git
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:

**Comment by sharmav007** [comment]
I had Nodev15.13.0 and CLI v11.2.8 installed, downgraded to below to get it working.

Angular CLI: 11.0.7
Node: 14.16.1
OS: win32 x64
Angular: 11.0.9

**Comment by miguel-coppiloto** [comment]
Same problem. Downgrading to node 14.17.3 compile without problem.

Angular CLI: 14.1.0
Node: 14.17.3
Package Manager: npm 6.14.13 
OS: darwin x64
