### ISSUE TITLE
[Custom Components] Need to reload to show custom components

### ISSUE THREAD

**Issue by StefanRupertsberger** [formio/angular#759]
I created two custom components using the guide in the wiki.
My problem is that the components do not render when first dropping them into the builder. After a reload of the page it works as expected.
There are no error thrown or anything like that.

**Comment by hbaldwinRPT** [comment]
I'm having this same issue, and just beginning to look into it. do you happen to be using another framework? For example my project is using ionic/capacitor on top of angular. Have you been able to make any progress in this?

**Comment by StefanRupertsberger** [comment]
No just angular. I observed that some people have similar problem when using lazy loaded modules.

**Comment by wag110894** [comment]
Hello @StefanRupertsberger, are you still experiencing this issue? If so, then can you try upgrading to Angular 5.2.2?

Thank you.
