### ISSUE TITLE
can we move the left side component fields options to right side by passing options

### ISSUE THREAD

**Issue by b09h** [formio/angular#763]
![image](https://user-images.githubusercontent.com/60179972/116204147-14099680-a75a-11eb-833d-398ef8d2d108.png)

**Comment by edwinanciani** [comment]
Hi @BhanuPrakashReddyT yes you can move it just changing the Builder Template . https://github.com/formio/formio.js/blob/master/src/templates/bootstrap/builder/form.ejs
