### ISSUE TITLE
[Question] - Remove item on file component

### ISSUE THREAD

**Issue by jftsaraiva** [formio/angular#784]
In `File` component what's the best practice to delete a file that was uploaded to storage (URL):

![image](https://user-images.githubusercontent.com/2278476/123827642-b419a280-d8f8-11eb-82ee-8270c74581ff.png)

this removes it only on UI, but keeps the file in storage. 

How to configure endpoint for `DELETE` verb? 

If we use form renderer's `change` event, we can verify if `type` of component is `file`, but how to verify which file was deleted?  We need to implement this in our component / service or we can get this from event data?

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
