### ISSUE TITLE
[Help] File Upload Error

### ISSUE THREAD

**Issue by sudurrani** [formio/angular#786]
I have added File upload component with below schema
![image](https://user-images.githubusercontent.com/14028940/124240135-e2cf8d00-db33-11eb-9729-30cb4082720f.png)

Can not read property '0' of null - error is raised and page does not  load
![image](https://user-images.githubusercontent.com/14028940/124240832-959feb00-db34-11eb-9778-08727e507ec2.png)

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
