### ISSUE TITLE
[Question] rendering performance - optimal way to set/change/update only server changed parts of submission

### ISSUE THREAD

**Issue by therabreal** [formio/angular#790]
Hi,

We are dealing with large forms many components.
Currently we set the submission for the complete form after each change/server interaction.
This is starting to cause rendering performance issues for us.

Is there a way to update only part of the submission?
So if the server only returns changed data - I would effectively like to merge this data with what is already in the form.

I could merge the existing submission with the changeset and then update the form but I guess this would "render" the data for entire form again?

Thanks in advance for any hints!
RAB

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
