### ISSUE TITLE
Adding a data grid within a existing form

### ISSUE THREAD

**Issue by Mkaith** [formio/angular#792]
Hi,
My use case is that i have a parent form and a contacts form. When i press addcontact button a pop up is opened and contact form is rendered within it. Once i have filled that form is there any way to dynamically show that info above the addcontact button in the form of grid. 

Also if i perform some actions through custom events then my form is again rendered and i need to fill that all again. Is there any way to retain all those values. 

Thanks
![Capture](https://user-images.githubusercontent.com/47468681/127112046-c2f7ddd1-72d4-4504-b446-0c1f61b38f63.PNG)

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
