### ISSUE TITLE
[Question] angular/formio render options errors

### ISSUE THREAD

**Issue by dnmosca** [formio/angular#793]
Hi,
a simple question:
under what conditions formio render options errors is triggered ?

<formio [form]='myForm' [options]="options"  ... > </formio>

options = {
        alerts: {'submitMessage': ''},
        errors: {'message': ''},
        i18n: {language: 'it',
        ...         
}

Thanks in advance

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
