### ISSUE TITLE
[Custom Components] Form Rendering issues

### ISSUE THREAD

**Issue by Mkaith** [formio/angular#796]
Hi team,
I have successfully captured the value and the array is stored in db but when i try to get the submission, my appropriate selection is not selected. For Ex:-
While Submitting :-
![image](https://user-images.githubusercontent.com/47468681/128598174-e1225be5-41ac-4968-8a2d-04220c4a0792.png)

![image](https://user-images.githubusercontent.com/47468681/128598182-cab32e96-072e-4da7-af37-148ce501ef57.png)

Data Retried while rendering:-
![image](https://user-images.githubusercontent.com/47468681/128598194-c240f78b-68af-4cf7-b776-59f6eca7ace0.png)

Rendered Output:-
![image](https://user-images.githubusercontent.com/47468681/128598202-83a35fbf-5de2-4256-92c8-0bace486060e.png)

Thanks in advance.

**Comment by wag110894** [comment]
Hello @Mkaith, can you provide your form json?

**Comment by Mkaith** [comment]
Here is the Json of form @wag110894 
{
    "components": [
        {
            "label": "Weekdays",
            "optionsLabelPosition": "right",
            "inline": false,
            "tableView": false,
            "validate": {
                "onlyAvailableItems": false
            },
            "key": "dfgh",
            "type": "weekdaypicker",
            "input": true
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}

I have found the reason why it cant be rendered :- 

1. We are making a custom component with some checkboxes(Weekdays).
2. We capture there selection through some functions and populate an array.
3. Pass this array to valuechange event which update the submission data.
4. This flow is correct.
5. But when we try to populate the form through submission it fails as it require a key but we havent provided any key to it and we even cant provide that in this way.
6. I further debugged the check matrix example and found that submission flow was broken there also. There even on submitting the form the data is not captured.
7. I am now trying with the default values.
8. But pls help if you have any ideas how to do it.

Thanks

**Comment by wag110894** [comment]
Have you taken a look at https://formio.github.io/formio.js/app/examples/customcomponent.html or https://github.com/formio/angular/wiki/Custom-Components-with-Angular-Elements?

**Comment by Mkaith** [comment]
@wag110894 I have read both these documentations and came to such conclusion.

I have thought of a other way round to make a table and drag check box components to each column to represent weekdays. But I still need help on submission flow I.e. to render the submitted form.

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
