### ISSUE TITLE
[Custom Components]  Button Custom Events

### ISSUE THREAD

**Issue by Radamanthys0** [formio/angular#798]
Hi team,
I had followed suceffuly the  tutorial https://github.com/formio/angular/wiki/Custom-Components-with-Angular-Elements 
and created an Angular custom component for formio. But I came with some adversity.

I'd like to know if it is possible to listen to a formio  button custom event within this Custom Component I've created

For an exaple, if I create this button with this event custom test:
![image](https://user-images.githubusercontent.com/11777478/129100301-14031456-6dff-497b-8b1f-9ce5d983c511.png)

Can I listen this "test" inside  my new component?
I've tried use angular's @Hostlistener, but it didn't work.

**Comment by thienmohr** [comment]
any update?

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
