### ISSUE TITLE
[Question] How to edit the dialog HTML ?

### ISSUE THREAD

**Issue by Samanoova** [formio/angular#800]
Hi 
Is there any way to edit the dialog HTML that generates when I dropped an input into a form builder? 

![Capture](https://user-images.githubusercontent.com/38281155/129710442-8547f547-94b0-47ea-8712-bffdecf13937.JPG)

for example, I want to append an icon to the default value block and wrap them into a new div to feel free when I add my styles to the new block that I want to create.
 and I want to make this new icon exist with every default value input when there are multiple values and I want to add a click event that will show a new popup to give the user some choices.
is that's possible?

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
