### ISSUE TITLE
How to ignore the labelPosition while having a default value of left-left for custom component using editForm [Question] 

### ISSUE THREAD

**Issue by shalin2000** [formio/angular#802]
Hey everyone, I am having trouble trying to achieve ignoring label position dropdown so that it doesn't show in the modal of the component but I want it to apply the "left-left" value from the dropdown to the components label. Is there a way of achieving that?

```
editForm: {
    textfield: [
      {
        key: 'display',
        ignore: false,
        components: [
          {
            key: 'labelPosition',
            ignore: true
          }
        ]
      }
    ]
}
```

So with the code above, I am able to hide the label position dropdown from the modal but how can I hide the dropdown but also have it apply the 'left-left' property?

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
