### ISSUE TITLE
[BUG] The number component's preview panel does not show correct default value when user delete it

### ISSUE THREAD

**Issue by lHilovsky** [formio/angular#803]
## Environment
- Formio.js version: 4.13.5
- Frontend framework: Angular 
- Browser: Chrome

# First issue
## Steps to Reproduce
1. Write some number into default value 
2. Delete digits one by one

## Expected behavior
Default value should be empty
## Observed behavior
First digit is still shown in preview panel
## Example

https://user-images.githubusercontent.com/56341727/131491296-30e65888-7c01-40ee-b37f-ff79f26a5e2f.mp4

# Second issue
## Steps to Reproduce
1. Write some number into default value 
2. Delete all digits at once

## Expected behavior
Default value should be empty
## Observed behavior
All digits are still shown in preview panel
## Example
https://user-images.githubusercontent.com/56341727/131491704-ebce2eaa-0856-49a8-b03e-5147d633c1d3.mp4

# Third issue
## Steps to Reproduce
1. Write some number into default value 
2. Delete digits by pressing the backspace button constantly

## Expected behavior
Default value should be empty
## Observed behavior
All digits except last are still shown in preview panel
## Example
https://user-images.githubusercontent.com/56341727/131492059-9e5d8c28-e2c8-4a59-8d5e-777da381baf3.mp4

**Comment by jeriah-formio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
