### ISSUE TITLE
[BUG] Formio autocomplete option in form builder not working

### ISSUE THREAD

**Issue by swapnil147** [formio/angular#808]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Form.io official demo page
- Browser: Chrome
- Browser version: 92.0.4515.159

## Steps to Reproduce
Go to the official demo page https://formio.github.io/angular-demo/#/forms/builder
1. Create Name field with type textfield and autocomplete as off
2. Create Address field with type textfield  and autocomplete as off
3. Create a Phone number field with type number  and autocomplete as off

## Expected behavior
Autocomplete feature should be disabled and there should be no suggestions to autofill the fields
## Observed behavior
Autocomplete feature is still enabled and having suggestions to autofill the fields

![Autocomplete](https://user-images.githubusercontent.com/4358001/132887425-f2c1589a-1819-4cc1-924f-dba709797b87.PNG)

![image](https://user-images.githubusercontent.com/4358001/132887482-6a559494-051e-4e18-9034-651dad4b0b38.png)

## Example

For code or form JSON, please enclose in a code block:

```
{
    "components": [
        {
            "label": "Name",
            "autocomplete": "off",
            "tableView": true,
            "key": "name",
            "type": "textfield",
            "input": true
        },
        {
            "label": "Address",
            "autocomplete": "off",
            "tableView": true,
            "key": "address",
            "type": "textfield",
            "input": true
        },
        {
            "label": "Phone number",
            "autocomplete": "off",
            "mask": false,
            "spellcheck": true,
            "tableView": false,
            "delimiter": false,
            "requireDecimal": false,
            "inputFormat": "plain",
            "key": "phoneNumber",
            "type": "number",
            "input": true
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "input": true,
            "tableView": false
        }
    ]
}
```
Note: to replicate the issue you should have the information stored in the chrome browser.
Step1: Open chrome browser settings
Step2: Type Autofill and fill the details in Address and more.

Let me know if I am missing anything.

Thank you!!!

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
