### ISSUE TITLE
[BUG] Angular 12 form-builder template error

### ISSUE THREAD

**Issue by HaidarZ** [formio/angular#812]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Local deployment
    - Version: 5.2.0-rc.1

## Steps to Reproduce
1. Create an angular 12 based project
2. Add formio as a dependency 
3. Create a component with form-builder inside it and try to handle the change event
4. Project will not build

## Expected behavior
Successful build, nothing is done only declaring the components

## Observed behavior
Template error
```
 Object is possibly 'undefined'.
```

## Example

The component below will fail to compile
```html
<form-builder [form]="{components: _components}" (change)="onChange($event)"></form-builder>
```

While the one below will compile successfully when I add optional chain to the `change` to be `change?` event 
inside the template , which is weird and the editor goes crazy about this marking it as an error , but it passes the angular build
```html
<form-builder [form]="{components: _components}" (change?)="onChange($event)"></form-builder>
```

### How to solve this issue

As a solution, you can pass a bindign property name to the output decorator

```ts
export class FormBuilderComponent implements OnInit, OnChanges, OnDestroy {
  ...
  @Output('change') change?: EventEmitter<object>;
  ...
```

Shall I raise a pull request for that ?

### Note

The linter is complaining that we're using a preserved output name
```
...the output property "change" should not be named or renamed as a native event.
```

**Comment by webstik1811** [comment]
When I add `(change?)` instead of only `(change)` the build is possible, but this does not emit the function `onChange($event)`. So this does not fix the problem with correctly handling the changes made from FormBuilder.
So how to make this think to work with Angular 12 and to handle changes?

**Comment by IsmaelPro** [comment]
try alter the 'change?' for 'change!'

**Comment by dbtomy** [comment]
Any news on this topic? I got the same issue.

**Comment by ecvelayo** [comment]
any workarounds?

**Comment by enumahin** [comment]
Yes, I came across a workaround for this.

**Comment by ecvelayo** [comment]
Could you share it here @enumahin ?

**Comment by enumahin** [comment]
#### Component
  @ViewChild('json') jsonElement?: ElementRef | any;
  @ViewChild('formio') formio:any;
  public form: any = {
    components: [

    ]
  };

  constructor() {
  }


  ngOnInit(): void {

  }

  saveForm(){
    this.jsonElement.nativeElement.innerHTML = '';
    this.jsonElement.nativeElement.appendChild(document.createTextNode(JSON.stringify(this.formio.form, null, 4)));

    const json = document.createTextNode(JSON.stringify(this.formio.form, null, 4));
  }

### HTML
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <form-builder style="color: #000; background-color: #0d101b" [form]="form" #formio></form-builder>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-10 offset-sm-2">
      <button (click)="saveForm()" class="btn btn-primary">Save Form</button>
    </div>
  </div>
  <div class="well jsonviewer">
    <pre id="json"><code class="language-json" #json></code></pre>
  </div>
</div>

**Comment by enumahin** [comment]
#### Component
  @ViewChild('json') jsonElement?: ElementRef | any;
  @ViewChild('formio') formio:any;
  public form: any = {
    components: [

    ]
  };

  constructor() {
  }


  ngOnInit(): void {

  }

  saveForm(){
    this.jsonElement.nativeElement.innerHTML = '';
    this.jsonElement.nativeElement.appendChild(document.createTextNode(JSON.stringify(this.formio.form, null, 4)));

    const json = document.createTextNode(JSON.stringify(this.formio.form, null, 4));
  }

### HTML
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <form-builder style="color: #000; background-color: #0d101b" [form]="form" #formio></form-builder>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-10 offset-sm-2">
      <button (click)="saveForm()" class="btn btn-primary">Save Form</button>
    </div>
  </div>
  <div class="well jsonviewer">
    <pre id="json"><code class="language-json" #json></code></pre>
  </div>
</div>

**Comment by enumahin** [comment]
HTML

`<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <form-builder style="color: #000; background-color: #0d101b" [form]="form" #formio></form-builder>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-10 offset-sm-2">
      <button (click)="saveForm()" class="btn btn-primary">Save Form</button>
    </div>
  </div>
  <div class="well jsonviewer">
    <pre id="json"><code class="language-json" #json></code></pre>
  </div>
</div>`

**Comment by HannaKurban** [comment]
The issue has been fixed

**Comment by dinbtechit** [comment]
Looks like at some point of time angular introduced strictTemplate

I had to set `tsconfig.json` -> `angularCompilerOptions` -> `strictTemplates: false`:

`tsconfig.json`:

```json
. . .
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": false   // <-------<<< change true to false
  }
. . .
}
```
