### ISSUE TITLE
[Question] 'undefined' Output on FormBuilder component

### ISSUE THREAD

**Issue by AurelienColas-Fr** [formio/angular#848]
Is that normal that the output **(change)** from the FormBuilderComponent can be 'undefined'?
If I try to build my angular project with the strict compilation mode of typescript, I get the compilation error below.

![Capture](https://user-images.githubusercontent.com/83823766/149100543-b4e82f63-b02a-41a8-9814-650a8a0b2d7f.PNG)

My versions are :
"@angular": "13.1.2"
"typescript": "4.5.4"
"@formio/angular": "5.2.2"
"formiojs": "4.13.11"

I don't understand why an output could be undefined. This output never seems to be undefined, is it an error on the type declaration ?

**Comment by fedesnieg** [comment]
Any workarounds?

**Comment by ecvelayo** [comment]
any workarounds?

**Comment by HannaKurban** [comment]
The fixes have been merged
