### ISSUE TITLE
How to manually trigger value change in edit form of form builder

### ISSUE THREAD

**Issue by HTMLProgrammer2001** [formio/angular#855]
Hi, i am using angular form builder for my app and i need change value of edit form in modal dialog dynamically. How can i do this?

![image](https://user-images.githubusercontent.com/55248791/152539054-53a94aa2-62c9-4fa3-b1bd-e5130b98d36e.png)

For example i want call some function `editFormUpdateValue({label: 'test'})` and after this value of "Label" in form and preview will be changed to "test"

**Comment by henriquesoareslima** [comment]
Hi @HTMLProgrammer2001, do you know how call some function editFormUpdateValue and refresh preview??
