### ISSUE TITLE
Current NPM version

### ISSUE THREAD

**Issue by sefini** [formio/angular#861]
hi,

Is the npm version no longer updated?  I see 4.11.5 on [NPM](https://www.npmjs.com/package/angular-formio).  But see v5.2.2 on the [github tag page](https://github.com/formio/angular/tags).

thank you.

**Comment by michealharrington** [comment]
This is the NPM I use: 
https://www.npmjs.com/package/@formio/angular

**Comment by surajpulloor** [comment]
This npm package doesn't work with latest angular version - Angular 15. There is a dependency conflict
I think the npm package needs to be updated with the latest build

**Comment by lane-formio** [comment]
For use with formiojs@4.x
@formio/angular@7.0.0 supports Angular 17
@formio/angular@6.0.0 supports Angular 16

formiojs@5.x is still in development, but is intended to be compatible with @formio/angular 7.5.0 and 6.5.0
