### ISSUE TITLE
Is it possible to trigger an event when a form field value in formio form changes?

### ISSUE THREAD

**Issue by paulmartinjoy** [formio/angular#874]
### Discussed in https://github.com/formio/angular/discussions/873

<div type='discussions-op-text'>

<sup>Originally posted by **paulmartinjoy** April  7, 2022</sup>
I am using formio angular to render a simple form. The form has a birthday field and when initialized, it has a default value and if it is changed, is it possible to emit an event if the default value has been changed once the focus changes ?</div>

**Comment by travist** [comment]
You need to first get the "formio" instance from the angular component like seen here.

https://gist.github.com/travist/e639060968a6ec984b38a49c3753043f

And then add the following.

```
formio.on('change', (changed) => {
   console.log(changed);
});
```
