### ISSUE TITLE
[BUG] No projects support the 'serve' target

### ISSUE THREAD

**Issue by malcolmswaine** [formio/angular#886]
## No projects support the 'serve' target.
Please provide as many details as you can:

Angular CLI: 13.2.4
Node: 16.15.1
Package Manager: npm 8.11.0
OS: win32 x64

Angular: 13.2.3
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.4
@angular-devkit/build-angular   13.2.4
@angular-devkit/core            13.2.4
@angular-devkit/schematics      13.2.4
@angular/cli                    13.2.4
@schematics/angular             13.2.4
ng-packagr                      13.2.1
rxjs                            7.5.4
typescript                      4.4.4

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 5.3.0-rc.2
- Formio.js version: 
- Frontend framework: Angular
- Browser: Chrome
- Browser version:

## Steps to Reproduce
1. C:\Projects\Seimens\Spikes\FormBuilder.io>git clone https://github.com/formio/angular.git .
2. C:\Projects\Seimens\Spikes\FormBuilder.io>npm install
3. C:\Projects\Seimens\Spikes\FormBuilder.io>ng version (posted above)
4. C:\Projects\Seimens\Spikes\FormBuilder.io>ng serve

## Expected behavior
The app is launched

## Observed behavior
Error on command line
No projects support the 'serve' target.

![image](https://user-images.githubusercontent.com/15143991/174498851-bd6d9ad0-0b6f-4283-bb48-a9870048513b.png)

**Comment by nerd00f** [comment]
Are you using the most recent angular cli version?

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
