### ISSUE TITLE
[BUG] File component, drop or browse space dissapear when error alert is shown

### ISSUE THREAD

**Issue by javierel7** [formio/angular#900]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version:
- Formio.js version: 5.2.2
- Frontend framework: Angular 13.3.6
- Browser: Chrome / Mozilla Firefox
- Browser version: any

## Steps to Reproduce
1. Use a File component in any form on Formio Builder
2. Capture file size limit and extension application/pdf (per example)
3. Load the form in your Angular project
4. Drag a file that trigger the File size too big error alert
5. Clic on X to remove the file
6. The row-space to drop or browse file dissapear and not allows to select other file.
Its possible to reproduce faster in https://formio.github.io/angular-demo/#/forms/builder , just add a file component and put a file size limit or pattern (application/pdf) 
 
## Expected behavior
That the drop files or browse row didnt dissapear when i remove the file selected (only when error alert is displayed) 
## Observed behavior
The space to drop or browse file dissapear when i clic on "X" to remove a selected file that doesn't apply the size or extension pattern.
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

![image](https://user-images.githubusercontent.com/111383567/184948531-a970602c-3db3-4bd9-ad8f-4510575a8c76.png)

**Comment by wag110894** [comment]
Hello @javierel7, We are aware of this issue and are currently working on fixing this.
Ticket Number is FIO-4603. We will let you know once this is released.

**Comment by javierel7** [comment]
Fixed version released! Thnx
