### ISSUE TITLE
[BUG] Data table column sorting is broken

### ISSUE THREAD

**Issue by Mimisss** [formio/angular#914]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version: 4.12.4
- Frontend framework: Angular 11.0.5
- Browser: Chrome 
- Browser version: 106.0.5249.119 (Official Build) (64-bit)

## Steps to Reproduce
1. Navigate to http://localhost:4200/#/data
2. Click on a column header; sorting works
3. Click on another column header; sorting stop working for all columns

## Expected behavior
Sorting should be working for all columns. Also, sorting icons should appear.

## Observed behavior
Sorting stops working when another column is clicked.

The bug is in the `sortColumn` function of the `FormioGridComponent` class. When all other column sorts are reset:

`col.sort = '';`

instead of 

`col.sort = undefined;`

```js
  sortColumn(header: GridHeader) {
    // Reset all other column sorts.
    each(this.header.headers, (col: any) => {
      if (col.key !== header.key) {
        col.sort = '';
      }
    });
    switch (header.sort) {
      case 'asc':
        header.sort = SortType.DESC;
        this.query.sort = '-' + header.key;
        break;
      case 'desc':
        header.sort = undefined;
        delete this.query.sort;
        break;
      case undefined:
        header.sort = SortType.ASC;
        this.query.sort = header.key;
        break;
    }
    this.refreshGrid();
  }
```

**Comment by Mimisss** [comment]
The bug can be fixed by overriding the `sortColumn` function:

```
FormioGridComponent.prototype.sortColumn = function(header: any) {
  // Reset all other column sorts.
  this.header.headers.forEach(col => {
    if (col.key !== header.key) {
      col.sort = undefined;
    }
  });

  switch (header.sort) {
    case 'asc':
      header.sort = 'desc';
      this.query.sort = '-' + header.key;
      break;
    case 'desc':
      header.sort = undefined;
      delete this.query.sort;
      break;
    case undefined:
      header.sort = 'asc';
      this.query.sort = header.key;
      break;
  }
  this.refreshGrid();
}
```

The header template can by fixed to show sorting icons by replacing `glyphicons` with `font-awesome`:

```
<ng-template>
    <thead>
      <tr>
        <th *ngFor="let header of headers">                    
          <a (click)="sort.emit(header)">
            {{ header.label }}&nbsp;<i [ngClass]="{'fa-arrow-up': (header.sort === 'asc'), 'fa-arrow-down': (header.sort === 'desc')}" class="fa" *ngIf="header.sort"></i>
          </a>
        </th>
      </tr>
    </thead>
  </ng-template>
```

Hope it helps.

**Comment by lane-formio** [comment]
Thanks for the contribution @Mimisss 
Closing this issue as resolved.
