### ISSUE TITLE
[BUG] Readme walkthrough broken

### ISSUE THREAD

**Issue by Arlen22** [formio/angular#915]
## Environment

```plain
$ ng version
Angular CLI: 14.2.6
Node: 19.0.0 (Unsupported)
Package Manager: npm 8.19.2 
OS: linux x64

Angular: 14.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.6
@angular-devkit/build-angular   14.2.6
@angular-devkit/core            14.2.6
@angular-devkit/schematics      14.2.6
@angular/cli                    14.2.6
@schematics/angular             14.2.6
rxjs                            7.5.7
typescript                      4.7.4
```

## Steps to Reproduce
1. `ng new testProject` (with routing and css)
2. `cd testProject`
3. `npm install --save @formio/angular formiojs` (from the readme)

## Observed behavior
```plain
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test-project@0.0.0
npm ERR! Found: @angular/common@14.2.7
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0" from @formio/angular@5.3.0
npm ERR! node_modules/@formio/angular
npm ERR!   @formio/angular@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/user/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-10-25T22_24_12_640Z-debug-0.log
```
[2022-10-25T22_24_12_640Z-debug-0.log](https://github.com/formio/angular/files/9864421/2022-10-25T22_24_12_640Z-debug-0.log)

**Comment by Arlen22** [comment]
I was able to solve this by replacing the string `^14.1.0` with `14.2.7` and then setting the version for `ng-packagr` to `14.2.2`.

**Comment by Arlen22** [comment]
I ended up using primefaces instead. There were so many different quirks that I kept running into and then I found a guide on Angular.io for making dynamic forms, which worked a lot better.

**Comment by lane-formio** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
