### ISSUE TITLE
Angular 14 build error (ɵɵComponentDeclaration)

### ISSUE THREAD

**Issue by erviem99** [formio/angular#925]
## Environment

I'm trying to use formio/angular with my Angular 14 project but there is a build error.

Typescript version 4.6.2
Node.js v16.13.1

## Steps to Reproduce

npm install @formio/angular@5.5.0-rc.7

## Expected behavior

My project will build without any errors.

## Observed behavior

Error: node_modules/@formio/angular/components/alerts/formio.alerts.component.d.ts:10:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.  

10     static ɵcmp: i0.ɵɵComponentDeclaration<FormioAlertsComponent, "formio-alerts", never, { "alerts": "alerts"; }, { "focusComponent": "focusComponent"; }, never, never, false, never>;

**Comment by Arsalan-Javed** [comment]
facing same issue with @formio/angular@5.5.0-rc.7

**Comment by luigi198** [comment]
Facing same issue with @formio/angular@5.5.0-rc.7 - can't use form.io with angular 14 at all

**Comment by brendanbond** [comment]
Hi all, thanks for letting us know. We're investigating the cause here and will be back with more information as soon as possible.

**Comment by travist** [comment]
For Angular 14, you should be using @formio/angular@5.4.0-rc.2

**Comment by luigi198** [comment]
Hi @travist 
When I use @formio/angular@5.4.0-rc.2 with @angular/core@14.2.12, I get the following error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: eleven-operations@0.0.0
npm ERR! Found: zone.js@0.12.0
npm ERR! node_modules/zone.js
npm ERR!   zone.js@"~0.12.0" from the root project
npm ERR!   peer zone.js@"~0.11.4 || ~0.12.0" from @angular/core@14.2.12
npm ERR!   node_modules/@angular/core
npm ERR!     @angular/core@"14.2.12" from the root project
npm ERR!     peer @angular/core@"^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0" from @formio/angular@5.4.0-rc.2
npm ERR!     node_modules/@formio/angular
npm ERR!       @formio/angular@"5.4.0-rc.2" from the root project
npm ERR!     3 more (@angular/common, @angular/elements, ngx-bootstrap)
```
As said above, my angular version is 14.2.12, I will try to setup a demo for you to see, if you have any ideas in the mean time, let me know

**Comment by erviem99** [comment]
I can confirm that 5.4.0-rc.2 fixed the issue for me.

**Comment by luigi198** [comment]
I'm back, nevermind, it's working, it was my fault, my zone.js package was in version ~0.12.0, had to drop it to 0.11.4 and now it works.
For anyone coming here, version 5.4.0-rc.2 works with angular 14 and zone.js 0.11.4

**Comment by auroSymplr** [comment]
> For Angular 14, you should be using @formio/angular@5.4.0-rc.2

Thank you so much. After a half day of searching,came here and found it. Just a recommendation to Form.IO team. Please add the dependency and compactibility versions in the main page.
