### ISSUE TITLE
How to apply translations to Form Builder

### ISSUE THREAD

**Issue by hem1232** [formio/angular#929]
How to apply translations to Form Builder??

**Comment by ZenMasterJacob20011** [comment]
In order to have translations in the form builder, you need to pass in the i18n property to the form builder options. The schema would look like the following...
```
Formio.builder(document.getElementById("id to builder"), {}, {
i18n: {
    en: {
        "Text to translate": "Translated Text"
    }
}
})
```
Here is an example in jsfiddle: https://jsfiddle.net/ZENMASTER2001/024bcLxh/6/
