### ISSUE TITLE
how to add scroll to a formio data grid and give a width to a column

### ISSUE THREAD

**Issue by Jayanth-R** [formio/angular#933]
We are using formio data grid as the number of column increases grid is placed outside the view port and couldn't scroll
Is there a way to add scroll and give width to a column? Please find the attachment 
[![image]()](https://user-images.githubusercontent.com/57098749/212594406-49ee0617-f6cf-4efe-aac3-b2c2af4b4e1f.png)

As a work around for above issue tried to override the default css in style.css by placing grid in tabs
div.card-body.tab-pane.active > div:has(table){
    overflow-x: auto;
    overflow-y: hidden;
}

table  > tbody > tr>td>div{
    width: 16rem;
}

above workaround is causing other issue like couldn't see the values of drop down tried to z-index but couldn't achieve it
![image](https://user-images.githubusercontent.com/57098749/212595240-3613e1d2-58bb-4847-ba21-04986ad25234.png)

**Comment by lane-formio** [comment]
Can you share what versions you are experiencing this on?

**Comment by Tatsiana8** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
