### ISSUE TITLE
[Question] change commit layout when removing multiple components

### ISSUE THREAD

**Issue by adhonay** [formio/angular#937]
![Sem título](https://user-images.githubusercontent.com/14100568/216122138-da43e8ae-72bf-49bd-8265-26ababd28095.png)

How can I within an angular project change the layout and confirmation message when removing several components of the webformBuilder?

The implementation in formiojs looks like this. But it doesn't offer way to customize/stylize the confirmation box, or at least change the message.

![Capturar](https://user-images.githubusercontent.com/14100568/216327688-fb36565b-a12e-49ea-a132-520fb3b402f2.JPG)

**Comment by adhonay** [comment]
The implementation in formiojs looks like this. But it doesn't offer way to customize/stylize the confirmation box
![Capturar](https://user-images.githubusercontent.com/14100568/216327594-e7d18ec6-6e88-427b-a99a-306f10b742a6.JPG)

**Comment by lane-formio** [comment]
<div>Agent Jeriah Henley linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/52270">52270</a> for this issue.</div><br/>

**Comment by lane-formio** [comment]
There is no way to change that message programmatically but they can translate the message. Here is the documentation
https://help.form.io/developers/form-development/translations
