### ISSUE TITLE
[BUG] @formio/angular 5.5.0-rc.5 build error in formio.common.d.ts

### ISSUE THREAD

**Issue by GMacAussie** [formio/angular#938]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: Windows 10
- Formio.js version: 14.4.10
- Frontend framework: Angular 15.1.2
- @formio/angular version: 5.5.0-rc.5
- Browser: N/A
- Browser version: N/A

## Steps to Reproduce
1. Import @formio/angular into a source file
2. ng build

## Expected behavior
Clean build

## Observed behavior
```
Error: ../../node_modules/@formio/angular/formio.common.d.ts:4:18 - error TS2430: Interface 'ComponentOptions<T, V>' incorrectly extends interface 'ComponentSchema<T> & { [key: string]: any; }'.
  Type 'ComponentOptions<T, V>' is not assignable to type 'ComponentSchema<T>'.
    Types of property 'validate' are incompatible.
      Type 'V | undefined' is not assignable to type 'ValidateOptions | undefined'.
        Type 'V' is not assignable to type 'ValidateOptions | undefined'.
          Type 'V' is not assignable to type 'ValidateOptions'.

4 export interface ComponentOptions<T = any, V = ValidateOptions> extends ExtendedComponentSchema<T> {
                   ~~~~~~~~~~~~~~~~

  ../../node_modules/@formio/angular/formio.common.d.ts:4:44
    4 export interface ComponentOptions<T = any, V = ValidateOptions> extends ExtendedComponentSchema<T> {
                                                 ~~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends ValidateOptions` constraint.
  ../../node_modules/@formio/angular/formio.common.d.ts:4:44
    4 export interface ComponentOptions<T = any, V = ValidateOptions> extends ExtendedComponentSchema<T> {
                                                 ~~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends ValidateOptions | undefined` constraint.
```

## Example
N/A per above build error.

## Possible Fix?
It is a bit hard to infer what is supposed to happen here, but the following change results in a clean build.

**NOTE!** Since our project is still in development and haven't incorporated the Formio renderer it is unclear whether this works at runtime for Formio.

Edit the formio.common.d.ts with the following change by replacing line 4:

`export interface ComponentOptions<T = any, V = ValidateOptions> extends ExtendedComponentSchema<T> {`

with:

`export interface ComponentOptions<T = any, V extends ValidateOptions = ValidateOptions> extends ExtendedComponentSchema<T> {`

## Additional Information:
Here is our package.json:

```
  "dependencies": {
    "@angular/animations": "^15.1.2",
    "@angular/cdk": "^15.1.2",
    "@angular/common": "^15.1.2",
    "@angular/compiler": "^15.1.2",
    "@angular/core": "^15.1.2",
    "@angular/forms": "^15.1.2",
    "@angular/platform-browser": "^15.1.2",
    "@angular/platform-browser-dynamic": "^15.1.2",
    "@angular/platform-server": "^15.1.2",
    "@angular/router": "^15.1.2",
    "@formio/angular": "^5.5.0-rc.5",
    "@fortawesome/angular-fontawesome": "^0.12.1",
    "@fortawesome/fontawesome-svg-core": "^6.1.2",
    "@fortawesome/free-brands-svg-icons": "^6.1.2",
    "@fortawesome/free-regular-svg-icons": "^6.1.2",
    "@fortawesome/free-solid-svg-icons": "^6.1.2",
    "@ngneat/until-destroy": "^9.2.2",
    "@uirouter/angular": "^11.0.0",
    "@webcomponents/custom-elements": "^1.5.1",
    "angular-i18next": "^15.0.5",
    "formiojs": "^4.14.10",
    "i18next": "^22.4.9",
    "i18next-browser-languagedetector": "^7.0.1",
    "i18next-http-backend": "^2.1.1",
    "jest-editor-support": "^31.0.1",
    "jquery": "^3.6.3",
    "libphonenumber-js": "^1.10.19",
    "luxon": "^3.2.1",
    "ngx-numeral": "^1.0.0",
    "primeflex": "^3.2.1",
    "primeicons": "^6.0.1",
    "primeng": "^15.2.0",
    "rxjs": "^7.8.0",
    "signalr": "^2.4.3",
    "tslib": "^2.4.0",
    "typescript": "^4.8.2",
    "zone.js": "^0.12.0"
  },
```

**Comment by fedesnieg** [comment]
Were you able to fix it? I see the same error now

**Comment by GMacAussie** [comment]
The edit mentioned above fixes the error by hand. So far in a little testing there have been no issues.

**Comment by fedesnieg** [comment]
But that's changing a node_modules file?

**Comment by GMacAussie** [comment]
Yup. As I said we are in development and have not fully validated integration.

**Comment by wenbin9** [comment]
> 

what's change did you made? I encountered same error with angular 14. Thank you.

**Comment by wenbin9** [comment]
> export interface ComponentOptions<T = any, V extends ValidateOptions = ValidateOptions> extends ExtendedComponentSchema<T> {

@GMacAussie Thanks your your provided. It works after update with above content.

**Comment by RomanLetsuk** [comment]
@GMacAussie Thank you for your contribution!
