### ISSUE TITLE
[BUG] WebformBuilder.saveComponent event Issue with Angular 15

### ISSUE THREAD

**Issue by chakshutadesai** [formio/angular#941]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
         Version: Windows 11 
- Formio.js version: 5.5.0-rc.9
- Frontend framework: Angular 15.1.5
- Browser: Chrome
- Browser version: Version 110.0.5481.177

## Steps to Reproduce
1. Drag any component from the form builder (i.e. Text Field)
2. set properties
3. click on the save button to save the component on Form. 
4. On click on save button, getting console errors

## Expected behavior
SHould not give any errors, and save component on Form.
## Observed behavior
On click save button , gives console errors 
![image](https://user-images.githubusercontent.com/46338853/221186949-d3a4963a-6ff1-410e-9ba8-d7c7ff3fb997.png)
![image](https://user-images.githubusercontent.com/46338853/221187200-2fa40664-15d8-4350-a9ea-f4285bea270b.png)

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by closesimple-mf** [comment]
We are on angular 14.2.1 and also see this.  I haven't been able to reliably reproduce it.  I've only seen it twice on my machine which is a mac m1; my coworkers encounter it daily and they are on older windows laptops, so my best theory is its a timing/async issue related to angular event handlers and zones.

https://github.com/formio/angular/blob/master/projects/angular-formio/src/components/formbuilder/formbuilder.component.ts#L94

**Comment by RomanLetsuk** [comment]
@chakshutadesai we cannot reproduce the issue. You can check our demo repository with the latest @formio/angular version https://github.com/formio/angular-demo. Maybe you missed some configuration. Please provide some example in JSFiddle for example for future investigation. Thanks!

**Comment by olgabann** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you'd like to reopen the issue, please reply and we can resume the triage process.
