### ISSUE TITLE
[Question] How can I overwrite nested form component url ?

### ISSUE THREAD

**Issue by adhonay** [formio/angular#943]
I managed to overwrite by editing the editform of the nested form, from the first request. I look for a list of other forms. But after selecting a value from a returned form, it makes another request.

https://api.form.io/form/id_selected_in_drop_form/live=1

**How can I modify this second request? It is triggered out of nowhere, and has no reference to the editForm**

Edit Form Component
![image](https://user-images.githubusercontent.com/14100568/222531545-971079a5-1d38-4b07-b3fc-2eea435164a4.png)

Component
![image](https://user-images.githubusercontent.com/14100568/222530857-96ef05fd-7db8-4f95-89a2-d23a030ad120.png)

**Comment by brendanbond** [comment]
Make sure you set your applications baseUrl and projectUrl, please see our documentation: https://help.form.io/intro/application

**Comment by adhonay** [comment]
The documentation does not in example and is not clear about this. But by trial and error it worked.

I had already set the baseUrl and projectUrl, but the request to fetch the nestedForm always concatenated the form in the request url. because it always looked like this:

GET- https://myhost/form/{id}

But by the editForm of my own nestedForm I was able to modify the request like this:

GET- https://myhost/ComponenteNegocio/{id}

```
      {
                  "label": "Form",
                  "key": "form",
                  "weight": 10,
                  "components": [
                    {
                      type: 'select',
                      input: true,
                      dataSrc: 'values',
                      searchField: 'title__regex',
                      disabled: true,
                      label: 'Id Componente Negocio',
                      key: 'form',
                      weight: 10,
                      lazyLoad: false,
                      tooltip: 'Codigo de busca para retornar o componente de negocio criado.',
                      validate: {
                        required: true,
                      },
                      calculateValue(context) {
                        return 'ComponenteNegocio/' + context.instance.options.editComponent.id;
                      },
                    },
                    {
                      "type": "checkbox",
                      "input": true,
                      hidden: true,
                      "weight": 19,
                      "key": "useOriginalRevision",
                      "label": "Use Original Revision while Submissions Viewing",
                      "tooltip": "Using this option will make form load the original revision (the one which was used to make a submission) when viewing a submission."
                    },
 }
```

**Comment by adhonay** [comment]
> Certifique-se de definir seus aplicativos baseUrl e projectUrl, consulte nossos documentos: https://help.form.io/intro/application


I think that you, sir, should not conclude the post without actually answering the question asked, it is disrespectful.

But I'll put the answer, because it may help someone in the community.

The documentation does not in example and is not clear about this. But by trial and error it worked.

I had already set the baseUrl and projectUrl, but the request to fetch the nestedForm always concatenated the form in the request url. because it always looked like this:

GET- https://myhost/form/{id}?live=1

But by the editForm of my own nestedForm I was able to modify the request like this:

GET- https://myhost/ComponenteNegocio/{id}?live=1

```
      {
                  "label": "Form",
                  "key": "form",
                  "weight": 10,
                  "components": [
                    {
                      type: 'select',
                      input: true,
                      dataSrc: 'values',
                      searchField: 'title__regex',
                      disabled: true,
                      label: 'Id Componente Negocio',
                      key: 'form',
                      weight: 10,
                      lazyLoad: false,
                      tooltip: 'Codigo de busca para retornar o componente de negocio criado.',
                      validate: {
                        required: true,
                      },
                      calculateValue(context) {
                        return 'ComponenteNegocio/' + context.instance.options.editComponent.id;
                      },
                    },
                    {
                      "type": "checkbox",
                      "input": true,
                      hidden: true,
                      "weight": 19,
                      "key": "useOriginalRevision",
                      "label": "Use Original Revision while Submissions Viewing",
                      "tooltip": "Using this option will make form load the original revision (the one which was used to make a submission) when viewing a submission."
                    },
 }
```
however, it still continues concatenating the live=1 at the end of the request, but it does not disturb the request so I stopped researching how to fix it.
