### ISSUE TITLE
[Question]: How to customize the form builder wizard panel configuration

### ISSUE THREAD

**Issue by davidyoung77** [formio/angular#950]
I am using the Angular/Formio builder wizard for multiple pages/steps.

How can I customize the builder panel/modal for the wizard pages?

Referring to this wizard
![Screenshot 2023-03-30 at 5 01 25 PM](https://user-images.githubusercontent.com/13836016/228985052-4fe0443b-259a-4d97-a4fd-67bf120035da.png)

Referring to this panel modal that pops up when I edit a wizard page
![Screenshot 2023-03-30 at 5 00 55 PM](https://user-images.githubusercontent.com/13836016/228985170-5417bb44-20a3-4624-8566-cc9d07b95e68.png)

Can I customize the builder components that show up in this wizard panel modal?
If not can I build a custom component and get the wizard to use my own custom panel/page

I am able to configure the builder panel/modal for any custom components successfully

See example here:
![Screenshot 2023-03-30 at 5 00 36 PM](https://user-images.githubusercontent.com/13836016/228984661-2721b978-5073-478b-8725-cb39c1917d96.png)

**Comment by davidyoung77** [comment]
https://formio.github.io/formio.js/app/examples/custombuilder.html

Note this describes how to customize component schema but not how to customize a the component configuration for an existing component in the builder panel

**Comment by adhonay** [comment]
Hello, it is only possible to customize the editing modal of a custom component.
