### ISSUE TITLE
[Question] Latest version do not support bootstrap v5

### ISSUE THREAD

**Issue by wenbin9** [formio/angular#953]
Hi, I try @formio/angular v5.3.0 work with angular 14 and boostrap 5.2.0 project could start success, but form builder icon can't display.
How can I make it works? Seek for your help thanks!!

![image](https://user-images.githubusercontent.com/43366674/230616142-8719934b-b6ab-4f45-85b0-8d8e0fbce2fc.png)

**Comment by HannaKurban** [comment]
@wenbin9 this item in progress right now. You can see https://github.com/formio/angular/pull/940. Thank you!
