### ISSUE TITLE
Bug: builder change eventEmitter causing Object is possibly undefined issue

### ISSUE THREAD

**Issue by davidyoung77** [formio/angular#955]
https://github.com/formio/angular/blob/c5f26aec4e1beae980761a96f2008e27dca3625b/projects/angular-formio/src/components/formbuilder/formbuilder.component.ts#L46

This is causing an issue `Object is possibly 'undefined'.`

Can this line be changed to this: `@Output() change: EventEmitter<object>; `
So that the issue no longer exists?
Notice the options `?` is removed.

You can see the error in the image here:

<img width="1073" alt="Screenshot 2023-04-13 at 10 17 09 AM" src="https://user-images.githubusercontent.com/13836016/231822205-ff850128-b008-4d17-9e32-465f87384bfb.png">

**Comment by HannaKurban** [comment]
This issue has been fixed by https://github.com/formio/angular/pull/896
