### ISSUE TITLE
[Question] When Angular 15 npm package will release?

### ISSUE THREAD

**Issue by deep913** [formio/angular#956]
Dear Members,
Thanks for this awesome plugin!

I have been using this plugin in one of our project with Angular v12 but now we are planing to move with v15, but the formio supports till v13 as per the npm package and while installing the same on my current project generates dependency issues. I used this repo and generated a new plugin which is v5.5.0 but it has many issues. So could you please tell me when do i expect the latest release of formio supporting v15?

Thanks in advance,
Inder

**Comment by abhishekcpwebline** [comment]
Hi @deep913 - I am trying to clone this repo and doing npm install, after that when I hit ng serve, it gives me error.

Any suggestion ? I am trying to use this plugin to create a custom component with multiple fields, But not getting any luck.


Guide me how to use this properly.

Thanks.

**Comment by HannaKurban** [comment]
@deep913 Since version 5.5.0, there is support for Angular 15. If you have any issues, please specify them, then we will be able reproduce and investigate them.
