### ISSUE TITLE
[BUG] Issue running / building angular application inside docker with Angular v13

### ISSUE THREAD

**Issue by deep913** [formio/angular#959]
Hi Team,
Thanks for such an awesome plugin

I have been using formio plugin with different projects in angular and it's working fine. Previously i was using v5.2.0 with angular v12 it was running fine with docker and not giving any kind of issue.

But with the version upgrade to Angular v13 and v5.3.0 the plugin started giving me the following error 

`Error: export 'FormUtils' (imported as 'FormUtils') was not found in '@formio/angular'`

The strange thing is that if i'm running the same application through my system settings without docker, it's running fine without any issue. I'm stuck at this point, i appreciate if you can help me to resolve the issue 

I'm sharing one screenshot:
<img width="1440" alt="Screenshot 2023-04-22 at 10 30 36 PM" src="https://user-images.githubusercontent.com/79099674/233797608-97e5926d-a54f-43ad-abb0-e5787138a34d.png">

Thanks in advance,
Deep

**Comment by HannaKurban** [comment]
Hi @deep913 ! Probably the issue with docker image build. Could  you provide us an information how are you building docker image?

**Comment by deep913** [comment]
@HannaKurban thanks for your reply, meanwhile i replaced the **import from @formio/angular** to **formiojs** and it's working fine with docker, the problem is in the @formio/angular import

**Comment by muneebshafiq** [comment]
@deep913 please close the issue if it's resolved! :)
