### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by danickblouin** [formio/angular#961]
Hi, I found a typo in the [*Input*](https://github.com/formio/angular/wiki/Form-Renderer#inputs) section of the Form-Renderer page. In the third column of the last row of the input's table "following" is written as "follwoing".

I wanted to make a PR but it seems like we need to be contributors to edit a Wiki pages.

**Comment by wag110894** [comment]
Hello @danickblouin.

Thanks for reaching out and letting us know. We will get this fixed.
