### ISSUE TITLE
How to load controls in a tab only when the tab is active

### ISSUE THREAD

**Issue by subash-arveti** [formio/angular#966]
Can some suggest how to load controls in tab only when it is active.

**For example:** Consider we have a page with 2 tab. In one tab we have around 5 controls and second tab contains around 10 controls.
when we navigate to the page by default first tab will be active and should load only  5 controls from that tab. It should not load the 10 controls from second tab until we click on that tab and it becomes active.

**Comment by RomanLetsuk** [comment]
@subash-arveti it's not possible. As form JSON contains all required information, all tabs will be rendered immediately. If you can provide more details what you are trying to achieve and what problems you have with this behavior, we can provide some additional information. Thanks!

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
