### ISSUE TITLE
[Question] Formio is cleaning the values ​​of the disabled components when sending, how to fix it?

### ISSUE THREAD

**Issue by adhonay** [formio/angular#968]

**Comment by adhonay** [comment]
Please help me!!!

@travist @wag110894

**Comment by brendanbond** [comment]
@adhonay Can you elaborate? Please provide a minimal reproducible example rather than just a one sentence question in the title of the issue. Thanks!

**Comment by adhonay** [comment]
Sorry about the way. @brendanbond 

I can't send a simulation as they are custom components.

But I'll go into more detail:

I have a textfield field, which is disabled and initially with an empty value, and when receiving an event from the button, it makes the https request and fills it with the equivalent data.

I have a buttom that emits an event for the textfield.

So far so good, the problem is when I send the form, it automatically deletes the value that was filled in by the service request from text field 1.

I've looked at several things, and found some cases that the library apparently erases the values ​​of disabled fields when sending, how could I ignore that?

![image](https://github.com/formio/angular/assets/14100568/4e7df6f4-3856-4166-9f79-6a47b5e883e8)

**Comment by HannaKurban** [comment]
@adhonay Could you please provide a jsfiddle example or form json so that we can reproduce and investigate the issue.

**Comment by adhonay** [comment]
@HannaKurban  I understand, for me to be able to simulate the error, I need to be able to solve this doubt: #969 

Because to simulate I need to disable a field that has value. Or insert a value in a disabled field. Remembering that value would be inserted via http request.

I couldn't find any example doing this. And I can't replicate my error, not even in the select component, which is the only one that makes the http request.

**Comment by adhonay** [comment]
I discovered the solution, for every custom component, it was going through a generic method in the basecomponentformio, so I modified it for cases that are disabled.
