### ISSUE TITLE
[Question]  Is there any way I can customize the disabling of components?

### ISSUE THREAD

**Issue by adhonay** [formio/angular#969]
In the editing modal there is an advanced option, for validation, data and display of the component, but I couldn't find it to enable or disable the component.

I would like to configure it to disable a specific component depending on the value in another component. But I tried different ways and I couldn't. I would like to configure via interface.

![image](https://github.com/formio/angular/assets/14100568/80f39a98-07ef-4552-bbd5-3bd993a046e4)

**Comment by RomanLetsuk** [comment]
Hi @adhonay. You need to interact with instance object instead of component. 
`instance.disabled = true;`

**Comment by adhonay** [comment]
@RomanLetsuk 

It doesn't work, I've tried several combinations

instance.component.disabled = true;
instance._parentDisabled = true;
instance.originalComponent.disabled = true;
instance._disabled=true;
instance.disabled=true;

**Comment by adhonay** [comment]
I managed to disable it by rule using the logical tab.
![image](https://github.com/formio/angular/assets/14100568/cd8d680c-dff1-4bba-9ed8-214f68aa9b47)
