### ISSUE TITLE
[Custom Components] How can I get the json if submitting the form render inside cunstom component?

### ISSUE THREAD

**Issue by adhonay** [formio/angular#983]
For example :

I save a form and it generates this submission json:

```
date : {
selectCity: '2',
textname: 'jake',
age: '55'
},
metadata : {
    "selectData": {
      "selectCity"{
        "label":"test"
      }
    }
}
```

How can I get the metada inside my custom component select? to get the value of the label

**Comment by HannaKurban** [comment]
@adhonay  Could you please describe your use case in more detail or provide a more detailed example??
