### ISSUE TITLE
[BUG] Can't open permissions screen

### ISSUE THREAD

**Issue by gonlopherfuj** [formio/angular#988]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 6.0.0-rc.5
- Formio.js version: 5.0.0-rc.23
- Frontend framework: Angular
- Browser: Google Chrome 
- Browser version: 114.0.5735.199

## Steps to Reproduce
1. Access the form or resource section
2. In any form or resource, select the fourth option from left to right, which is permissions.
3. It is not redirected to any screen and if we open the console the error appears.

## Expected behavior
It should open the permissions screen
## Observed behavior
The permissions screen does not open and an error appears in the console
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

![BUG FORMIO](https://github.com/formio/angular/assets/142219947/3883de77-2862-46fd-a11b-36e88c4da2af)

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by HannaKurban** [comment]
Hey @gonlopherfuj ! Thank you for reaching out. We will investigate this issue.

**Comment by daneformio** [comment]
@gonlopherfuj The version of the renderer you are using (5.0.0-rc.27) is supported by the 6.5.0 version of formio/angular. Please upgrade and see if the issue is still present.

**Comment by Tatsiana8** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days, I will close it for now. If you wish to reopen the issue, please respond and we can resume the triage process.
