### ISSUE TITLE
[BUG] Can't create resources

### ISSUE THREAD

**Issue by gonlopherfuj** [formio/angular#989]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 6.0.0-rc.5
- Formio.js version: 5.0.0-rc.23
- Frontend framework: Angular
- Browser: Google Chrome
- Browser version: 114.0.5735.199

## Steps to Reproduce
1. Access the resources section
2. Click on the create form button
3. Enter any test data and save form

## Expected behavior
What we have created should appear in the "Resources" section
## Observed behavior
What we have created appears in the "Forms" section
## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by roma-formio** [comment]
Hey @gonlopherfuj! Thank you for reaching out. We will investigate this issue.

**Comment by prathmchavan** [comment]
hello @gonlopherfuj  can you elaborate more on Expected behavior  and Observed behavior while going through the website i didn't get the issue like what you wanted to tell

**Comment by gonlopherfuj** [comment]
Hi, 

I do the following:

I am in the resources tab, I click on the create form button below, I add a component and I save.

Since I am in the resources tab, a resource should be created but instead a form is created. So, I can't find a way to create resources.
