### ISSUE TITLE
How to change the default tooltip messages for basic components using Formio with Angular 15

### ISSUE THREAD

**Issue by dheeksha02** [formio/angular#991]
Tried the solutions by setting properties through "editForm" properties. But no luck on it. Can someone please suggest any solution on it

**Comment by roma-formio** [comment]
@dheeksha02 can you provide a small example of what exactly you are doing with some code sandbox?

**Comment by dheeksha02** [comment]
@roma-formio , Want to change the tooltip messages of label field
![image](https://github.com/formio/angular/assets/142782729/56a147b3-a5d0-42ea-a684-77163b0e7997)

**Comment by adhonay** [comment]
You can use the same translation logic, in my case I translated the text, but you can change it to the message you want, but it will affect the entire project.

`export const DefaultOption = {
  noDefaultSubmitButton: true,
  idFormioOptions: ConstantesOptionsFormBuilder.principal,
  // alwaysConfirmComponentRemoval: true //alerta ao remover componente.
  builder: {
    basic: {
      title: "Componentes Basicos",
      components: {
        textfield: false,
        textarea: false,
        number: false,
        password: false,
        checkbox: false,
        select: false,
        selectboxes: false,
        radio: false,
        button: false,

        customInputText: true,
        customInputMask: true,
      },
    },
    layout: {
      default: true,
      components: {
        htmlelement: false,
        content: false,
        columns: true,
        fieldset: true,
        panel: true,
        table: true,
        tabs: true,
        well: true,
      },
    },
    advanced: false,
    premium: false,
    data: false
  },
  editForm: {
    customInputText: customInputText,
    customInputMask: customInputMask
  },
  language: "pt-BR",
  i18n: {
    // https://docs.form.io/developers/translations
    pt: { 
    'The label for this field that will appear next to it.': 'Label que irá aparecer próximo ao campo.',
     },
  },
};
`
