### ISSUE TITLE
In forms layout field properties how to change the default filled text.

### ISSUE THREAD

**Issue by dheeksha02** [formio/angular#992]
Renamed the "Panel Component " as "Section"
![image](https://github.com/formio/angular/assets/142782729/fbe62abb-93aa-4051-96e2-53d75ddbb6ef)
![image](https://github.com/formio/angular/assets/142782729/44b3ddbf-c0df-4d4e-8cc4-e285172f021f)

Want to change the highlighted text as "section"
![image](https://github.com/formio/angular/assets/142782729/0c9e3806-f4dc-4cf2-8e90-20da5de0542e)

Can someone please help out.

**Comment by brendanbond** [comment]
It's in the editForm file for that component
