### ISSUE TITLE
[BUG] Search field(s) not working

### ISSUE THREAD

**Issue by gonlopherfuj** [formio/angular#997]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 6.0.0-rc.5
- Formio.js version: 5.0.0-rc.27
- Frontend framework: Angular
- Browser: Google Chrome
- Browser version: 114.0.5735.199

## Steps to Reproduce
1. Access the form or resources section
2. Click on the create or edit form button
3. Enter any letter or word in the component search

## Expected behavior
It should show me those components that match the searched pattern

## Observed behavior
It doesn't show me any components.

I want to add an image that may help the solution. Debugging the code I realize that 'sidebar-groups' is null and that's why it doesn't look for anything, it enters the first return and the code ends.

![image](https://github.com/formio/angular/assets/142219947/8369395b-ee6f-4303-b1fa-ab7e83936199)

**Comment by adhonay** [comment]
Can you run the ng serve command and send me a printout?
I would like to know the version of your angular cli, node and npm.

**Comment by gonlopherfuj** [comment]
Hi, 

node: v16.14.0
npm: v9.4.2
angular cli: v16.2.0

**Comment by lane-formio** [comment]
Thank you for your contribution. As this issue has been inactive for over 90 days and looks be resolved, I will close it for now. If you wish to reopen the issue, please respond, and we can resume the triage process.
