### ISSUE TITLE
[Question] Is it possible to translate the text (placeholder) of the component search field within the creation / edition of forms and / or resources?

### ISSUE THREAD

**Issue by gonlopherfuj** [formio/angular#998]
I want to translate the placeholder that I attached in the image but I can't find the way. I have tried with the i18n from the options but it doesn't work. I have also tried to look for that placeholder in the code of the formio/js library but I can't find it. Any way to do it?

![image](https://github.com/formio/angular/assets/142219947/c22c3044-66bf-4433-8544-9ce67acaf5d7)

**Comment by adhonay** [comment]
I resolved it this way: #949
